### ISSUE TITLE
Nan image

### ISSUE THREAD

**Issue by lukasfolle** [nipy/nibabel#1002]
Hi,
I am participating in this challenge and have problems reading a nifti file https://valdo.grand-challenge.org/.
Specifically, file 320 t2.nii.gz is not readable while t2s.nii.gz is readable.

If you can replicate this erro ,could you please have a look at whats going on there?
[sub-320_space-T2S_desc-masked_T2.nii.gz](https://github.com/nipy/nibabel/files/6143246/sub-320_space-T2S_desc-masked_T2.nii.gz)
[sub-320_space-T2S_desc-masked_T2S.nii.gz](https://github.com/nipy/nibabel/files/6143248/sub-320_space-T2S_desc-masked_T2S.nii.gz)

**Comment by effigies** [comment]
Hi, sorry for the delay. The `nan` image just needs its `nan`s replaced by 0s, I think. Something like:

```Python
import numpy as np
import nibabel as nb

img = nb.load(fname, mmap=False)
data = img.dataobj[:]
data[np.isnan(data)] = 0
new_img = nb.Nifti1Image(data, img.affine, img.header)
new_img.to_filename(fname)
```

**Comment by lukasfolle** [comment]
Thank you for your help!
