### ISSUE TITLE
Editing img/hdr pair

### ISSUE THREAD

**Issue by PavanChaggar** [nipy/nibabel#1004]
Hi there, 

I have some .img and .hdr files from OASIS1 that I'd like to reorient and save as nifti. I can't work out how to open the files using nibabel.
I thought it would be; 
`nib.load("filename.img", header="filename.hdr")` 
but this does not work as there is no argument for header. 

Any advice on if/how I can do this? 

Thanks, 
Pavan

**Comment by matthew-brett** [comment]
What do you get for:

```
img = nib.load("filename.img")
```

?

**Comment by PavanChaggar** [comment]
`nib.load("filename.img")`
nibabel.spm2analyze.Spm2AnalyzeImage at 0x13c1c1a90

is what gets returned. 

Is this all I need?

**Comment by matthew-brett** [comment]
I think so - unless you want to specify that the `.img` format is something other than the SPM2 extended Analyze format.   For example, if you thought the file was Nifti1 format instead of SPM2 Analyze:

```
img = nib.nifti1.load('filename.img')
```

**Comment by PavanChaggar** [comment]
Ok thanks. It sounds like this is all I need then. 
Is there a straightforward way to convert to RAS orientation? 
It seems I can compose some functions from nibabel.orientations, but wondering if there's something simpler.

**Comment by effigies** [comment]
Check out the nib.as_closest_canonical function.
