### ISSUE TITLE
ModuleNotFoundError with nibabel

### ISSUE THREAD

**Issue by amsinha9** [nipy/nibabel#1006]
When I'm importing nibabel, I get the following error:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-1865394ef9c8> in <module>()
----> 1 import nibabel
      2 import nilearn.plotting as plotting
      3 import numpy as np
      4 import matplotlib.pyplot as plt
      5 import hcp_utils as hcp

~\AppData\Roaming\Python\Python36\site-packages\nibabel\__init__.py in <module>()
     36 """
     37 # module imports
---> 38 from . import analyze as ana
     39 from . import spm99analyze as spm99
     40 from . import spm2analyze as spm2

~\AppData\Roaming\Python\Python36\site-packages\nibabel\analyze.py in <module>()
     85 import numpy as np
     86 
---> 87 from .volumeutils import (native_code, swapped_code, make_dt_codes,
     88                           shape_zoom_affine, array_from_file, seek_tell,
     89                           apply_read_scaling)

~\AppData\Roaming\Python\Python36\site-packages\nibabel\volumeutils.py in <module>()
     20 import numpy as np
     21 
---> 22 from .casting import (shared_range, type_info, OK_FLOATS)
     23 from .openers import Opener
     24 from .deprecated import deprecate_with_version

~\AppData\Roaming\Python\Python36\site-packages\nibabel\casting.py in <module>()
      9 
     10 import numpy as np
---> 11 from .testing import setup_test  # flake8: noqa F401
     12 
     13 

~\AppData\Roaming\Python\Python36\site-packages\nibabel\testing\__init__.py in <module>()
     19 from numpy.testing import assert_array_equal
     20 
---> 21 from numpy.testing.decorators import skipif
     22 # Allow failed import of nose if not now running tests
     23 try:

ModuleNotFoundError: No module named 'numpy.testing.decorators'

How do I resolve this?

For reference, I have the following packages and versions:

nibabel: 2.3.0
numpy 1.19.5
scipy: 1.5.4

**Comment by effigies** [comment]
You're going to need to either use a new nibabel or an older numpy. Is there a reason you need 2.3.0?

**Comment by amsinha9** [comment]
No, there is no particular dependencies on versions for my current purpose. I was running an old script from a while back and realized the error now. Any suggestions on which versions of nibabel and/or numpy I can use to resolve this?

**Comment by effigies** [comment]
I would suggest upgrading to the latest nibabel if you don't have any reason to use an older version.
