### ISSUE TITLE
Question about orientations

### ISSUE THREAD

**Issue by akeshavan** [nipy/nibabel#1010]
Hello! I have some niftis I need to reorient from whatever orientation they come in, to LPS. Here's what I have after some trial and error:

```python
img = nib.load("some_file.nii.gz")

print('original orientation:', nib.orientations.ornt2axcodes(nib.orientations.io_orientation(img.affine)))

ornt = nib.orientations.axcodes2ornt("ASL")
img_orient = img.as_reoriented(ornt)

print('final orientation:', nib.orientations.ornt2axcodes(nib.orientations.io_orientation(img_orient.affine)))

```

and it prints:

```
original orient: ('P', 'S', 'R')
final orient: ('L', 'P', 'S')
```

I played around with the three letter orientation string in this line:

```python
ornt = nib.orientations.axcodes2ornt("ASL")
```

until my final orientation was `LPS`. What am I doing? Why did this work? How do I make it work for any arbitrary orientation? 

Thanks for your help!

**Comment by effigies** [comment]
Hey Anisha. So `as_reoriented` doesn't take axcodes, but instead takes a representation of axis flips and rolls. You need to find the transform from where you are `io_orientation(affine)` to where you want to be `axcodes2ornt("LPS")`:

```Python
orig_ornt = nb.io_orientation(img.affine)
targ_ornt = axcodes2ornt("LPS")
transform = ornt_transform(orig_ornt, targ_ornt)

img_orient = img.as_reoriented(transform)
```

In case it's helpful, there's also a Nipype interface that does this: [Reorient](https://github.com/nipy/nipype/blob/6c060304f380c46b2f05c5afdc7171dbbdfadc58/nipype/interfaces/image.py#L108-L222)

**Comment by akeshavan** [comment]
thanks @effigies !!
