### ISSUE TITLE
Align orientations

### ISSUE THREAD

**Issue by ch-n** [nipy/nibabel#1011]
Hi,
I try to cast image to a different orientation.
My images have the axcodes ('L', 'A', 'S') and ('L', 'S', 'P'). I try to cast them to the orientation of the napari viewer (axcode ('P', 'I', 'L')).

I take the image orientation from the affine with `nib.orientations.io_orientation` and the orientation of the viewer with `nib.orientations.axcodes2ornt`. To transform the image to the orientation of the viewer I use `nib.orientations.ornt_transform` and `nib.orientations.apply_orientation` to the image data array.

This works perfectly with the ('L', 'S', 'P') image but not at all with the ('L', 'A', 'S') one.
Am I doing something wrong or might there be a bug?

Nibabel Version:
'3.2.1dev'

Best regards,
Chris

**Comment by effigies** [comment]
Does #1010 help?

**Comment by ch-n** [comment]
Sadly not, using `imgobj.as_reoriented` instead of `nib.orientations.ornt_transform` yields the same results.
The  ('L', 'A', 'S') is converted to ('I', 'A', 'L') and not ('P', 'I', 'L').

**Comment by effigies** [comment]
That should work... Could you share a reproduction where it fails so we can add a test and fix the issue?

**Comment by ch-n** [comment]
I'm really sorry to have wasted your time. I found the error. 

It was on my side as I did not noticed that my perception of the wrong orientation was based on a wrong assumption. The images I compared are highly rotated to each other and the LAS images are quite thin in the z-axis. I misinterpreted there alignment. 

They are aligned as best as possible without applying affine transformation.
