### ISSUE TITLE
`as_closest_canonical` fails for Nifti1Images created using `header` and `affine=None`

### ISSUE THREAD

**Issue by joshuacwnewton** [nipy/nibabel#1012]
> For context, this was encountered in https://github.com/ivadomed/ivadomed/issues/775.

Say we create a `Nifti1Image` by specifying the header but leaving `affine=None`:

```python
    img = nib.Nifti1Image(
        dataobj=data_array,
        affine=None,
        header=img_ref.header.copy()
    )
```

My expectation here was that because the header contains affine-related fields (with an affine retrieved using `header.get_best_affine()`), it would be unnecessary/redundant to also specify `affine` when creating the image.

However, if we then call `nibabel.funcs.as_closest_canonical` on the image, it will fail, because the function accesses `img.affine` directly, ignoring the header affine.

https://github.com/nipy/nibabel/blob/62aea04248e70d7c4529954ca41685d7f75a0b1e/nibabel/funcs.py#L204-L205

----

I'm reminded of an observation from @pauldmccarthy in https://github.com/nipy/nibabel/issues/1001 (emphasis mine):

> When creating a new image from an existing image (e.g. after some processing step), using the header from the original image to preserve the NIFTI header metadata **(not that there's much of use in there, but that's another matter)**:

Because of this, I'm wondering: Should we even be copying the header when creating an image? Or, should we instead be specifying `affine`? 

The reason we chose to copy the header is outlined in https://github.com/ivadomed/ivadomed/pull/714, but perhaps there is a better way to solve that problem.

Thanks in advance! :blush:

**Comment by effigies** [comment]
In this case, I believe I would probably set both affine and header. Setting `affine=None` is something I would only do if I wanted to skip consistency checks while saving a file, so it works fine if you're creating the image and immediately saving it.

Assuming that `img.affine == img.header.get_best_affine()` (which will be true if you're loading `img` from file), then `Nifti1Image(data, img.affine, img.header)` will get you the same thing, but also allow you go modify the file. If you don't trust your affine but do trust your header, then `Nifti1Image(data, img.header.get_best_affine(), img.header)` should work fine.

**Comment by joshuacwnewton** [comment]
Thank you for the quick response. I also notice this in the [`Nifti1Image`](https://nipy.org/nibabel/reference/nibabel.nifti1.html#nibabel.nifti1.Nifti1Image) docs:

> If both a header and an affine are specified, and the affine does not match the affine that is in the header, the affine will be used, but the sform_code and qform_code fields in the header will be re-initialised to their default values. This is performed on the basis that, if you are changing the affine, you are likely to be changing the space to which the affine is pointing. The set_sform() and set_qform() methods can be used to update the codes after an image has been created - see those methods, and the manual for more details.

Since our goal was to preserve the codes, I guess we have two options, then? 
* `Nifti1Image(data, img.header.get_best_affine(), img.header)` as you suggest (to ensure that the affines match and won't be reset).
* `Nifti1Image(data, img.affine, img.header)`, but then explicitly use `set_<x>form()` to ensure that the codes are as expected.

**Comment by joshuacwnewton** [comment]
I think our question has been answered, so I'll close this issue. Thanks again!
