### ISSUE TITLE
Setting slop and intercept does not work.

### ISSUE THREAD

**Issue by vpapaioannou** [nipy/nibabel#1015]
import nibabel as nib
         old = nib.nifti1.load(old_nifti)
         old.header.set_slope_inter(1.0, 0.0)
         print(old.header.get_slope_inter()) # gives 1.0 and 0.0 as expected, it was NaN, NaN initially
         nib.nifti1.save(old, new_nifti)
         new = nib.nifti1.loadnew_nifti)
         print( new.header.get_slope_inter()) # gives NaN, NaN which is unexpected

Also, reading initially NaN, NaN values for slope and intercept, is not correct. The actual values are `scl_inter -1024, scl_slope 1` as I get them from SimpleITK.

Finally, when I try to update the datatype, the datatype is updated as expected into the `new_nifti`.

Please help.

**Comment by matthew-brett** [comment]
Did you find : https://nipy.org/nibabel/nifti_images.html#data-scaling

We'd be very happy for any suggestions on how we could improve the docs or make them more visible.

**Comment by vpapaioannou** [comment]
Thanks for the resource, I didn't find it. I read it and using `.dataobj.slope` and `.dataobj.inter` I see the expected values for the original file. Nonetheless, for the new file I get `18.200000762939453, -1024.0` instead of `1.0, 0.0` as I set it.Why is that?

If you would like some feedback, the way that is implemented right now for `datatype` and e.g. `slope` it seems having two interfaces to access some header information. The interface for `slope` is not as intuitive as is for `datatype`, especially for SimpleITK users. I believe, that a `datatype` access interface should be exposed to the user not matter what happens behind the scenes. Why would I need to read the resource you shared at first place?

As for the documentation, I'd suggest a simple and basic tutorial, how to read/write a nifti image, get/set the headers and get/set the image data e.g. change data type to the actual array.

**Comment by matthew-brett** [comment]
Thanks for the suggestions.   There is of course a reason why the interface is as it is, and we probably can't change it now, but we should definitely think about adding another and easier interface that will be less confusing.
