### ISSUE TITLE
Resample 3D image

### ISSUE THREAD

**Issue by talhaanwarch** [nipy/nibabel#1021]
Can we resample 3D MRI image to a fix z-axis length? 
I have image of different z-axis such as `(512,512,110)`,`(512,512,117)`,`(512,512,103)`. Can I make all of them to equal length.

**Comment by matthew-brett** [comment]
You could try having a look at:
https://nipy.org/nibabel/reference/nibabel.processing.html#nibabel.processing.resample_from_to
But - please do ask this kind of question on the mailing list - the issues here are for reporting bugs, asking for new features.
