### ISSUE TITLE
Permission Error Windows System 

### ISSUE THREAD

**Issue by panchel** [nipy/nibabel#1028]
Hi everyone! I have been trying to use the python package resector (https://github.com/fepegar/resector), description: Implementation of a TorchIO transform used to simulate a resection cavity from a T1-weighted brain MRI and a corresponding geodesic information flows (GIF) brain parcellation (version 3.0), but am getting the error "PermissionError: [Errno 13] Permission denied: 'C:\\Users\\yingt\\AppData\\Local\\Temp\\tmp_3soszuh.nii'"

For context, I have Python version: 3.7.9 and Operating System: Windows x64. The traceback shows the error occurs when: 
File "c:\users\yingt\appdata\local\programs\python\python37\lib\site-packages\nibabel\openers.py", line 113, in __init__
    self.fobj = opener(fileish, *args, **kwargs)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\yingt\\AppData\\Local\\Temp\\tmp_3soszuh.nii'

I have tried running command prompt and git bash as an administrator, tried on two separate PCs, changed the properties of the Appdata and Temp folders so all users have access, and it all has not worked. From what I understand, most people using MacOS have no problem using this package. Is this a windows problem or is there anything else I can do?

Thanks!

**Comment by effigies** [comment]
Are you able to `open()` the file?

**Comment by panchel** [comment]
> Are you able to `open()` the file?

which file are you referring to? The tmp_3soszuh.nii file in the Temp folder was never created because for some reason, the package does not have permission to make the files in the Temp folder. However, I can add a file.txt in Temp.

**Comment by effigies** [comment]
> > Are you able to `open()` the file?
> 
> which file are you referring to?

I meant, in Python:

```Python
>>> open(r'C:\Users\yingt\AppData\Local\Temp\tmp_3soszuh.nii', 'rb')
```

Anyway, I think I'm misunderstanding what's going on. Could you share what you specifically did, either as a command that you ran, or a sequence of Python lines, and the full tracebacks?

**Comment by panchel** [comment]
Yes absolutely!

To use the package, you have to run "resect path/to/Nifti/file path/to/parcellation.nii.gz path/to/output.nii.gz path/to/output_label/nii.gz"

I specifically ran 
resect /c/Users/username/Desktop/folder/mni_icbm152_t1_tal_nlin_asym_09c.nii /c/Users/username/Desktop/folder/17549_NeuroMorph_Parcellation.nii.gz /c/Users/username/Desktop/folder/outcome.nii.gz /c/Users/username/Desktop/folder/outcome_label.nii.gz

and the full traceback was

Traceback (most recent call last):
  File "C:\Users\yingt\AppData\Local\Programs\Python\Python37\Scripts\resect-script.py", line 33, in <module>
    sys.exit(load_entry_point('resector', 'console_scripts', 'resect')())
  File "c:\users\yingt\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\yingt\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\users\yingt\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\yingt\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\yingt\resector\resector\cli\resect.py", line 59, in main
    parcellation_path,
  File "c:\users\yingt\resector\resector\cli\resect.py", line 126, in ensure_images
    parcellation_path, hemisphere)
  File "c:\users\yingt\resector\resector\parcellation.py", line 56, in get_gray_matter_mask
    mask = nib_to_sitk(array, parcellation_nii.affine) > 0
  File "c:\users\yingt\resector\resector\io.py", line 70, in nib_to_sitk
    nib.Nifti1Image(array, affine).to_filename(f.name)
  File "c:\users\yingt\appdata\local\programs\python\python37\lib\site-packages\nibabel\filebasedimages.py", line 333, in to_filename
    self.to_file_map()
  File "c:\users\yingt\appdata\local\programs\python\python37\lib\site-packages\nibabel\analyze.py", line 1030, in to_file_map
    hdrf = hdr_fh.get_prepare_fileobj(mode='wb')
  File "c:\users\yingt\appdata\local\programs\python\python37\lib\site-packages\nibabel\fileholders.py", line 70, in get_prepare_fileobj
    obj = ImageOpener(self.filename, *args, **kwargs)
  File "c:\users\yingt\appdata\local\programs\python\python37\lib\site-packages\nibabel\openers.py", line 113, in __init__
    self.fobj = opener(fileish, *args, **kwargs)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\yingt\\AppData\\Local\\Temp\\tmp_3soszuh.nii'

Thank you!

**Comment by effigies** [comment]
@fepegar Any chance you can track this one down? I can probably look at resector tomorrow if not.

**Comment by matthew-brett** [comment]
Just a guess - but maybe the code is trying to re-use the name from a NamedTemporaryFile - https://stackoverflow.com/questions/23212435/permission-denied-to-write-to-my-temporary-file

**Comment by fepegar** [comment]
@effigies Thanks for the heads-up. @panchel did report this at https://github.com/fepegar/resector/issues/3 before posting here. We'll keep you posted here.

@matthew-brett thanks for investigating. It looks like it might be that, but I'm surprised it only happens on Windows.

**Comment by fepegar** [comment]
This works on my mac:

```python
In [5]: import numpy as np
   ...: import nibabel as nib
   ...: from tempfile import NamedTemporaryFile
   ...:
   ...: with NamedTemporaryFile(suffix='.nii') as f:
   ...:     x = np.zeros((4, 4, 4))
   ...:     img = nib.Nifti1Image(x, np.eye(4))
   ...:     nib.save(img, f.name)
```

**Comment by matthew-brett** [comment]
Yes - that's what I'd expect - that it would work on Mac or Linux, but not on Windows.  See the StackOverflow post quote from the Python docs:

>   Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows NT or later).

<https://docs.python.org/3.8/library/tempfile.html>

**Comment by fepegar** [comment]
Oh, I see. Is there a way to pass a file object to `nib.save`, instead of a string or path object? If not, I guess I will need to change the implementation within `resector`.

**Comment by matthew-brett** [comment]
If you're always using standalone `.nii` files, you could `write` the output of `img.to_bytes()` - as in something like:

```python
f.write(img.to_bytes())
```

I think ...

**Comment by fepegar** [comment]
That looks good. I will modify that, try it on mac/Linux, work with @panchel to make sure it works on Windows, and let you know how it went. Thanks again!

**Comment by panchel** [comment]
Thank you so much everyone for helping me with this issue!

I'm pretty new to python, so I really appreciate all your input. Please let me know if there is anything I can do (run commands, etc) to help resolve this. Again, thank you all.

**Comment by effigies** [comment]
I wonder if SimpleITK can read a bytestring, so you could change to something like

```Python
niistring = nb.Nifti1Image(...).to_bytes()
image = sitk.NiftiImage1Image.read(niistring)
```

I don't know their syntax enough to get that right, but it looks like they have a method that will read a buffer: https://itk.org/Doxygen/html/classitk_1_1NiftiImageIO.html#a9311accde0fc96072b942e40a567e21f

**Comment by fepegar** [comment]
Thanks, @effigies. I have switched to using TorchIO to convert from array+affine to SITK, which doesn't involve writing and reading: https://github.com/fepegar/torchio/blob/master/torchio/data/io.py#L228-L268

I actually use some NiBabel code for that, so you'll find some links to NiBabel in my code.

I think this issue can now be closed.

**Comment by effigies** [comment]
Glad you got it working!
