### ISSUE TITLE
nifti to dicom - creating ImageOrientationPatient / ImagePositionPatient from nifti affine

### ISSUE THREAD

**Issue by tomaroberts** [nipy/nibabel#1033]
Hi there,

I am creating 4D flow MRI DICOMs, effectively from scratch, using our in-house 4D flow nifti files as a starting point. I'm using nibabel to read in my nifti files and then pydicom to create the DICOMs and propagate the relevant DICOM tags. However, I haven't ported across the orientation information yet.

I can easily access the affine information in the nifti headers, but I was wondering how to create the ImageOrientationPatient and ImagePositionPatient tags using the nifti affine - is there a function in nibabel which will help with this? Or I guess pydicom for if you happen to be familiar with it at all.

If not, I guess I can code something up following the docs here?: https://nipy.org/nibabel/dicom/dicom_orientation.html. Just wondering if you know of any existing tools for doing this before I wade in.

Many thanks,
Tom

**Comment by aaroncapon** [comment]
Hi @tomaroberts 

 I also need to calculate the ImageOrientationPatient and ImagePositionPatient tags from the NIfTI affine. Did you find any tools that do this already, or did you have to code this up yourself?

Cheers,
Aaron

**Comment by tomaroberts** [comment]
Hi @aaroncapon 

Been a while since I looked at this! I think I ended up doing it myself.

Here's a little Gist which might help: https://gist.github.com/tomaroberts/8deebaa0ae204d7ae32fecd1e6efdb51

See if it makes sense.

Cheers
Tom
