### ISSUE TITLE
`dim[5:]` and `pixdim[5:]` in nifti header set to 1 after using slicer.

### ISSUE THREAD

**Issue by mateuszpawlik** [nipy/nibabel#1034]
I tried to use `img.slicer` to discard some dummy scans from the front of an fmri image (bold signal). I observed that the original image has `0`s in `dim[5:]` and `pixdim[5:]` and after the slicer the values in these arrays are set to `1`s.
Before we used AFNI nifti_tool for the same purpose and it modified the values only in `dim[5:]`.

After googling I understood that values `dim[5:]` and `pixdim[5:]` are not relevant if `dim[0]=4`. However, I couldn't find what should be the correct values. So what should they be?

**Comment by effigies** [comment]
0 and 1 are both sensible defaults. 0 to me would indicate unused, 1 that the array has length 1 in that dimension, which are both true. It has no effect on interpretation, but you can always set the fields manually:

```Python
img.header["pixdim"][5:] = 0
img.to_filename(...)
```

**Comment by mateuszpawlik** [comment]
Thanks a lot for such a quick answer. I spent quite some time today to figure it out. So I understand it's a matter of interpretation:
- `0` - unused. I agree.
- `1` - dimension of length `1`. It may be interpreted as there are other dimensions in the data.

**Comment by effigies** [comment]
The standard provides no interpretation for dimensions beyond `dim[0]` or guidance on what they should be, so there is no correct/incorrect setting. They should not be considered to have any impact on the interpretation of the data at all.

The default values put in by any given tool will probably reflect which interpretation the original author thought was more intuitive, but this should not be read into too deeply. This choice will have no effect on any standards-compliant reader.

**Comment by mateuszpawlik** [comment]
I guess that solves my problem, thanks a lot Chris. As a person new to nifti & co, I wanted to make sure that everything is fine.
