### ISSUE TITLE
Rescale 3d Image

### ISSUE THREAD

**Issue by sitandon** [nipy/nibabel#1037]
@effigies : Following your discussion on this issue: https://github.com/nipy/nibabel/issues/670

I am trying to figure what will be the new translation values in case of scaling. Lets say we have new scale and old scale. I was going thru @ellisdg's code and he has used something like this (https://github.com/ellisdg/3DUnetCNN/blob/master/unet3d/utils/affine.py)

def calculate_origin_offset(new_spacing, old_spacing):
return np.divide(np.subtract(new_spacing, old_spacing)/2, old_spacing)

Another question is leveraging other libraries like skimage and torchio. How resize/transform in skimage/ torchio approach is different from scaling affine first and then using resample_img from nilearn

https://stackoverflow.com/questions/64674612/how-to-resize-a-nifti-nii-gz-medical-image-file

**Comment by effigies** [comment]
> I am trying to figure what will be the new translation values in case of scaling. Lets say we have new scale and old scale. I was going thru @ellisdg's code and he has used something like this (https://github.com/ellisdg/3DUnetCNN/blob/master/unet3d/utils/affine.py)
> 
> ```Python
> def calculate_origin_offset(new_spacing, old_spacing):
>     return np.divide(np.subtract(new_spacing, old_spacing)/2, old_spacing)
> ```

I'd start from `nibabel.affines.rescale_affine`:

https://github.com/nipy/nibabel/blob/c162e65a2ec9140c93d66907a8dcefbe41c7456d/nibabel/affines.py#L328-L365

Basically:

```Python
new_affine = rescale_affine(old_affine, old_shape, new_zooms, new_shape)
new_translation = new_affine[:3, 3]
```

You can compare David's results to that, or work through the algebra to prove that it reduces to his calculation.

> Another question is leveraging other libraries like skimage and torchio. How resize/transform in skimage/ torchio approach is different from scaling affine first and then using resample_img from nilearn
> 
> https://stackoverflow.com/questions/64674612/how-to-resize-a-nifti-nii-gz-medical-image-file

Here I think @fepegar might be best placed to answer. If you're using the same interpolation method, I would expect your results to be within a small rounding error using any of these. But it would almost certainly be worth your time to write some benchmarks to prove it to your own satisfaction.

**Comment by fepegar** [comment]
Hi! I'm not familiar with `rescale_affine` nor `nilearn`, but I'm happy to help with specific questions about the behavior of TorchIO.

**Comment by ellisdg** [comment]
Hello @sitandon!

>Another question is leveraging other libraries like skimage and torchio. How resize/transform in skimage/ torchio approach is different from scaling affine first and then using resample_img from nilearn

For the 3DUNetCNN code the affine functions are designed to allow for multiple augmentations to be done prior to resampling. For example, the affine can be translated, inverted, and the spacing can be changed. Then after all the augmentations are applied to the affine, the image can be resampled in a single step. This prevents a loss of information from performing multiple resampling steps. I don't know TorchIO, so it may be that it allows multiple transformations to be applied in a single resampling step as well.

**Comment by fepegar** [comment]
> I don't know TorchIO, so it may be that it allows multiple transformations to be applied in a single resampling step as well.

It doesn't (yet).

TorchIO uses NiBabel and SimpleITK under the hood. An overview of a basic training pipeline with TorchIO can be found in the first tutorial: [TorchIO tutorials](https://github.com/fepegar/torchio/blob/master/notebooks/README.md#general).

**Comment by sitandon** [comment]
> Hello @sitandon!
> 
> > Another question is leveraging other libraries like skimage and torchio. How resize/transform in skimage/ torchio approach is different from scaling affine first and then using resample_img from nilearn
> 
> For the 3DUNetCNN code the affine functions are designed to allow for multiple augmentations to be done prior to resampling. For example, the affine can be translated, inverted, and the spacing can be changed. Then after all the augmentations are applied to the affine, the image can be resampled in a single step. This prevents a loss of information from performing multiple resampling steps. I don't know TorchIO, so it may be that it allows multiple transformations to be applied in a single resampling step as well.

Hi @ellisdg,

Could you please explain the algebra for this function

def calculate_origin_offset(new_spacing, old_spacing):
    return np.divide(np.subtract(new_spacing, old_spacing)/2, old_spacing)

**Comment by ellisdg** [comment]
@sitandon,

I like to think of the affine as the window and orientation through which we are looking at the data. When changing the spacing we want the corners of the window to stay in the same location, we just want a lower resolution sampling of the data within that window.

The code you are talking about is calculating the new origin given a new desired spacing. Let's say we have a 2D image with 1mm^2 pixel sizes and we want 2mm^2 pixel sizes for our new spacing. And let's say that we have an origin of (0, 0). The origin actually describes the center of the origin voxel (or pixel in this case) (see https://nipy.org/nibabel/coordinate_systems.html). So the corner of the image is actually going to be at (-0.5, -0.5) for the original image. We want the new image to have the same extent as the original image, we need to adjust the origin so that it is at (0.5, 0.5). This way the corner of the image remains (-0.5, -0.5).
