### ISSUE TITLE
as_closest_canonical() routine

### ISSUE THREAD

**Issue by ilyanelken** [nipy/nibabel#1045]
Hi,

I am using nibabel.as_closest_canonical() call and I see different behavior on
different platforms for the same input (I get different output dimensions),
is it possible?

Thanks,
Ilya

**Comment by matthew-brett** [comment]
I suppose it's just conceiveable, if a couple of axes are at more or less exactly 45 degrees to a canonical axis - then the SVD step in analyzing the affine could have very slight variations according to the platform implemementation.  What is the affine of the image that has this problem?

**Comment by ilyanelken** [comment]
The affine is:
![affine](https://user-images.githubusercontent.com/3438404/129757986-07000a37-2d3b-4818-a72b-ef3af63d4033.jpg)

**Comment by matthew-brett** [comment]
Could you do

```python
np.savez('aff.npz', affine=brain.affine)
```

and attach that file?

**Comment by ilyanelken** [comment]
I don't have access to the PC where the data is stored, so I just manually
retyped (hopefully wo typos) from JPEG above.
Just remove .zip extension after downloading:
[aff.npz.zip](https://github.com/nipy/nibabel/files/7001460/aff.npz.zip)

**Comment by ilyanelken** [comment]
I will try to acquire the original data and upload here when I will get it.

**Comment by ilyanelken** [comment]
Affine taken from NIFTI:
[aff.npz.zip](https://github.com/nipy/nibabel/files/7002190/aff.npz.zip)

**Comment by matthew-brett** [comment]
Hmm - the affine look entirely unexceptional. 

```
[ins] In [8]: R = aff[:3, :3]

[ins] In [9]: np.linalg.svd(R)
Out[9]: 
(array([[ 0.003335  ,  0.02655223,  0.99964186],
        [ 0.00476386, -0.9996365 ,  0.0265362 ],
        [ 0.99998309,  0.00467366, -0.00346028]]),
 array([0.99999998, 0.99999997, 0.99999945]),
 array([[-3.97145028e-03,  9.99992113e-01, -3.81335971e-05],
        [ 9.99992071e-01,  3.97146121e-03,  2.90980176e-04],
        [-2.91129328e-04,  3.69776815e-05,  9.99999957e-01]]))
```

What are you seeing in the difference between the images, on different platforms?  Can you get the affines from the two output images?

**Comment by ilyanelken** [comment]
Yep, looks like ordinary axes.
It will take me a while since I don't have direct access to this PC, I will update soon.

**Comment by effigies** [comment]
@ilyanelken Any updates here? Is there anything to do?
