### ISSUE TITLE
How to undo as_closest_canonical()

### ISSUE THREAD

**Issue by wasserth** [nipy/nibabel#1063]
Hello,
before I process an image I do nibabel.as_closest_canonical(). After processing I want to move it back to its original orientation. How can I do this? as_closest_canonical() is only returning the reoriented image, but no information about the transformations it did.

**Comment by effigies** [comment]
I would look at the code for as_closest_canonical and see the structures used internally. It uses the orientations module and the as_reoriented method.

**Comment by wasserth** [comment]
Thank you for your answer. So if I understand correctly this should be the solution:
```
import nibabel as nib
from nibabel.orientations import io_orientation

img = nib.load("my_image.nii.gz")
orientation = io_orientation(img.affine)

# Transform to canonical
img_canonical = nib.as_closest_canonical(img)

# Transform back to original space
img_original = img_canonical.as_reoriented(orientation)
```

**Comment by effigies** [comment]
That will work for, say, LPS, which just flips the first two directions but doesn't rotate axes. But for something like AIR, applying it twice would get to SRP.

To invert use the `ornt_transform` and explicitly specify your to/from orientations:

```Python
import nibabel as nib
from nibabel.orientations import io_orientation, axcodes2ornt
import numpy as np

img_ornt = io_orientation(img.affine)
ras_ornt = axcodes2ornt("RAS")

to_canonical = img_ornt  # Same as ornt_transform(img_ornt, ras_ornt)
from_canonical = ornt_transform(ras_ornt, img_ornt)

# Same as as_closest_canonical
img_canonical = img.as_reoriented(to_canonical)

img_original = img_canonical.as_reoriented(from_canonical)
```

This API is not terribly intuitive... The orientation structure is clearly a [finite group](https://en.wikipedia.org/wiki/Finite_group), so it would be nice to at least have a more straightforward inversion function.

**Comment by wasserth** [comment]
Great. Thank you!
