### ISSUE TITLE
How to get the corresponding brain area name of each label_id？

### ISSUE THREAD

**Issue by tanjia123456** [nipy/nibabel#1064]
https://github.com/nipy/nibabel/blob/62aea04248e70d7c4529954ca41685d7f75a0b1e/nibabel/freesurfer/io.py

Hello, thank you for your contribution. In the above link, the return value of the read_annot function has the label index corresponding to each node, but the name obtained does not have the brain area name corresponding to each node. How to get the corresponding brain area name of each label_id？

**Comment by tanjia123456** [comment]
such as 
1 bankssts
2 caudalanteriorcingulate
3 caudalmiddlefrontal

**Comment by tanjia123456** [comment]
![image](https://user-images.githubusercontent.com/66013865/141992328-0b95da1a-d885-420a-ae4b-62859ff381d9.png)

**Comment by effigies** [comment]
If I'm understanding you correctly, then `names[labels]` should get you a vector with the name at each vertex.

In general, I imagine you want to get a given vertex index and retrieve its name, in which case you can use `names[labels[idx]]`.

**Comment by tanjia123456** [comment]
> If I'm understanding you correctly, then `names[labels]` should get you a vector with the name at each vertex.
> 
> In general, I imagine you want to get a given vertex index and retrieve its name, in which case you can use `names[labels[idx]]`.

OK, thanks for your response.
