### ISSUE TITLE
Add MZ3 surface file format

### ISSUE THREAD

**Issue by effigies** [nipy/nibabel#1065]
Via @neurolabusc:

> you may want to consider handling the [mz3](https://github.com/neurolabusc/surf-ice/tree/master/mz3) format, the page includes Python, Blender, JavaScript code as well as a full specification and examples datasets. It attempts to live at the Pareto frontier of file size and speed. It is both faster and smaller than GIfTI. The layout design maps directly onto modern GPU architectures (and hence WebGL, Metal and Vulkan APIs). I developed this primarily for the sample files distributed with Surfice, to reduce download times, disk usage and the time to run the demos / regression testing. It is intentionally simple, and does not have the flexibility of other formats. It does not attempt to do everything, but it can fill a niche.

**Comment by neurolabusc** [comment]
I forgot to mention Matlab code is provided. @gllmflndn contributed to the code and specification, and thanks to him it is supported by [spm12](https://github.com/spm/spm12/search?q=mz3) and [PALM](https://github.com/andersonwinkler/PALM).

**Comment by effigies** [comment]
Thanks, Chris. That sounds reasonable to me.
