### ISSUE TITLE
ImageIO Plugin

### ISSUE THREAD

**Issue by FirefoxMetzger** [nipy/nibabel#1067]
Hej, [ImageIO](https://github.com/imageio/imageio) Dev here! 👋 

I learned about nibabel today (by chance) and it looks like a really cool library! Especially so, because it covers quite a few specialized image formats and I don't think that we (ImageIO) actually support all of them. This brings me to my main question:

1. Do you use ImageIO under the hood somewhere? (I searched briefly, but didn't find anything)

I'm asking because I am currently checking if it is possible to write a plugin for nibabel and I would like to avoid a circular dependency if any.

---

**Sidenote 1**: I'm scouring the docs for info on the nibabel API and I've noticed that the sidebar menu is broken, i.e., none of the links there work,

**Sidenote 2**: For those that haven't heard of ImageIO before, the idea is to have a library that allows you to `imread("my_image")` and it _just works_ no matter the file format or source (filesystem, remote HTTP/FTP, webcam, ...).

**Comment by matthew-brett** [comment]
Thanks for pointing out the docs problem - I put up an issue at #1068 

I do know of ImageIO via scikit-image - but no - we don't import it.  We have tried to keep our dependencies to an absolute minimum.

**Comment by FirefoxMetzger** [comment]
Thanks for the quick reply @matthew-brett !

> we don't import it. We have tried to keep our dependencies to an absolute minimum.

Thanks, that solves it :) I will close the issue as resolved.
