### ISSUE TITLE
How to load a nifti from a file without extension like ".nii.gz" (but which actually is)

### ISSUE THREAD

**Issue by PaulJehanno** [nipy/nibabel#1070]
Hi there!
I'm having trouble loading a nifti (more precisely a Nifti1Image) from a file path that does not have an extension ".nii.gz".
My usecase is: in a database, for storage purpose, I replaced all *.nii.gz files with a "git-lfs like" pointer (a text file having containing a hash, for example `a3f0ba7b052af6f1caa3735c543e3e8e8fd17e94034033e96e167541ca9b3021`). Then I move the original file content to a new file in named after its hash `a3f0ba7b052af6f1caa3735c543e3e8e8fd17e94034033e96e167541ca9b3021`, inside a dedicated HDD.

Then to load a series, I just have to read the hash of the real nifti inside a pointer file, and eventually call 
`nibabel.Nifti1Image.load('a3f0ba7b052af6f1caa3735c543e3e8e8fd17e94034033e96e167541ca9b3021')` but it does not work, neither does a `nibabel.Nifti1Image.from_file_map`

It would be great to have simple means to do this like `.load(..., force=True)` or
```
import nibabel
with open('a3f0ba7b052af6f1caa3735c543e3e8e8fd17e94034033e96e167541ca9b3021', 'wb') as byte_content_nifti:
    nifti_object = nibabel.Nifti1Image.load_from_byte(byte_content_nifti)
```

Anyone had a similar issue? Would someone have a quick fix? Could there be a plan to add such a to the API?
Thanks in advance

**Comment by effigies** [comment]
Have you tried `Nifti1Image.from_bytes()`?

**Comment by PaulJehanno** [comment]
Thanks effigies for the tip, yes I tried this way :
```
with open(PATH_FILE_WITHOUT_EXTENSION, 'rb') as file_obj:
    byte_content = file_obj.read()
nib.Nifti1Image.from_bytes(byte_content)
```
and I get warnings of 
```
sizeof_hdr should be 348; set sizeof_hdr to 348
data code 1637 not recognized; not attempting fix
```
plus a HeaderDataError, it seems I should maybe pass a `.nii` byte content, instead of .nii.gz. let me try..

**Comment by effigies** [comment]
Ah, right. You will need to decompress the byte string first.

**Comment by PaulJehanno** [comment]
right, never mind, solution is : 
```
import nibabel as nib
import zlib
with open(hash_name, 'rb') as file_obj:
    nii_gz_byte_content = file_obj.read()
# from https://stackoverflow.com/questions/6123223/howto-uncompress-gzipped-data-in-a-byte-array
nii_byte_content = zlib.decompress(nii_gz_byte_content, 15+32)
nib.Nifti1Image.from_bytes(nii_byte_content)
```

Sorry! I have the exact same problem for SimpleITK, though, but guess i'll close the issue here and dig myself ;) 
Thanks! 👋
