### ISSUE TITLE
Gzipped gifti files I/O

### ISSUE THREAD

**Issue by alexisthual** [nipy/nibabel#1071]
Loading `.gii.gz` files will crash with `nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/path/to/file"`.

Here is a snippet to reproduce:

```python
import nibabel as nib
from nilearn import datasets

fs5 = datasets.fetch_surf_fsaverage()
nib.load(fs5.pial_left)
```

**Comment by matthew-brett** [comment]
For someone passing by, the key line causing the error boils down to:

```python
nib.load('/some/path/pial_left.gii.gz')
```

This is because we don't recognize `.gii.gz` files as Gifti files.   See PR #1072
