### ISSUE TITLE
How to crop NIFTI file based on mask data and save it

### ISSUE THREAD

**Issue by SoyaOda** [nipy/nibabel#1074]
Hello. Can anyone help me?

I have two types of nii.gz
1. original MRI
2. mask

I want to extract the area of original MRI where the mask covers and save it as nifti file.
Anyone have good ideas?

**Comment by effigies** [comment]
Apologies for not getting to this promptly. If this is still an question, please open a new issue with details of the images you're looking at and what you're trying to do. Clearly describe what data you have, what you would like to end up with, and what you've tried so far.
