### ISSUE TITLE
Orientation and flip on a Nifti file

### ISSUE THREAD

**Issue by manoaman** [nipy/nibabel#1086]
Hi,

I am trying to move axes and flip the Nifti file but I have doubts if the file is actually changed as expected.  Could I be missing something here?

Thank you for your help,
-m

```
import nibabel as nib
import numpy as np

nii = nib.load('sample.nii.gz')
ornt = np.array([[2, -1],
                [0, 1],
                [1, 1]])                   
img_orient = img.as_reoriented(ornt)
nib.save(img_orient, 'sample2.nii.gz')
```

**Comment by effigies** [comment]
You can check the new axcodes with `nib.aff2axcodes(img_orient.affine)`.

**Comment by manoaman** [comment]
Could it be possible that the header(?) needs to be updated?  I'm not sure if I'm saving the file as it should be after the transformation.  Attached is the ITK-SNAP profile.

(Before)
<img width="844" alt="Screen Shot 2022-02-17 at 10 15 24 AM" src="https://user-images.githubusercontent.com/47464840/154544980-cf95cf65-48f4-49eb-8a91-3051bb6c919b.png">

(After)
<img width="932" alt="Screen Shot 2022-02-17 at 10 15 35 AM" src="https://user-images.githubusercontent.com/47464840/154544964-8a78a9a7-dba9-43ac-9008-08fc2017de2c.png">

**Comment by matthew-brett** [comment]
I don't know ITK-Snap, but is it possible it is using the header affine information to display the image?  In which case, you won't see any difference. The voxel data has changed, and has been suituably flipped, but the affine records these flips in order to keep the voxels in the same world-coordinate space.    If you want to change the world-coordinate space, and not the voxel data, you need to change the affine, rather than re-orienting, as you are doing here.

**Comment by manoaman** [comment]
@matthew-brett thank you for the insights.  How do I change the world-coordinate space?

**Comment by matthew-brett** [comment]
You can modify the affine array.  Just for example, if you wanted to flip the world-space of the image left right, without any changes to the voxel data, you could do:

```
flipped_affine = np.diag([-1, 1, 1, 1]) @ img.affine
flipped = nib.Nifti1Image(img.dataobj, flipped_affine, img.header)
```

**Comment by manoaman** [comment]
any thoughts? @matthew-brett

**Comment by matthew-brett** [comment]
Sorry - I think I don't understand what you want to do.  The axcodes are exactly the voxel block orientations, relative to the affine - so you did accomplish that already.

Perhaps you mean that you want affine to indicate that the current apparent Right is in fact Anterior, and so on?

**Comment by manoaman** [comment]
Hi @matthew-brett , sorry about the lack of explanation on my end.  I'm new to this transformation.

> Perhaps you mean that you want affine to indicate that the current apparent Right is in fact Anterior, and so on?
Yes, I'm trying to swap axes here.  I get `-1` flips but how do I swap axes to accomplish `Right` is `Anterior`, `Anterior` is `Superior`, and `Superior` is `Left`? I want Coronal, Sagittal, Horizontal planes mapped to different axes.

Would that make sense?

**Comment by matthew-brett** [comment]
It could make sense - if you find that, when you display the image in a viewer that uses the affine, R and A and S are all mixed up, and you want to fix that.

**Comment by chrisrapson** [comment]
I wanted to swap the axes just like @manoaman. This thread sent me in the right direction. For me, the solution was:

```
data = nib.load('sample.nii.gz')
data_affine = np.array([
            [0, 0, 1, 0],
            [0, 1, 0, 0],
            [1, 0, 0, 0],
            [0, 0, 0, 1]
        ]) @ data.affine
data = nib.Nifti1Image(data.dataobj, data_affine, data.header)
nib.save(data, 'sample_axes_swapped.nii.gz')
```
