### ISSUE TITLE
Slices from a Nifti file to generate thumbnail galleries

### ISSUE THREAD

**Issue by manoaman** [nipy/nibabel#1088]
Hi,

I'm trying to generate thumbnail galleries from the Nifti image.  The resulting image looks pixelated and they do not appear as the original image I see in the GUI view.  Do you have any working example with niabel? Could anyone suggest what I am doing wrong here?

Thanks,
m

```
    import nibabel as nib
    import numpy as np
    from PIL import Image

    nii = nib.load('test.nii.gz')
    img_data = nii.get_data()
    img_data_arr = np.asarray(img_data)

    x,y,z = img_data_arr.shape
    for i in range(z):
        im = Image.fromarray(img_data_arr[:,:,i], 'L')
        im.save(os.path.join(target_dir,f'{i}.jpeg'))
```

**Comment by effigies** [comment]
You probably don't want to use JPEG. If you're looking for some useful plotting functions, I'd check out nilearn: https://nilearn.github.io

**Comment by manoaman** [comment]
@effigies What about TIFF format?  Does niabel support generating tiff stacks from a Nifti file?

**Comment by effigies** [comment]
Not directly, but what you showed above with PIL should work with TIFF. Nibabel exposes the data as a numpy array, so anything that works with those should integrate easily

**Comment by effigies** [comment]
Sorry, I'm not sure I understand. You have a 1D NIfTI image and want to save it as a TIFF? What requirements does PIL have for input arrays? Without knowing what your source data are or the requirements for your target usage, I'm afraid I won't have much helpful to say.

**Comment by manoaman** [comment]
Sorry, I don't think I'm explaining it well.  The Nifti image I'm using is float64 and (228, 160, 264) in shape.  The ultimate goal for me is to generate a stack of TIFF images from a Nifti file which is a 3D image.  I'm not too worried about the quality of the generated image sequences because they are used for thumbnail images.  In Fiji (ImageJ), there is a feature which saves a Nifti file or a 3D image volume as in "Image Sequence".  I'd rather want to do this in a CLI script.

**Comment by effigies** [comment]
Okay, so the way I'd think about this is to make a function that converts your data from one type to another. You have a Nifti1Image and a slice index, you can get a PIL Image:

```Python
from PIL import Image

def image_from_slice(img, idx):
    return Image.fromarray(img.dataobj[:, :, i])
```

Now you can do something like:

```Python
for idx in range(img.shape[2]):
    slice = image_from_slice(img, idx)
    slice.save("slice{idx}.tif")
```

Putting it together:

```Python
import nibabel as nib
from PIL import Image

def image_from_slice(img, idx):
    return Image.fromarray(img.dataobj[:, :, i])

img = nib.load('test.nii.gz')

for idx in range(img.shape[2]):
    slice = image_from_slice(img, idx)
    slice.save("slice{idx}.tif")
```

**Comment by manoaman** [comment]
Thank you! This is what I wanted.
