### ISSUE TITLE
How to fix patient orientation

### ISSUE THREAD

**Issue by kiwibruyant** [nipy/nibabel#1099]
Hello,

I'm currently working with nibabel and reading some nifti ct-scans of different patients. It works well, however some patient seems to have a different orientation than the other (they are flipped horizontally). Here's some examples :

![image](https://user-images.githubusercontent.com/68054821/162994619-bb88386a-0c79-4070-a1a3-4a2481ef3b73.png)

Is the orientation data provided by the nifti header ? Because I can't find it : here's what the header looks like : 

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 512 512 537   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [-1.00000e+00  9.68750e-01  9.68750e-01  7.99988e-01  0.00000e+00
  1.00000e+00  1.00000e+00  4.47800e+04]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 255
glmin           : 0
descrip         : b'None'
aux_file        : b'None'
qform_code      : scanner
sform_code      : scanner
quatern_b       : 0.0
quatern_c       : 1.0
quatern_d       : 0.0
qoffset_x       : 240.0
qoffset_y       : -344.03125
qoffset_z       : -621.8
srow_x          : [ -0.96875   0.        0.      240.     ]
srow_y          : [   0.         0.96875    0.      -344.03125]
srow_z          : [   0.          0.          0.799988 -621.8     ]
intent_name     : b''
magic           : b'n+1'

**Comment by matthew-brett** [comment]
The orientation comes from the combination of the arrangement of the voxel data, and the qform and sform information in the header.  What you see, depends on what visualization software you are using - whether it uses the header qform or sform information.

For example, if you use Matplotlib to display slices from the image data, that does not use the header orientation information, the only thing that matters is the arrangement of the voxel data.

Does https://nipy.org/nibabel/coordinate_systems.html help?

**Comment by ArthurRyan0803** [comment]
```python
def get_dcm(image) -> np.ndarray:
    """
    Get direction cosine matrix from nifti image object
    """
    affine_matrix = image.affine.astype(np.float64)
    rot_zoom_matrix = affine_matrix[0:-1, 0:-1]  # Get rotation and zoom matrix from affine matrix

    voxel_spacing = image.header.get_zooms()  # Get voxel spacing
    voxel_spacing = voxel_spacing[0:rot_zoom_matrix.shape[0]]
    voxel_spacing_inverse = np.diag(1. / np.array(voxel_spacing))   
    rot_zoom_matrix = rot_zoom_matrix.dot(voxel_spacing_inverse)    # Restore to pixel coordinate
    dcm = rot_zoom_matrix.flatten() # Get direction cosine matrix
    return dcm

nii_obj = nib.load("your image file")
matrix = nii_obj.get_fdata()

dcm = get_dcm(nii_obj)
if len(dcm) == 9:
    # There are only two possible values in the dcm: 1 & -1. 
    # If the direction cosine of an axis is -1 ( cos(180) = -1 ), we will flip this axis 
    axis = np.where(dcm[[0,4,8]]<0)[0]  
    matrix = np.flip(matrix, axis=1)

matrix = matrix.transpose(1, 0, 2)
slice = matrix[:, :, 24]
slice = np.interp(slice, [-1250, 250], [0, 1])

plt.imshow(slice, cmap=plt.gray())
plt.show()
```

Another similar version of SimpleITK: https://github.com/JoHof/lungmask/blob/master/lungmask/mask.py

This code is inspired from the work of : 

read_sitk_vector_image method in https://github.com/gift-surg/PySiTK/blob/master/pysitk/simple_itk_helper.py

**Comment by matthew-brett** [comment]
Is there an error in the code after:

```python
    axis = np.where(dcm[[0,4,8]]<0)[0] 
```

I don't think you are using the `axis` variable.
