### ISSUE TITLE
module 'nibabel.processing' has no attribute 'conform'

### ISSUE THREAD

**Issue by akansh12** [nipy/nibabel#1100]
module 'nibabel.processing' has no attribute 'conform' 
I am getting this error only when executing code in Google Colab. In my local system, I am not getting this error. 

![image](https://user-images.githubusercontent.com/39628860/164200437-1998219e-ef80-405e-9e2a-9eede4f80f3e.png)

**Comment by effigies** [comment]
You need to upgrade to a newer version of nibabel. Try adding the `--upgrade` flag to your pip command.

**Comment by akansh12** [comment]
Thanks, @effigies, it works perfectly!

**Comment by effigies** [comment]
Glad to hear it!
