### ISSUE TITLE
Return native endian data as byteorder "="

### ISSUE THREAD

**Issue by matthew-brett** [nipy/nibabel#111]
Numpy linalg <= 1.6.1 has a problem with explicit endian codes for native endian.  Specifically, if the endian code is '<' for an array, and the system is little endian, then numpy linalg will blow up doing - say - an SVD.  The fix is to make the returned array `=` endian (implicit native endian).  

See : 

https://github.com/nipy/nipy/issues/130
https://github.com/numpy/numpy/pull/235

**Comment by effigies** [comment]
I think we can close this, as the minimum numpy is now 1.8.
