### ISSUE TITLE
Exclude tests and test data from pypi package

### ISSUE THREAD

**Issue by Korijn** [nipy/nibabel#1122]
Currently the wheel on pypi includes the test suite and all test data. Is this really needed? It makes the package bigger than it could be.

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/1882046/176653200-eff00dff-9558-4cd2-a3cd-7c75d4b90996.png)

**Comment by effigies** [comment]
In general our philosophy has been that the tests should be runnable from installed versions, not just the source repository. But we should review things to ensure that these really aren't too big.

This discussion ties into #1087, so let's follow up there.
