### ISSUE TITLE
HeaderError Nibabel

### ISSUE THREAD

**Issue by giovannividetta** [nipy/nibabel#1123]
Hi!
I have a technical problem with Trackvis file upload with Nibabel.

A brief premise. Last January 2022 I e-mailed Dr. Ruopeng in order to solve launch problems of Trackvis software on my Mac PC. He shared with me a new build of the software released in December 2021: Trackvis version 0.6.2.1 (Build 2021.12.08). This build was compatible with the latest MacOS system updates (Monterey from 12.1 to 12.4 version).

Recently, I performed some segmentations with the new Trackvis build saving them as .trk files. However, using Nibabel, I tried to upload one of them in order to extract the number of streamlines, but I failed. The following error message was reported: "**HeaderError: NiBabel only supports versions 1 and 2 of the Trackvis file format**". I repeated the same operation with another .trk file produced with the previous Trackvis build and I didn't have any problem. Finally, I checked on GitHub the latest updates of Nibabel library (https://github.com/nipy/nibabel/blob/master/nibabel/streamlines/trk.py) and I noticed that they are made in August 2021.

Therefore, is it possible that the Trackvis format of .trk files produced with the new build is not compatible with the Nibabel library tool/s?

Thank you for your support and availability.
Best wishes!

<img width="1280" alt="Schermata 2022-07-01 alle 11 53 01" src="https://user-images.githubusercontent.com/54890054/177297544-d66a3e3d-6ca4-48c7-9bc5-8da1322a2bb1.png">
<img width="1280" alt="Schermata 2022-07-01 alle 11 53 12" src="https://user-images.githubusercontent.com/54890054/177297551-816f13aa-1d79-421d-a74b-8c0635cae1f8.png">
<img width="1280" alt="Schermata 2022-07-05 alle 11 35 37" src="https://user-images.githubusercontent.com/54890054/177298889-bfdff41b-ac0e-4900-b4c5-b31b7858e63f.png">

**Comment by effigies** [comment]
Are you able to share the file? Do you know the version of the format used?

**Comment by giovannividetta** [comment]
Good afternoon, Chris.
Which file are you referring to? I cannot share .trk file due to privacy
policy of hospital where I work. I apologies for this inconvenience. Is
there another way to help you?
Thank you so much,
Giovanni

Il giorno mar 5 lug 2022 alle 14:02 Chris Markiewicz <
***@***.***> ha scritto:

**Comment by effigies** [comment]
Without a file that it fails on, it's going to be difficult. Perhaps you could save one with fake data that fails to load, or find an example from the trackvis site?

**Comment by giovannividetta** [comment]
Here it is! Attached file is a segmentation performed with the new build of
Trackvis and save as.trk. I checked if I was able to load with Nibabel and
the same error message popped up.

Let me know if you have problems with downloading.
 test.trk
<https://drive.google.com/file/d/1zxV71FEhgpRA8g88WWxTJfSChU8QEEyH/view?usp=drive_web>

**Comment by effigies** [comment]
So it looks like this file is claiming to be format version 3.

```Python
In [1]: import nibabel as nb

In [2]: %pdb
Automatic pdb calling has been turned ON

In [3]: nb.streamlines.load('test.trk')
---------------------------------------------------------------------------
HeaderError                               Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 nb.streamlines.load('test.trk')

File ~/Projects/nipy/nibabel/nibabel/streamlines/__init__.py:95, in load(fileobj, lazy_load)
     92 if tractogram_file is None:
     93     raise ValueError(f"Unknown format for 'fileobj': {fileobj}")
---> 95 return tractogram_file.load(fileobj, lazy_load=lazy_load)

File ~/Projects/nipy/nibabel/nibabel/streamlines/trk.py:321, in TrkFile.load(cls, fileobj, lazy_load)
    294 @classmethod
    295 def load(cls, fileobj, lazy_load=False):
    296     """ Loads streamlines from a filename or file-like object.
    297 
    298     Parameters
   (...)
    319     voxel.
    320     """
--> 321     hdr = cls._read_header(fileobj)
    323     # Find scalars and properties name
    324     data_per_point_slice = {}

File ~/Projects/nipy/nibabel/nibabel/streamlines/trk.py:599, in TrkFile._read_header(fileobj)
    597     pass  # Nothing more to do.
    598 else:
--> 599     raise HeaderError('NiBabel only supports versions 1 and 2 of '
    600                       'the Trackvis file format')
    602 # Convert the first record of `header_rec` into a dictionary
    603 header = dict(zip(header_rec.dtype.names, header_rec[0]))

HeaderError: NiBabel only supports versions 1 and 2 of the Trackvis file format
> /home/chris/Projects/nipy/nibabel/nibabel/streamlines/trk.py(599)_read_header()
    597                 pass  # Nothing more to do.
    598             else:
--> 599                 raise HeaderError('NiBabel only supports versions 1 and 2 of '
    600                                   'the Trackvis file format')
    601 

ipdb> header_rec['version']
array([3], dtype=int32)
```

There doesn't seem to be any documentation on this that I can find. Here are docs for v2: http://trackvis.org/docs/?subsect=fileformat

For us to support this, it would be best if the Trackvis authors could document the new format.

**Comment by effigies** [comment]
Yes, that answer does make sense, and we can go ahead and do what he says. It would look like this:

```Diff
diff --git a/nibabel/streamlines/trk.py b/nibabel/streamlines/trk.py
index 6f9987e4..ee809fa4 100644
--- a/nibabel/streamlines/trk.py
+++ b/nibabel/streamlines/trk.py
@@ -593,10 +593,10 @@ class TrkFile(TractogramFile):
             if header_rec['version'] == 1:
                 # There is no 4x4 matrix for voxel to RAS transformation.
                 header_rec[Field.VOXEL_TO_RASMM] = np.zeros((4, 4))
-            elif header_rec['version'] == 2:
+            elif header_rec['version'] in (2, 3):
                 pass  # Nothing more to do.
             else:
-                raise HeaderError('NiBabel only supports versions 1 and 2 of '
+                raise HeaderError('NiBabel only supports versions 1, 2 and 3 of '
                                   'the Trackvis file format')
 
             # Convert the first record of `header_rec` into a dictionary
```

That said, I don't understand having a different version number if it has no impact on parsing the file. Presumably there is something different worth capturing? I suppose we could warn `"Parsing a TRK v3 file as v2. Some features may not be handled correctly."` until there is a spec we can address.

**Comment by giovannividetta** [comment]
Dear Chris.
About script change on Nibabel library, is it necessary that I change it? I
do not know I I have access and I can apply the modification you suggested.
Thank you,
Giovanni

**Comment by effigies** [comment]
You can install from the repository like so:

```Shell
git clone https://github.com/nipy/nibabel.git
cd nibabel
pip install -e .
```

Then any changes you make in the source tree will be available in your Python environment. If you would like to submit a patch to us, see https://nipy.org/nibabel/devel/devguide.html.

**Comment by giovannividetta** [comment]
I really don’t know. I am not an engineer nor informatics, I am a cognitive
neuroscientist who uses this tools for structural connectivity analysis
(sorry!). I am sharing with you what Dr. Ruopeng said to me. He also added
that “ *Version 3 trk file should be compatible to version 2”* . So, I
suppose that the information contained in header and informatics structure
of the file should be the same between the two versions.

Il giorno mer 6 lug 2022 alle 20:55 Chris Markiewicz <
***@***.***> ha scritto:

**Comment by giovannividetta** [comment]
I could try to email Dr. Ruopeng again in order to ask him this. By the
way, the website of Trackvis has not been updated for long time. Indeed,
the downloadable version of software is the old one, 0.6.1, that now
crashes on Mac PC without allowing users to launch it.

Il giorno mar 5 lug 2022 alle 21:23 Chris Markiewicz <
***@***.***> ha scritto:
