### ISSUE TITLE
Call each label from NIFTI file for Dice Score Computation

### ISSUE THREAD

**Issue by monjoybme** [nipy/nibabel#1130]
Hi,
I have two NIFTI files, one for automated segmentation and one for manual segmentation. I'm loading them with ```nib.load```. Each NFTI file contains multiple labels (six labels each). I want to call each label to calculate the Dice score for all the labels. I can't remember how to call each label. Any assistance would be greatly appreciated. Here is my code snippet

```
mask_gt = nib.load('GT-01S.nii').get_data() # Load Ground Truth
mask_pred = nib.load('Auto_01S.nii').get_data() # Load Automated Segmentation File
```
Thanks

**Comment by effigies** [comment]
Hi, is this still a question? I'm not sure what you mean by "call each label".

**Comment by monjoybme** [comment]
@effigies Hi, Thanks for your response! To solve this problem, I wrote my own code. I wanted to calculate the dice score for each of the six labels/segments at once. I tried using your package, but I couldn't find a suitable function for this purpose. Please share any hints you have. It will be beneficial to others.

**Comment by effigies** [comment]
It's not clear to me what kind of data you have, but here's a rough sketch of how you might approach this:

First, create a function that operates on numpy arrays. Following [this formula](https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient#Formula), you can write a function that calculates the overlap coefficient of binary masks:

```Python
def dice(mask1, mask2):
    return np.sum(mask1 & mask2) / (np.sum(mask1) + np.sum(mask2))
```

Now, how to get binary masks? It depends what your data look like. If your images are already binary masks (arrays of 0 or 1 values), you can simply pass them:

```Python
dice(np.bool_(img1.dataobj), np.bool_(img2.dataobj))
```

If you have images with label values from 1-6 (0 elsewhere), then you could calculate the overlap of, say the threes:

```Python
dice(np.array(img1.dataobj) == 3, np.array(img2.dataobj) == 3)
```

Hope this is somewhat helpful...
