### ISSUE TITLE
How to deserialize the io stream of a nifti file?

### ISSUE THREAD

**Issue by Fivethousand5k** [nipy/nibabel#1135]
Hi! I have no idea how to deserialize the binary io stream of a nifti file with the nibabel, could you please give me an example?

**Comment by effigies** [comment]
Hi, could you clarify what you're trying to do? As in, what do you have (filename, open file object, byte string) that you're trying to convert into an image? And do you know whether it's a NIfTI-1 image or NIfTI-2?

Have you looked at our [documentation](https://nipy.org/nibabel/gettingstarted.html)?
