### ISSUE TITLE
Rotating a T1 image

### ISSUE THREAD

**Issue by TamerGezici** [nipy/nibabel#1144]
Hi,

I have a T1 image in NiFTI which I am doing some modifications. Such as adding additional markings to the image. Then I need to convert this T1 image to DICOM

The issue is, as you can see from the picture as well, the image is rotated. 

![image](https://user-images.githubusercontent.com/11014942/194766048-8eb38d20-d464-430b-b70c-cf82be026d7e.png)

I would like to have it like this:

![image](https://user-images.githubusercontent.com/11014942/194766225-5263e3c1-7b9a-49c7-aeec-d30e597a7494.png)

However, I have extensively looked at the documentation and tried rotating it. But it didn't work. The issue is that even if the NiFTI rotation is fine, converting it back to DICOM using (https://www.onlineconverter.com/nifti-to-dicom) may also rotate it. So I would like to know how I can sort this issue.

I am saving my image like this, after doing my modifications to the T1 image by modifying the image array itself.

```
out_img = nib.Nifti1Image(out_array, t1_img.affine)
nib.save(out_img, 'overlay.nii')
```

**Comment by effigies** [comment]
Hi, apologies for the delay. Your image isn't just rotated, but the orientation information appears to be corrupted, as the superior direction is labeled as right. You need to start with an image with a known orientation; while you can get inferior/superior and anterior/posterior visually, you will need some way to verify that you got left and right correct.

Once you have an image with a known orientation, if you can describe what sort of transformation you want to do, we can work through it. If the concern is that you want the image rotated so that it displays correctly in a particular viewer while retaining correct orientation metadata, then we'll need to know what orientation that viewer expects.

**Comment by TamerGezici** [comment]
I believe for it to work properly on the viewer, all I need to do is rotate the image 90 degrees left once. How can I do this?

**Comment by effigies** [comment]
How are you converting to DICOM? You'll need to check whether the orientation information is corrupted or just ignored by RadiantViewer.

You can at least check consistency with nibabel:

```Python
>>> import nibabel as nb
>>> from nibabel.nicom import dicomwrappers as dw
>>> nii = nb.load(nii_fname)
>>> dcm = dw.wrapper_from_file(dcm_fname)
>>> nii_viewer = nii.orthoview()
>>> nii_viewer.show()
>>> dcm_viewer = nb.viewers.OrthoSlicer3D(dcm.get_data(), dcm.affine)
>>> dcm_viewer.show()
```

If the `dcm_viewer` has the same issue as `RadiantViewer`, then your conversion process is damaging orientation information. You may need to find out what orientation the converter is expecting and rotate your NIfTI before converting. The same thing will be true if `RadiantViewer` is just displaying it incorrectly, but then it's also a bug to report to `RadiantViewer`.

Anyway, if you suppose your image needs to be in ARS (I believe DICOM swaps the rows/columns), we can reorient a NIfTI image like so:

```Python
import nibabel as nb
img = nb.load(nii_fname)
init_ornt = nb.orientations.io_orientation(img.affine)
tgt_ornt = nb.orientations.axcodes2ornt("ARS")
xfm = nb.orientations.ornt_transform(init_ornt, tgt_ornt)
reoriented = img.as_reoriented(xfm)
```

**Comment by effigies** [comment]
> I believe for it to work properly on the viewer, all I need to do is rotate the image 90 degrees left for once. How can I do this?

I really would try not think about it in terms of rotating left/right/up/down/etc. It's very easy to get mixed up, and you always want your affine to exactly correspond with your array. As soon as you decouple them, you're in dangerous territory.

I would think of it in terms of "for this purpose, a tool I have needs the data array in a particular orientation", and reorient the image using tooling designed to adjust the data array and affine simultaneously.

**Comment by TamerGezici** [comment]
Dear Chris, thank you for your thorough explanations! I really appreciate your help so far.

I tried applying the orientation you suggested, however at the NIfTI level this did not make any difference, which is probably indicative that the orientations are correct. 

However, when I tried viewing it using orthoview, it threw an error:

`ValueError: data must have at least 3 dimensions`

Which is indicative that somehow I am messing up with the DICOM conversion as you suggested.

I will share the DICOM conversion script which I am using, I found this on the internet.

I will also share the part where I'm modifying this T1 image, because maybe there is something wrong there...

I am sorry if this issue went out of the scope of the library.  I would appreciate any help to point me in the right direction if it's not possible to provide further support on this issue. Thank you.

DICOM conversion script:

https://gist.github.com/TamerGezici/cef2110c00703739b3b33f7d46efa467

Nibabel script to modify T1:

https://gist.github.com/TamerGezici/5f97ce81b37b1dd48516272d467f5baa

**Comment by effigies** [comment]
I am definitely not an expert on DICOM, and cannot comment on the correctness of your conversion script. I would refer you to this [Neurostars thread](https://neurostars.org/t/tools-to-convert-nifti-to-dicom/2634) on conversion, and advise you to consider dedicated tooling for converting.

@moloney or @ZviBaratz might have more suggestions for working with DICOM in Python.

**Comment by ZviBaratz** [comment]
I am also far from an expert, but I can say that DICOM files have highly complicated headers, and whatever worked for some particular use-case might not work properly for yours. I noticed the conversion script you use relies on an arbitrary reference DICOM, this is definitely a risky way to approach this, and may very well be the root of the problem. 

I realize it might be frustrating, but I don't think there is any "safe" way to generate a complete, valid DICOM file from NIfTI. While there are a number of conversion tools and scripts which may be able to come up with something good enough for some, maybe even many, of the cases, I can't think of any way to really cover everything. It seems like your use-case falls outside the scope of what's handled correctly with your workflow. Given that, the only solution I could recommend is trying more workflows, starting with those that seem most robust. 

From a quick search, it seems like [this](https://neurostars.org/t/tools-to-convert-nifti-to-dicom/2634/5) Neurostars thread might be beneficial – @neurolabusc mentions [PixelMed](http://www.pixelmed.com/dicomtoolkit.html), and another user points to a [nifti2dicom](https://github.com/biolab-unige/nifti2dicom) repo (last updated 2016, but might still be useful if you're determined enough). Another resource that might be useful is [this](https://simpleitk.readthedocs.io/en/next/Examples/DicomSeriesFromArray/Documentation.html) example from [SimpleITK](https://simpleitk.readthedocs.io/en/next/index.html)'s documentation site. 
HTH, sorry I can't suggest anything more concrete.

**Comment by TamerGezici** [comment]
Thank you @ZviBaratz @effigies for your answers.

I noticed the system also allows the loading of NIfTI images. 

I loaded the image, however the axes are mis-labeled on the system. (See the image below)
![IMG-9737](https://user-images.githubusercontent.com/11014942/213430838-434f5342-8a95-4a8a-a1fe-718995e66366.jpg)



However, on MRIcroGL and FSLeyes they are correctly labeled.

![image](https://user-images.githubusercontent.com/11014942/213430785-3202871b-6e06-4768-badc-fc94715bae88.png)

Do you have any idea why this can be?

**Comment by neurolabusc** [comment]
You will have to work with the developer of your system so it can support the [NIfTI orientation information](https://brainder.org/2012/09/23/the-nifti-file-format/). It looks like this assumption assumes the orientation of a NIfTI identity matrix, while your image was acquired with the images being sagittal in plane.

**Comment by TamerGezici** [comment]
> You will have to work with the developer of your system so it can support the [NIfTI orientation information](https://brainder.org/2012/09/23/the-nifti-file-format/). It looks like this assumption assumes the orientation of a NIfTI identity matrix, while your image was acquired with the images being sagittal in plane.

Thanks a lot for your answer! It was indeed the case that transforming the affines to an identity matrix fixed it! I found a script on the internet which does this: https://gist.github.com/ofgulban/df2a0a2437a13055b84e09dd4a345c91
