### ISSUE TITLE
Loading/Saving different image formats

### ISSUE THREAD

**Issue by pjsjongsung** [nipy/nibabel#1145]
I recently had problems loading/saving mnc and spm2 analyze files.

While there is a mnc image class, there are no instructions on how to load or save it, and if I try to save it gives me a not implemented error.

Also I tried to load .img and .hdr files, which both gave me Spm2AnalyzeImage instead of a header class, which took me a very long time finding out how to change it back and save it as nifti.

Could we have more intuitive functions or better documentation of how to load and save different file formats? It seems very essential as there are many datasets without the nifti file. I would love to contribute if it helps.

Thank you!

**Comment by effigies** [comment]
Hi @pjsjongsung, apologies for the delay. The basic approach is this:

```Python
import nibabel as nb

def load_anything_to_nifti(fname):
    img = nb.load(fname)
    return nb.Nifti1Image(img.dataobj, img.affine, img.header)
```

> While there is a mnc image class, there are no instructions on how to load or save it, and if I try to save it gives me a not implemented error.

MINC write support is not implemented. If you have experience with MINC files and want to contribute better support, that would be very welcome. I'd be happy to walk you through the data structures (and we can work on improving the documentation at the same time) and answer questions, but I don't really know much about MINC itself.

> Also I tried to load .img and .hdr files, which both gave me Spm2AnalyzeImage instead of a header class,

So [`nibabel.load()`](https://nipy.org/nibabel/reference/nibabel.loadsave.html#load) will load an image, regardless of which file you give it. If it's a spatial image like `Spm2AnalyzeImage`, then it will have the `(data, affine, header)` interface of [`SpatialImage`](https://nipy.org/nibabel/reference/nibabel.spatialimages.html#nibabel.spatialimages.SpatialImage).

From here, if you want to convert to NIfTI, you can try simply to save it as a NIfTI, and [`nibabel.save`](https://nipy.org/nibabel/reference/nibabel.loadsave.html#nibabel.loadsave.save) will attempt to convert it:

```Python
def convert(in_fname, out_fname):
    img = nb.load(in_fname)
    nb.save(img, out_fname)
```

Or you can be explicit, as I was above, and create a Nifti1Image in memory, so you can make any changes you want before saving it.
