### ISSUE TITLE
Add blue to style dependencies

### ISSUE THREAD

**Issue by ZviBaratz** [nipy/nibabel#1164]
Now that [blue](https://blue.readthedocs.io/en/latest/) and [isort](https://pycqa.github.io/isort/) are applied to the existing codebase, it would be good to add them to the style dependencies. 
@effigies @matthew-brett I also think it might be beneficial to include the style dependencies in the dev dependencies, and maybe even add a bit about it to the [developer guidelines](https://nipy.org/nibabel/devel/devguide.html#chap-devguide). WDYT?

**Comment by ZviBaratz** [comment]
Turns out, VSCode doesn't support formatting with blue, which AFAIK essentially requires using a custom extension, which doesn't currently seem to exist. I might be missing something, but if not, this makes auto-formatting somewhat painful. I also looked for a pre-commit hook, in case we consider using those, and couldn't find one. 
Do you have any ideas regarding how to integrate this easily into the development workflow? Should we just recommend running it manually on edited files before committing?

**Comment by matthew-brett** [comment]
Does the same apply to Black?

**Comment by ZviBaratz** [comment]
@matthew-brett No, black is supported both in VSCode and as a pre-commit hook.

**Comment by matthew-brett** [comment]
Would it be reasonable to use Black instead?   It seems to be more widely used?

**Comment by effigies** [comment]
Pre commit should work with any executable. I haven't tried it, but I can.

Also okay with switching to black. For big style commits, please add `[git-blame-ignore-rev]` somewhere in the commit message.

**Comment by effigies** [comment]
Here's a working pre-commit config:

```YAML
repos:
  - repo: https://github.com/grantjenks/blue
    rev: v0.9.1
    hooks:
      - id: blue
        language: python
```

**Comment by ZviBaratz** [comment]
OK, great. Thank you. I'll come up with a PR to integrate pre-commit. 
I tried configuring VSCode to simply run the blue executable too, but unfortunately, it doesn't enable reloading the files after it is executed. This results in a mismatch between the version of disk and the open one, so it's no help. I suppose having the files be reformatted on commits will be enough.
