### ISSUE TITLE
Remove README duplication from info.py

### ISSUE THREAD

**Issue by ZviBaratz** [nipy/nibabel#1166]
The current *README.rst* file is generated as part of the [release checklist](https://nipy.org/nibabel/devel/make_release.html#release-checklist) using the `make refresh-readme` command. This is no longer required for RST files to be displayed correctly on PyPI and may be removed.

**Comment by effigies** [comment]
While there may be a better way to keep things synced, we're not going to get rid of the duplication altogether.
