### ISSUE TITLE
Integrate pre-commit

### ISSUE THREAD

**Issue by ZviBaratz** [nipy/nibabel#1168]
Pre-commit hooks will enable auto-formatting (see #1164) and other beneficial actions/validations.

**Comment by effigies** [comment]
@ZviBaratz Hold up a minute; I'm working on a precommit/isort PR.

**Comment by effigies** [comment]
Created https://github.com/nipy/nibabel/pull/1169. I pushed it to the upstream branch, so if you have additional things you want to add to this, you should be able to push.
