### ISSUE TITLE
Output of `Nifti1Header.get_qform()` returns different affine values than `fslhd`

### ISSUE THREAD

**Issue by joshuacwnewton** [nipy/nibabel#1181]
Hi there! I'm trying to track down discrepancies between the qform outputs of both `nibabel` and [`fslhd`](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Fslutils), a FSL command for printing Nifti header metadata. 

For [this sample image](https://github.com/nipy/nibabel/files/10394137/sample_image.nii.gz), the relevant output of `fslhd` is:

```
qform_name	Scanner Anat
qform_code	1
qto_xyz:1	-0.625000 0.000000 -0.000000 80.000000 
qto_xyz:2	0.000000 0.570521 1.469992 -102.004517 
qto_xyz:3	-0.000000 -0.255207 3.286208 -137.370850 
qto_xyz:4	0.000000 0.000000 0.000000 1.000000 
sform_name	Scanner Anat
sform_code	1
sto_xyz:1	-0.625000 0.000000 -0.000000 80.000000 
sto_xyz:2	0.000000 0.570521 1.469992 -102.004517 
sto_xyz:3	0.000000 -0.255207 3.286208 -137.370850 
sto_xyz:4	0.000000 0.000000 0.000000 1.000000 
```

However, when I load the same image using `nibabel`, then call `header.get_sform()` and `header.get_qform()`, I see the following:

```python
# Avoid exp notation for easier readability
>>> import numpy as np
>>> np.set_printoptions(suppress=True)

# Load image
>>> import nibabel as nib
>>> im_sample = nib.load("sample_image.nii.gz")

# Print sform and qform
>>> sform = im_sample.header.get_sform()
>>> print(sform)
[[  -0.625         0.           -0.           80.        ]
 [   0.            0.57052135    1.46999204 -102.0045166 ]
 [   0.           -0.25520656    3.28620815 -137.37084961]
 [   0.            0.            0.            1.        ]]
>>> qform = im_sample.header.get_qform()
>>> print(qform)
[[  -0.62499996    0.00004513   -0.00121767   80.        ]
 [  -0.00004513    0.57052135    1.46999205 -102.0045166 ]
 [  -0.0002114    -0.25520655    3.28620791 -137.37084961]
 [   0.            0.            0.            1.        ]]
```

The `sform` matches expectations, but the `qform` does not.

* Do you know how these discrepancies might have arisen? (Perhaps, differing methods of [computing the `qform`](https://nipy.org/nibabel/nifti_images.html#the-qform-affine)?)
* And, do you know what the "correct" interpretation of the qform is?

Thanks much!

**Comment by joshuacwnewton** [comment]
Just for reference, it is my understanding that Nibabel [constructs the `qform`](https://nipy.org/nibabel/nifti_images.html#the-qform-affine) on the fly using a combination of values:

> This affine can be calculated from a combination of the voxel sizes (entries 1 through 4 of the `pixdim` field), a sign flip called `qfac` stored in entry 0 of pixdim, and a [quaternion](https://en.wikipedia.org/wiki/Quaternion) that can be reconstructed from fields `quatern_b`, `quatern_c`, `quatern_d`.
>
> See the code for the [`get_qform()` method](https://nipy.org/nibabel/reference/nibabel.nifti1.html#nibabel.nifti1.Nifti1Header.get_qform) for details.

And that the specific source code is as follows: 

https://github.com/nipy/nibabel/blob/323a88ae3e278d1d0f1bcbad223575a323a607ac/nibabel/nifti1.py#L971-L1010

-----

That said, I don't quite know how `fslhd` computes its qform, so it is hard to determine where the discrepancies are coming from.

**Comment by effigies** [comment]
The difference is going to be in computing the quaternion:

https://github.com/nipy/nibabel/blob/323a88ae3e278d1d0f1bcbad223575a323a607ac/nibabel/quaternions.py#L37-L105

We only get three quaternion values, so we need to find the other to ensure that we have a unit quaternion. It turns out that the sum of squares of the quaternions in your file is `0.9999999700948321024`, so we get `sqrt(1 - ss) == 1.72931107e-04`.

If we replace that value with 0 and run through the rest of `get_qform()`, we get the same values as fslhd. So they are deciding that the difference between the sum of squares of the quaternions and 1 is negligible, while we are accepting it because it is positive.

**Comment by effigies** [comment]
It's probably worth noting that if we attempt to set the qform from the sform, the saved quaternion values do not change (apart from a sign flip). So we're hitting the precision limits of NIfTI here.

Currently we're allowing for floating point error in the sum-of-squares to result in the value to exceed 1 by $3\epsilon_{float}$ and calling the difference zero. For symmetry, we could say if we're within $3\epsilon_{float}$ in either direction, the difference is 0. Then we would get the same result, and at least in some cases preserve equality between qform and sform:

```diff
      # Calculate w
      w2 = 1.0 - np.dot(xyz, xyz)
-     if w2 < 0:
-         if w2 < w2_thresh:
-             raise ValueError(f'w2 should be positive, but is {w2:e}')
+     if np.abs(w2) < np.abs(w2_thresh):
          w = 0
+     elif w2 < 0:
+         raise ValueError(f'w2 should be positive, but is {w2:e}')
      else:
          w = np.sqrt(w2)
```

@matthew-brett Any thoughts?

**Comment by joshuacwnewton** [comment]
> Currently we're allowing for floating point error in the sum-of-squares to result in the value to exceed 1 by _3efloat_ and calling the difference zero.

Just to double-check my understanding, here:

* Nifti1Headers have a property called [`quaternion_threshold`](https://github.com/nipy/nibabel/blob/323a88ae3e278d1d0f1bcbad223575a323a607ac/nibabel/nifti1.py#L690-L691), set to `-np.finfo(np.float32).eps * 3`.
* This value is passed to the [`w2_thresh`](https://github.com/nipy/nibabel/blob/323a88ae3e278d1d0f1bcbad223575a323a607ac/nibabel/nifti1.py#L969) parameter of the `fillpostive` function.
* `w2_thresh` is used to zero out any negative `w` values between `w2_thresh < w < 0`.
* You're proposing that positive `w` values between `0 < w < w2_thresh` _also_ be set to 0, for symmetry sake?

And, a consequence of this proposed change is that it would allow me to set a value for `quaternion_threshold` to emulate "FSL-like behavior", if I were able to determine what threshold FSL uses to determine "negligible" values of `w`? (If so, neat! Thank you.)

**Comment by effigies** [comment]
Yes, all correct. It's possible there's a better test than this threshold. And you could imagine wanting to relax the negative threshold a bit without wanting to change the value of qform when w2 is positive.

**Comment by matthew-brett** [comment]
Yes, that seems reasonable to me (the `abs` on the check).
