### ISSUE TITLE
How can I convert .nii to .nrrd file or .nii.gz to .nrrd file

### ISSUE THREAD

**Issue by kmordhwaj** [nipy/nibabel#1187]
I want to know if is there is any way through which we can convert a .nii file to .nrrd file

**Comment by effigies** [comment]
Not with just nibabel. Possibly in combination with pynrrd, but I don't know anything about nrrd, so it's hard to say for certain.

**Comment by effigies** [comment]
xref #356

**Comment by effigies** [comment]
I'm going to close this as answered, but please feel free to update it with a link to any code you write that helps people convert between formats, so others can benefit from your experience. It may also be a small step toward integrating nrrd support in nibabel.
