### ISSUE TITLE
cant usse nibabel imagestats

### ISSUE THREAD

**Issue by Factral** [nipy/nibabel#1207]
I installed the latest version from the repository and it doesn't let you use this module

![image](https://user-images.githubusercontent.com/74687828/221685171-d7fd5fb9-76e8-413e-acfb-c62fb5db68fc.png)

**Comment by effigies** [comment]
It is not imported into `__init__.py`. For now, `import nibabel.imagestats`. Would you mind opening a PR to import `imagestats` into `__init__.py`?
