### ISSUE TITLE
Failing zstd tests

### ISSUE THREAD

**Issue by effigies** [nipy/nibabel#1209]
The latest pyzstd release has changed the error type of:

```Python
>>> import io
>>> import pyzstd
>>> f = pyzstd.ZstdFile(io.BytesIO(b'bad'), mode='rb')
>>> f.read()
```

And tests are now failing.

@vanandrew Do you have time to look into this? I suspect what we want to do is coerce exceptions in `Opener.read()` to match expected exceptions from `IOBase.read()`, and possibly other methods.

**Comment by vanandrew** [comment]
@effigies I'll add it to my to-do list, but I might not get around to it until late next month.

**Comment by effigies** [comment]
No worries. I'll have a look at it in the next week or so if nobody gets there before me.
