### ISSUE TITLE
Typing errors in new version

### ISSUE THREAD

**Issue by fepegar** [nipy/nibabel#1219]
Hi,

I think the new version (5.1.0) introduced some typing issues (seen in [this TorchIO CI run](https://github.com/fepegar/torchio/actions/runs/4603828409/jobs/8134186940)):

```
src/torchio/data/io.py:53: error: "FileBasedImage" has no attribute "get_fdata"
 [attr-defined]
        data = img.get_fdata(dtype=np.float32)
               ^~~~~~~~~~~~~

Found 2 errors in 1 file (checked 95 source files)
src/torchio/data/io.py:[59](https://github.com/fepegar/torchio/actions/runs/4603828409/jobs/8134186940#step:5:60): error: "FileBasedImage" has no attribute "affine" 
[attr-defined]
        affine = img.affine
                 ^~~~~~~~~~
```

**Comment by effigies** [comment]
This is the best that can be done with `load()`.

If you know the image class, you can use, e.g., `Nifti1Image.from_filename()`.

**Comment by effigies** [comment]
Started a discussion over at https://github.com/nipy/nibabel/discussions/1220

It would be nice to add to this as we learn new best practices for working with type-checked code.

**Comment by effigies** [comment]
I don't think there's anything to do here, as we will not be reverting the return type of `nibabel.load()` to `Any`.

**Comment by fepegar** [comment]
Thanks, @effigies!
