### ISSUE TITLE
mypy complains that FileBasedImage (from nibabel.load) has no member "affine"

### ISSUE THREAD

**Issue by ericmburgess** [nipy/nibabel#1225]
Starting with 5.1.0, I'm getting `mypy` complaints when trying to use a loaded image via `nibabel.load`. Since `mypy` believes the image is of type `FileBasedImage`, which is a base class with very little functionality, it complains when I try to do anything with the image, which in my case is of type `Nifti1Image`. 

Am I doing this wrong, or is it type-annotation growing pains?

**Comment by effigies** [comment]
Nope, you're doing it right, but type checking and generic loading functions are in tension.

I've started a discussion where we can work out best practices for writing typed neuroimaging code: https://github.com/nipy/nibabel/discussions/1220
