### ISSUE TITLE
Replace label intensity value of NIFTI file

### ISSUE THREAD

**Issue by monjoybme** [nipy/nibabel#1229]
Hi,
I am trying to replace the intensity values of segmentation labels. For example, 
```
1 will be replaced by 4
2 will be replaced by 3
3 will be replaced by 2
4 will be replaced by 1
```
Following code is partially working, but the image size has been changed. 

```import nibabel as ni
import numpy as np
ori_img = ni.load("ground_truth.nii")
data = ori_img.get_fdata()
data[data == 1] = 14
data[data == 2] = 13
data[data == 3] = 12
data[data == 4] = 11
data[data == 14] = 4
data[data == 13] = 3
data[data == 12] = 2
data[data == 11] = 1
datalr = np.fliplr(data)
data = np.flipud(datalr)
new_image = ni.Nifti1Image(data, affine=np.eye(4))
ni.save(new_image, "converted_dataLRUD.nii")
```
I don't find the cause of shape changes. Any help will be highly appreciated.

**Comment by effigies** [comment]
Oh, I missed the fliplr and flipud. Don't do that. If you need to reorient, you'll want to use the `nibabel.orientations` module.

**Comment by monjoybme** [comment]
> 

@effigies I implemented the change you suggested. Now, the code is partially working. Intensity values are showing as floating number instead of. integers. For example, instead of 2, I received 2.000031. 3Similarly 3.000061 instead 3. How to convert all intensity values into integer?

**Comment by effigies** [comment]
Ah, `get_fdata()` will give you `float64` data. If you know what type you want (say `int16`), you can coerce it on retrieval:

```Python
data = np.int16(ori_img.dataobj)
```

Or you could coerce when creating the new image:

```Python
new_image = ni.Nifti1Image(np.int16(data), ori_img.affine, ori_img.header)
```

**Comment by monjoybme** [comment]
Hi,
Sorry for the delayed reply. I changed the code as you suggested. But I'm still having trouble getting my two NIFTI files to be in the same orientation.

````import nibabel as ni
import numpy as np
ori_img = ni.load("manual.nii")
data = ori_img.get_fdata()
data[data == 1] = 14
data[data == 2] = 13
data[data == 3] = 12
data[data == 4] = 11
data[data == 14] = 4
data[data == 13] = 3
data[data == 12] = 2
data[data == 11] = 1
new_image = ni.Nifti1Image(np.int32(data), ori_img.affine, ori_img.header)
ni.save(new_image, "converted_Auto.nii")
````

But still, I am facing orientation issues. Please see the example images (converted into PNG). 
Example1: ![Example-1](https://github.com/nipy/nibabel/assets/17875749/0db6c178-ca0d-4984-aa0f-28f83c4d7cf6)
Example2: ![Example-2](https://github.com/nipy/nibabel/assets/17875749/e5800224-c6bb-44b3-8965-48babc2f9a4e)

**Comment by monjoybme** [comment]
Solved this issue. Below is my final code. 
```import nibabel as ni
import numpy as np
ori_img = ni.load("manual.nii")
print('original orientation:', ni.orientations.ornt2axcodes(ni.orientations.io_orientation(ori_img.affine)))
orig_ornt = ni.io_orientation(ori_img.affine)
targ_ornt = ni.orientations.axcodes2ornt("LAS")
transform =ni.orientations. ornt_transform(orig_ornt, targ_ornt)
img_orient = ori_img.as_reoriented(transform)
data = img_orient.get_fdata()
data[data == 1] = 14
data[data == 2] = 13
data[data == 3] = 12
data[data == 4] = 11
data[data == 14] = 4
data[data == 13] = 3
data[data == 12] = 2
data[data == 11] = 1
print('Converted orientation:', ni.orientations.ornt2axcodes(ni.orientations.io_orientation(img_orient.affine)))
new_image = ni.Nifti1Image(np.int32(data), ori_img.affine, ori_img.header)
ni.save(new_image, "converted_manual-Ori.nii")
```
