### ISSUE TITLE
Type checking issues

### ISSUE THREAD

**Issue by blakedewey** [nipy/nibabel#1252]
Hi Nibabel community,

Great job on getting some type checking into this package! I wanted to point out two scenarios that I use frequently that have run me into type checking issues based on 5.1.0.

1. `nb.load` shows a return type of `FileBasedImage`. This is all well and good, but unfortunately `FileBasedImage` does not define `get_fdata()`. A common code example that I use (and see around) is:
```python
obj = nb.load(filepath)
data = obj.get_fdata()
```
2. `nb.Nifti1Image` doesn't want to take `None` for the affine. I previously saw this code used frequently:
```python
nb.Nifti1Image(data_array, None, header)
```

Just bringing these to your attention. I'm also flexible to change up my code, if better patterns are recommended.

**Comment by blakedewey** [comment]
Just saw this comment https://github.com/nipy/nibabel/issues/1109#issuecomment-1209417782. I think this change to `SpatialImage` would fix my first issue.

**Comment by effigies** [comment]
Have you seen https://github.com/nipy/nibabel/discussions/1220#discussioncomment-5521024?

**Comment by blakedewey** [comment]
Ah. I had not. Good resource. I was wondering if that would have to be the case. It honestly is smarter code anyways, even if it is more verbose.

**Comment by effigies** [comment]
> 3\. `nb.Nifti1Image` doesn't want to take `None` for the affine. I previously saw this code used frequently:
> 
> 
> ```python
> nb.Nifti1Image(data_array, None, header)
> ```

I'm a bit surprised by this. We haven't typed the `__init__` method at this point, so I would expect it to be `Any`. What type checker are you using, and what error do you see?

**Comment by blakedewey** [comment]
This is in my IDE. I use PyCharm from JetBrains. The error I get is `Expected type 'ndarray', got 'None' instead`. I'm assuming it's doing some kind of inspection of how it's assigned somewhere in lieu of a known type.

**Comment by effigies** [comment]
Ah, I bet it's picking up on the `SpatialImage.__init__`:

https://github.com/nipy/nibabel/blob/184335580fcaedec64e5d5e14e8104cfe552e260/nibabel/spatialimages.py#L481-L488

`affine` should be `np.ndarray | None`.

**Comment by blakedewey** [comment]
Is that as easy of a PR as I think? I can submit fix, if so.

**Comment by effigies** [comment]
I think it should be, yes. Please go ahead.

**Comment by blakedewey** [comment]
#1253 is open. Closing this issue as both concerns have been addressed.
