### ISSUE TITLE
`file` constructor in `doc/source/devel/register_me.py`

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [nipy/nibabel#1274]
Noticed this code, where `file` is neither a Python 3 built-in, nor imported:
https://github.com/nipy/nibabel/blob/1ee4983a55fae5da47fbf197fb97d17157a22534/doc/source/devel/register_me.py#L41

This looks like a Python 2 left-over:
https://python.readthedocs.io/en/v2.7.2/library/functions.html#file
https://portingguide.readthedocs.io/en/latest/builtins.html#removed-file

Has [`doc/source/devel/register_me.py`](https://github.com/nipy/nibabel/blame/master/doc/source/devel/register_me.py) ever been run recently? Is it still useful?

**Comment by effigies** [comment]
This seems to be something dpkg related. Possibly @yarikoptic or @mih would know what the use case is, but clearly nobody has run this in years. I'm okay to delete it.

**Comment by effigies** [comment]
I'd guess it has something to do with https://nipy.org/nipy/users/install_data.html, then. Which I don't think anybody still uses.

**Comment by DimitriPapadopoulos** [comment]
If so, the following files might be deleted:
* [`doc/source/installing_data.rst`](https://github.com/nipy/nibabel/blame/master/doc/source/devel/installing_data.rst)
* [`doc/source/devel/data_pkg_design.rst`](https://github.com/nipy/nibabel/blame/master/doc/source/devel/data_pkg_design.rst)
* [`doc/source/devel/register_me.py`](https://github.com/nipy/nibabel/blame/master/doc/source/devel/register_me.py)

**Comment by yarikoptic** [comment]
FWIW 

```shell
❯ git show --stat ec163399251a7c449a4a54fc660c8504abc0a705
commit ec163399251a7c449a4a54fc660c8504abc0a705
Author: Matthew Brett <matthew.brett@gmail.com>
Date:   Mon Dec 6 17:44:08 2010 -0500

    DOC - fleshed out use cases with example code

 doc/source/devel/data_pkg_uses.rst | 254 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 doc/source/devel/register_me.py    |  49 +++++++++++++++++
 2 files changed, 303 insertions(+)
```

so only @matthew-brett would know for sure. And given that `win32` was involved, likely that `dpkg` has nothing to do with Debian, but rather some ad-hoc "data package" ;)

altogether, if not used ,indeed could be let RiP
