### ISSUE TITLE
270 tests fail because of quote issues

### ISSUE THREAD

**Issue by yurivict** [nipy/nibabel#1317]
See the log [here](https://freebsd.org/~yuri/nibabel-5.2.1-tests.log).

There are a lot of deltas like:
```
-    if dt.kind == 'c':
+    if dt.kind == "c":
```

Version: 5.2.1
Python-3.9
FreeBSD 14.0

**Comment by effigies** [comment]
Why are you running black?

**Comment by yurivict** [comment]
black just happened to be installed on this system.

**Comment by effigies** [comment]
Ah, it looks like your testing setup is injecting tests we don't use. Perhaps you have a global pytest configuration that needs to be isolated? You should be able to run our entire test suite with `tox`.

In any event, we will not be adopting `black`, so I'm going to close this issue.
