### ISSUE TITLE
Add free-threaded CI build

### ISSUE THREAD

**Issue by effigies** [nipy/nibabel#1322]
Python 3.13 will have experimental support for free-threading (Python with the GIL disabled). There are Python builds out there that we can use: https://dev.to/hugovk/help-us-test-free-threaded-python-without-the-gil-1hgf

First step will be to check on the status of numpy support (https://github.com/numpy/numpy/issues/26157) and make sure we know the minimum version/date we can work from. Then we'll need to either fetch nightly wheels or ensure that the CI job can build numpy from scratch.

After a first pass build is working, we can start adding optional dependencies, when they are confirmed to work with free-threading.

**Comment by ngoldbaum** [comment]
Numpy has nightlies up on linux now, FWIW.
