### ISSUE TITLE
appropriate reading/derivation of bvalues and bvectors in the dicom readers

### ISSUE THREAD

**Issue by satra** [nipy/nibabel#152]
@matthew-brett  in the data set i have shared with you, the dicom reader fails to return appropriate bvalues and bvectors. i will post a link here once that data set is made publicly available either on xnat or on midas.

**Comment by effigies** [comment]
@satra Any chance you know/can determine if this is resolved? Or possibly this is related to @mgxd's #727?

**Comment by satra** [comment]
i would close this. too old at this point and pydicom has come a long way. let's focus on #727 as a real issue.
