### ISSUE TITLE
Support for partial read/write access

### ISSUE THREAD

**Issue by mih** [nipy/nibabel#18]
This is closely related to issue #9, but asking for more general support of partial access to image data. Algorithms processing huge files might only need to have access to one slice/volume/voxel at a time. It would allow for implementing leaner tools if NiBabel would support partial read from images and partial write to images, i.e. either incrementally writing to a file (e.g. appending volumes), or iterating over a file and modifying its content in-place.

**Comment by effigies** [comment]
Looks like these docs [exist](http://nipy.org/nibabel/images_and_memory.html#saving-time-and-memory). Good to close?
