### ISSUE TITLE
Warn on degenerate array

### ISSUE THREAD

**Issue by samuelstjean** [nipy/nibabel#188]
Currently, nibabe let's you save an array that has no dimension without complaining, producing a corrupted file. For example

``` python
import nibabel as nib
import numpy as np
data = np.arange(1000).reshape(10,10,10)
# This should be invalid, but the save nifti will be corrupted instead
nib.save(nib.Nifti1Image(data[45:46], np.eye(4)),'broken.nii.gz')
data[45,489] # This returns an empty array
```

Since this behavior is valid, but is probably undesired, raising a warning saying that the file is empty would be nice.

**Comment by effigies** [comment]
This doesn't seem to have really bitten us in 6 years, and it's fallen far enough back in the list to rarely get looked at. Closing for now. If it's still an issue, please reopen and let's aim to create a test case and its desired behavior.
