### ISSUE TITLE
nibabel.concat_images returns 5D images from 4D images

### ISSUE THREAD

**Issue by GaelVaroquaux** [nipy/nibabel#207]
If I concat a list of 4D images, I get a 5D image.

I was a bit surprised by this behavior: this is not what I was expecting from the docstring.

Maybe an option to avoid this behavior, and concat along the last axis, and not the last+1 axis would be useful. Another option would be to concat along a specified axis (given as a kwarg to concat_images), that could be '4' by default.

**Comment by bcipolli** [comment]
Is there a recommended solution to this?  I couldn't find any elegant ways to eliminate the unary 4th dimension.  Since my images were size 1 in the 4th dimension, I could do:

```python
all_files = glob.glob('fM00223/*.img')
all_images = [nibabel.funcs.four_to_three(nibabel.load(f))[0] for f in all_files]
func_img = nibabel.funcs.concat_images(all_images)
```

**Comment by matthew-brett** [comment]
I'm sorry, I just ran out of time for the 2.0 release, but I still agree that an axis keyword would be good.  Do you have any time to hack that up as a pull-request?   That would be the best solution.  Otherwise it's pretty easy to do by hand, by adapting the code in `concat_images`.
