### ISSUE TITLE
Indian code store in Gifti file should be "LittleEndian" instead of "GIFTI_ENDIAN_LITTLE"

### ISSUE THREAD

**Issue by duchesnay** [nipy/nibabel#283]
The gifti dtd  "www.nitrc.org/frs/download.php/115/gifti.dtd" mentions:
Endian       (BigEndian |
                    LittleEndian)  #REQUIRED

However the recoding thanks to "gifti_endian_codes" in  nibabel/nibabel/gifti/util.py
Leads to store "GIFTI_ENDIAN_LITTLE". This cause problem to freesurfer to read gifti file generated with nibabel.

Additionaly, is it possible to swith the default encoding of GiftiDataArray() from B64GZ to B64BIN. This way Freesurfer and other gifti readers will be able to read gifti files generated by nibabel.

**Comment by matthew-brett** [comment]
Hi @duchesnay - I'm assuming the new release fixes this - does it?  Can I close this one?

**Comment by matthew-brett** [comment]
I believe this one is fixed by https://github.com/nipy/nibabel/pull/233 - but feel free to re-open if I'm wrong.
