### ISSUE TITLE
Q: Sign up for zenodo before release

### ISSUE THREAD

**Issue by larsoner** [nipy/nibabel#294]
Zenodo allows software to be cited more easily. If we sign up for it before release, then it will automatically detect the release and make a new DOI for it. @matthew-brett WDYT? Here's an example in the mne-python README:

https://github.com/mne-tools/mne-python
http://zenodo.org/record/11556#.VIIT6-ZGjUY

**Comment by matthew-brett** [comment]
Eric - sorry to be ignorant - but is this working?   Where do the results go?

**Comment by Eric89GXL** [comment]
Hmm, looks like it didn't work. It might be that the person who is going to make the release tag needs to be the one to activate the webhook on zenodo.org

**Comment by effigies** [comment]
Might also need to draft a GitHub "release", not just push a tag to make Zenodo happen. It's been a bit, but I think I had that issue.

https://github.com/nipy/nibabel/releases/new

**Comment by effigies** [comment]
That said, it might make sense for @matthew-brett to set the hooks, because then he'll be able to manage the editing on the Zenodo end, too.

I believe, when it works, after a minute or two you should see a draft in https://zenodo.org/deposit/

**Comment by matthew-brett** [comment]
Hi,

I am trying to set up a DOI number for a release from the repository
at https://github.com/nipy/nibabel.

I am logged in as myself ('matthew-brett') at github.

I believe I have done this correctly.  I did that about five hours ago.

When I go to:

https://zenodo.org/deposit/

I see, at the right of that page:

"""
My uploads
Submitted
nibabel: 2.1.0   13 seconds ago
"""

where '13 seconds ago' seems to refer to the last time I clicked on
the 'nibabel: 2.1.0' link.  When I click on that link, I get this
page:

https://zenodo.org/deposit/147072/

which still (after 5 hours) tells me that "Editing is only possible
after your upload have been fully integrated. Please wait a few
moments, then try to reload the page.".  If I click on 'View', I get
this page:

https://zenodo.org/record/60808

That page has (for the last 5 hours) the message:

"""
Page Not Found

The page you were looking for doesn't exist. If you just submitted a
new upload, your record may still be in process of being uploaded. Do
not hesitate to contact us if it takes longer than 5 minutes.
"""

Have I done a step incorrectly?

Many thanks for your help,

Matthew

**Comment by matthew-brett** [comment]
Sorry - the last entry on this thread was a Cc of an email to zenodo support.

**Comment by matthew-brett** [comment]
Dear Matthew,

Thank you for contacting us.

The record https://zenodo.org/record/60808 is ( https://zenodo.org/record/60808%C2%A0is ) now fully
published and accessible. We're very sorry for the delay.

The publishing of a record can occasionally take longer (in some
cases up to several hours) if there are some delays in the DOI
registration, or we're experiencing a high activity from our
users
at given moment (e.g. a high upload activity). We are currently
working on the next version of Zenodo which will be much more
stable and responsive, thus the publishing of records will be
done
almost instantly.

Please let us know if you have any questions.

Best regards,

Krzysztof Nowak

Zenodo Support

http://zenodo.org ( http://zenodo.org )

On August 24, 2016 at 4:35 PM Matthew Brett wrote:

Hi,

I am trying to set up a DOI number for a release from the
repository

at https://github.com/nipy/nibabel ( https://github.com/nipy/nibabel ).

I am logged in as myself ('matthew-brett') at github.

I believe I have done this correctly. I did that about five
hours ago.

When I go to:

https://zenodo.org/deposit/ ( https://zenodo.org/deposit/ )

I see, at the right of that page:

"""

My uploads

Submitted

nibabel: 2.1.0 13 seconds ago

"""

where '13 seconds ago' seems to refer to the last time I clicked
on

the 'nibabel: 2.1.0' link. When I click on that link, I get this

page:

https://zenodo.org/deposit/147072/ ( https://zenodo.org/deposit/147072/ )

which still (after 5 hours) tells me that "Editing is only
possible

after your upload have been fully integrated. Please wait a few

moments, then try to reload the page.". If I click on 'View', I
get

this page:

https://zenodo.org/record/60808 ( https://zenodo.org/record/60808 )

That page has (for the last 5 hours) the message:

"""

Page Not Found

The page you were looking for doesn't exist. If you just
submitted a

new upload, your record may still be in process of being
uploaded. Do

not hesitate to contact us if it takes longer than 5 minutes.

"""

Have I done a step incorrectly?

Many thanks for your help,

Matthew

Powered by UserVoice. ( http://www.uservoice.com/powered-by?utm_campaign=poweredby&utm_medium=email&utm_source=ticket&uv_company=ZENODO&uv_contact_url=zenodo.uservoice.com&uv_experience=email )
