### ISSUE TITLE
shape has 4 dimensions for a 3d image

### ISSUE THREAD

**Issue by satra** [nipy/nibabel#299]
is there a reason why shape has the 4th dimension?

```
images[0] = nb.load('cope01.nii.gz')
images[0].shape
(91, 109, 91, 1)
```

**Comment by matthew-brett** [comment]
Nibabel gives you whatever is in the header.  I guess someone added an extra dimension when saving it.

**Comment by satra** [comment]
thanks @matthew-brett - that would be ANTs!

**Comment by satra** [comment]
@matthew-brett - is there a quick of converting it to a pure 3d file?

**Comment by satra** [comment]
in memory

**Comment by matthew-brett** [comment]
You could try `nibabel.squeeze_image` ...

**Comment by satra** [comment]
gracias - that works!
