### ISSUE TITLE
Convert dicm to nifti with nibabel

### ISSUE THREAD

**Issue by TheChymera** [nipy/nibabel#303]
Is it possible to use nibabel to convert dicom files to nifti? I was not able to find this info on the [tutorials page](http://nipy.org/nibabel/tutorials.html#tutorials).

I found a dicom2nifti tutorial on the nipype wiki, but that requires freesurfer, a d I would like to avoid using freesurfer (for this).

**Comment by matthew-brett** [comment]
I think you want https://github.com/moloney/dcmstack for that.  dcmstack uses nibabel under the hood.

**Comment by TheChymera** [comment]
So nibabel has all the functionality needed for the conversion, but I need another package to put all those functions together? There is no way to do this directly from nibabel?

**Comment by matthew-brett** [comment]
Specifically, the combination of pydicom and nibabel has everything you need in principle, but then there is the tricky sfuff about sorting slices and volumes into volumes and time-series, with the right shapes and order.  This stuff, is what dcmstack does.   We do plan to merge dcmstack and nibabel at some point, but that's been going rather slowly I'm afraid...
