### ISSUE TITLE
Nifti surface files misshapen when loaded

### ISSUE THREAD

**Issue by effigies** [nipy/nibabel#309]
As noted in #100, FreeSurfer can put surface files into niftis. For example, on a machine that has FreeSurfer installed:

    $ mri_convert $SUBJECTS_DIR/fsaverage/surf/lh.orig.avg.area.{mgh,nii}

To examine the files:

    >>> fmt = os.path.join(os.environ['SUBJECTS_DIR'], 'fsaverage/surf/lh.orig.avg.area.{}').format
    >>> mgh = nib.load(fmt('mgh'))
    >>> nii = nib.load(fmt('nii'))

We see:

    >>> mgh.shape
    (163842, 1, 1)
    >>> nii.shape
    (27307, 1, 6)
    >>> np.all(np.squeeze(mgh.get_data()) == nii.get_data().transpose().reshape(-1))
    True

So the data's the same, but reshaped and has an axis rolled. I think the expected behavior would probably be a `Nifti1Image` with the same shape as the `MGHImage`.

On the plus side, `nib.load(x).to_filename(x)` seems to produce files that FreeSurfer tools accept without complaint (and look the same at first glance).

I could probably write up the above in test form in the next couple days, but I'm really not sure where to begin digging into Nifti1Image to fix this. It's also possible that the problem is that `mri_convert` is producing `nii`s with bad headers.

**Comment by effigies** [comment]
I've done some more digging and this appears to be a distinctly `fsaverage` related bug. All of the other subjects I've tested this on load into an `(x, 1, 1)` shape.

If nibabel is interested in accommodating this bug, I demonstrate a fix at 65d51ad. This may not be the best place to put such a check, but it does the job. Also, conveniently throws up a warning about FreeSurfer nonsense from #100.

**Comment by effigies** [comment]
Okay, not a FreeSurfer bug but a hack. Had I read #100 more carefully I would have seen it's because 163842 won't fit in 16 bits.

My feeling is that, in this case, nibabel should support the (x/6, 1, 6) convention for both reading and writing Nifti surface files.

**Comment by matthew-brett** [comment]
OK - fair enough - would you consider doing a PR with a test?   Is this / 6 hack documented somewhere?

**Comment by effigies** [comment]
Sure. Might take a little time. I'll see if I can find some documentation or piece of code that makes this explicit. I'm only guessing it's always by 6, but it could simply be the first n > 1 such that n|x and x/n < 65536.
