### ISSUE TITLE
'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by cccbauer** [nipy/nibabel#311]
Hi,

I am trying to convert par/rec to nii to feed them into a real-time system, but somehow the par/rec files that Philips scanner dumps into the folder are not converted and 'NoneType' object has no attribute 'groups' appears.

thanks so much

clemens

**Comment by matthew-brett** [comment]
Thanks for the report.

I guess you are using `parrec2nii` from the command line?

Can you isolate the error to a particular call to `parrec2nii`?

**Comment by cccbauer** [comment]
Yes, I'm using it form the command line, I just typed in parrec2nii Dump-0000.par with no selected options.
it gives:

Caught 1 exceptions. Dump follows:

 Dump-0000.par: 'NoneType' object has no attribute 'groups'

**Comment by matthew-brett** [comment]
Can you share `Dump-0000.par` publicly or privately so I can take a look?

**Comment by cccbauer** [comment]
yes, here you have:

https://www.dropbox.com/sh/afvly1lu04c9ms0/AAAYDoIlq-H7EnZpfLVt4jq3a?dl=0

**Comment by matthew-brett** [comment]
Thanks - I see the problem - will fix later on today.

**Comment by cccbauer** [comment]
Fantastic, I appreciate it very much!

**Comment by cccbauer** [comment]
Just for additional information, It also seems that the par/rec files that come from the scanner include phase images and here is a matlab code which can help figure out how the files are structured.
 thanks


x_res = 80;
y_res = 80;
dynamics = 50; 
mixes = 2; % is 2 for rt dumps
slices = 44; % is 1 for rt dumps
a = y_res * dynamics * mixes * slices;  % Number of columns of raw data
 
filenamestruct=dir('*.rec');
for dump=1:length(filenamestruct)
    storedname=filenamestruct(dump).name;
    
    fid = fopen(storedname, 'r', 'l');
    Data(:,:) = fread(fid, [x_res,a],'uint16');
    fclose(fid);
    
    % if mixes = 2, the first is the phase image, 
    % i.e. Data4D(:,:,:,1,:) is the phase matrix
    if mixes == 1
        Data4D = reshape(Data,x_res,y_res,slices,[]); % Matrix has structure [x_voxels, y_voxels, slices, dynamics]  
    elseif mixes == 2
        Data4D = reshape(Data,x_res,y_res,slices,mixes,[]); % Matrix has structure [x_voxels, y_voxels, slices, phase, dynamics]
    else
        disp('Error: Mix number unknown')
    end
end

**Comment by matthew-brett** [comment]
Can I distribute your Dump-0000.par file under an MIT license with nibabel, to use it for tests?

**Comment by cccbauer** [comment]
Yes, of course, however, if you could  also include the University of Massachusetts Medical School in the license.
thanks

**Comment by matthew-brett** [comment]
Something like this OK for license: https://github.com/nipy/nibabel/pull/312  (I used PDDL in fact)?

**Comment by cccbauer** [comment]
yes, thanks!

**Comment by matthew-brett** [comment]
OK - ready for review - what do you think?

**Comment by cccbauer** [comment]
Ok, first, how do I get the newest version of parrec2nii, reinstal nibabel?

**Comment by matthew-brett** [comment]
What system are you on?  Windows / OSX / Linux?  From where did you get your copy of Python?

**Comment by cccbauer** [comment]
Im on linux and use anaconda

**Comment by matthew-brett** [comment]
```
conda create -n nibabel-test numpy
pip install git+git://github.com/matthew-brett/nibabel@fix-par-parsing
```

Should work (I think).

**Comment by matthew-brett** [comment]
Sorry - you might need to do `conda install pip` before the `pip install` command.

**Comment by cccbauer** [comment]
It is working great! Thanks so much for the fix! I appreciate it a lot.

best

clemens
