### ISSUE TITLE
Refactoring around checking for scipy 

### ISSUE THREAD

**Issue by bcipolli** [nipy/nibabel#324]
In refactoring `imageclasses.py` to distribute info into individual image classes (#323), I want to implement a simple function to check if scipy exists. I see that scipy checking is a bit varied across the code:

* Different files define their own function / decorators (`imageclasses.py`, `tests/test_spm99analyze.py`, `tests/test_image_load_save.py`, `tests/test_image_api.py`, etc), using different methods to check (`ImportError`, `optional_package`, etc)
* Some tests pass if scipy doesn't exist (even if required); other tests are skipped if scipy doesn't exist.

I suggest the following cleanup:
* Create a file `utils.py`, and add `have_scipy()` as a function.
* Use this function everywhere (in image classes where scipy status determines if they're makeable, in tests to determine if they're skippable, and other conditional logic)

Posting here just to double-check before doing the work.

**Comment by bcipolli** [comment]
Or I could just use `optional_package` everywhere, and ignore what's going on elsewhere... :)

**Comment by matthew-brett** [comment]
I would go for optionalpackage everywhere, and if you have the interest, refactor the other code to do the same, for consistency.  I guess the older code didn't use optionalpackage because it didn't exist yet.

**Comment by bcipolli** [comment]
This was fixed in 0129ea50baecfee83d01388b7e3a1278b9d3aa28
