### ISSUE TITLE
TST: test_back_tick calls python directly

### ISSUE THREAD

**Issue by FRidh** [nipy/nibabel#341]
In the test `test_back_tick()` in `nibabel/nisext/tests/test_testers.py` python is called. This test will fail on systems where the binary is named differently. E.g., on systems with only Python 3 where the binary is called python3.

In the testers package the interpreter is chosen using `sys.executable`. Could that be done here as well?

**Comment by Eric89GXL** [comment]
+1 for `sys.executable`
