### ISSUE TITLE
ImportError: No module named dicom

### ISSUE THREAD

**Issue by MadsJensen** [nipy/nibabel#350]
Hi,
I get the following error trying to load dicom files with nibabel. The files are from a Siemens Skyra. 

    data,affine,bvals,bvecs = read_mosaic_dwi_dir(dcm_dir)
    Traceback (most recent call last):

    File "<ipython-input-8-40e949d760f1>", line 1, in <module>
      data,affine,bvals,bvecs = read_mosaic_dwi_dir(dcm_dir)

    File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/nibabel/nicom/dicomreaders.py", line 44, in read_mosaic_dwi_dir
      dicom_kwargs=dicom_kwargs)

    File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/nibabel/nicom/dicomreaders.py", line 89, in read_mosaic_dir
      dcm_w = wrapper_from_file(fname, **dicom_kwargs)

    File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/nibabel/nicom/dicomwrappers.py", line 52, in wrapper_from_file
      import dicom

    ImportError: No module named dicom

I have pydicom install, any ideas what the problem might be? 

best wishes,
mads

**Comment by matthew-brett** [comment]
What do you get for:

```
python -c 'import dicom'
```

How did you install pydicom?  Is it possible that you installed it with `pip` and the `pip` you used was not the one from Anaconda?

**Comment by moloney** [comment]
I am guessing it is due to pydicom 1.0 being installed. The module name changes from "dicom" to "pydicom": https://github.com/darcymason/pydicom/wiki/Porting-to-pydicom-1.0

**Comment by moloney** [comment]
Hmm, sorry for the noise. I guess 1.0 isn't quite out yet.

**Comment by MadsJensen** [comment]
@matthew-brett  I get:
python -c 'import dicom'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named dicom

@moloney yes I have pydicom 1.0 from git installed. 

I tried with the pip version as well, but that didn't work either. But it was the anaconda pip, so it sounds like that is why.

**Comment by moloney** [comment]
The code needs to be update to work with pydicom 1.0, but should work with 0.99 and earlier.

**Comment by MadsJensen** [comment]
thanks, I fixed the pydicom version and it works.

**Comment by matthew-brett** [comment]
I made a new issue for this, just so we don't forget: https://github.com/nipy/nibabel/issues/351
