### ISSUE TITLE
XML parsers

### ISSUE THREAD

**Issue by effigies** [nipy/nibabel#359]
#354 added XML generation with the builtin `xml` library, which shouldn't be a security issue, but [parsing](https://github.com/nipy/nibabel/blob/master/nibabel/gifti/parse_gifti_fast.py) is a potential problem as malformed XML can cause pathological behavior in the parser.

There are "defused" packages to prevent these issues (e.g. https://pypi.python.org/pypi/defusedxml/), but this would mean adding a dependency, which needs discussion.

**Comment by matthew-brett** [comment]
Chris - sorry to be slow to respond to this. 

A pure Python dependency is OK, I think, especially if it is optional.   I was a bit worried to see that the last release of defusedxml was 2013, and the last commit was November 2015 : https://bitbucket.org/tiran/defusedxml .  Do you know of any alternatives?

**Comment by effigies** [comment]
Not really. I came across these packages via the [official docs](https://docs.python.org/3/library/xml.html#defused-packages).

**Comment by effigies** [comment]
Just an update: defusedxml has made a 0.5.0 release to support Python 3.6 about a year ago. Perhaps the low churn is due to stability?

**Comment by effigies** [comment]
According to https://github.com/tiran/defusedxml/issues/27#issuecomment-422435344:

> the project is pretty much abandoned. The next versions of CPython 2.7, 3.6, and 3.7 as well as expat 2.3.0 will contain all necessary fixes.

Going to go ahead and close this.
