### ISSUE TITLE
Incomplete documentation for dcm2nii algorithms

### ISSUE THREAD

**Issue by bcipolli** [nipy/nibabel#374]
The documentation for `dcm2nii_algorithms` ends with:
```
There’s a function ``
```
http://nipy.org/nibabel/dicom/dcm2nii_algorithms.html

The line should be removed, or the thought should be completed :)

**Comment by matthew-brett** [comment]
Thanks for pointing that out - I just pushed straight to master given it's an obvious doc fix.
