### ISSUE TITLE
Add six to legal / 3rd party code docs

### ISSUE THREAD

**Issue by bcipolli** [nipy/nibabel#375]
`six` doesn't appear here:
http://nipy.org/nibabel/legal.html#rd-party-code-and-data

There is a copyright notice at the top of `six.py`; perhaps we should just copy it into `legal.rst`. Version is 1.3, so download location should be: 
https://pypi.python.org/packages/source/s/six/six-1.3.0.tar.gz#md5=ec47fe6070a8a64c802363d2c2b1e2ee
taken from
https://pypi.python.org/pypi/six/1.3.0

**Comment by matthew-brett** [comment]
I think the definitive source is the `COPYING` file (`legal.rst` is a link to COPYING).

Yes, six should definitely go in there.
