### ISSUE TITLE
nibabel documentation out of sync with numpy style guide

### ISSUE THREAD

**Issue by bcipolli** [nipy/nibabel#376]
First, the link to the numpy style guide no longer works. Here's the new link:
https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt

Second, there are a few differences in style worth noting:
* [Use single ticks (\`var\`), not double-ticks (\`\`var\`\`)](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#common-rest-concepts) for variables, parameters, modules in docstrings
* Docs for class `__init__` functions should [appear in the class docstring directly](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#class-docstring).

I'll update the URL in the docs; just posting this info as a place for potential discussion, as I will try to follow the above in future PRs.

**Comment by matthew-brett** [comment]
Ben - can we close this one?

**Comment by bcipolli** [comment]
Sounds good to me!
