### ISSUE TITLE
Ohloh.net is hanging webpage load

### ISSUE THREAD

**Issue by bcipolli** [nipy/nibabel#378]
This url is hanging loading of nibabel docs:
https://www.ohloh.net/projects/480908/widgets/project_partner_badge

Maybe useful to load that asynchronously? It's been like this for at least two days.

![image](https://cloud.githubusercontent.com/assets/4072455/10999824/06cf0e12-8453-11e5-8871-d185e1238383.png)

**Comment by effigies** [comment]
ohloh.net is now openhub.net. This URL works: https://www.openhub.net/projects/480908/widgets/project_partner_badge

**Comment by bcipolli** [comment]
Cool. I will update the docs.

**Comment by bcipolli** [comment]
Full list of widgets, and code to embed them, are here. I selected a slightly smaller image to fit better in the sidebar.
https://www.openhub.net/p/nibabel/widgets

**Comment by bcipolli** [comment]
This looks bad:
![image](https://cloud.githubusercontent.com/assets/4072455/11000826/af90ff42-8458-11e5-88c5-8ffdd7adf11e.png)

Unless I can figure out how to style their iframe to be smaller (and I don't think I can without some javascript), I am thinking this:
![image](https://cloud.githubusercontent.com/assets/4072455/11001134/8500182e-845a-11e5-93e4-e6d3edae529c.png)
