### ISSUE TITLE
Add flake8 to continuous integration

### ISSUE THREAD

**Issue by bcipolli** [nipy/nibabel#400]
Style-checking should be part of tests. Any unwanted style checks could be put into `tox.ini`.

This would require:
* Run `flake8` (`pep8`/`pyflakes`) again; #337 apparently wasn't enough!
* Update our `tox.ini` to exclude unwanted checks.
 * Add `flake8` to the travis run.

@matthew-brett @effigies is this cool?

**Comment by effigies** [comment]
Yeah, there were some definite pep8/flakes remnants (especially tests), and I'm not sure we've been too assiduous about enforcing style on more recent PRs, so having checks in Travis would be great.

:+1:

**Comment by bcipolli** [comment]
Cool. `autopep8` seems to be doing a good job, so it's really not that hard to set up...
