### ISSUE TITLE
Book 30 minutes of maintainer time per day

### ISSUE THREAD

**Issue by matthew-brett** [nipy/nibabel#410]
Recently, it has been hard for me (your friendly maintainer) to get to pull requests and other things.

This has been for various reasons, but my plan is now that - if anyone wants me to

a) answer a question about nibabel;
b) look at an open issue or [NIAP](https://github.com/nipy/nibabel/wiki);
c) review a pull-request;

then I'm offering an average of 30 minutes per day at which I am at your disposal.   If you want to book that 30 minutes, comment on this issue here, saying what you'd like me to do, and I'll reply.

Sometimes I won't have 30 minutes in a day of course, but I'm committing to an average of 30 minutes per day, over the (6 day) week.  So, unless you see some comment on this thread like "I am stuck under a tree, won't get to me email for 5 days", expect me to reply within 1-2 days to every request.

If I get several requests at the same time, I'll take them in the order they arrived, or explain why I want to do them in a different order.

Please, keep the requests coming, I'm looking forward to hearing what y'all come up with.

**Comment by MarcCote** [comment]
I guess I'll start the ball rolling! I really appreciate the time you spend on my PR about the streamlines API and I'd like to continue having your input so we can close it in a near future. :-)

**Comment by matthew-brett** [comment]
Thanks for getting the ball rolling...

I'll take that as booking Monday's 30 minute slot - you should hear from me by the end of Monday... :)

**Comment by satra** [comment]
@matthew-brett - i think the cifti PR #249 is also a good one to review in an upcoming 30 min slot.

**Comment by Eric89GXL** [comment]
#404 would be good, too

**Comment by matthew-brett** [comment]
Satra - could you / Ben clarify what the status of PR 249 is?  Is it ready for review?

**Comment by matthew-brett** [comment]
Eric - sure - I want to finish up the tests and merge #255 - that should be an hour or two of work now. After that I will do the #404 .  I hope / expect that to be around Thursday.

**Comment by matthew-brett** [comment]
I just finished up work on #255 and I'm taking the liberty of treating that work as 30 minutes for Eric's request about #404.  Now I'm going to actually work on #404.

For the CIFTI, I had a quick look at the test failures and commented.  From Ben's comment on that PR, it sounds as if it would be most efficient for me to wait on that PR until after the weekend - is that reasonable?

**Comment by satra** [comment]
@matthew-brett - sounds good to wait after the weekend for CIFTI PR.
