### ISSUE TITLE
Why does nibabel use so many relative imports?

### ISSUE THREAD

**Issue by arokem** [nipy/nibabel#424]
A question we've been struggling with over here: 

https://github.com/nipy/dipy/issues/968
https://github.com/nipy/dipy/issues/969

Can you tell we're confused?

**Comment by matthew-brett** [comment]
It was the fashion at some point.   The general idea was that it was easier to move pieces of the tree around, moving the subpackage with the tests, for example.

I haven't to my knowledge had any problems with relative imports, and we're currently sort of -0 on them, for the main tree, and -0.5 on them for the tests.

**Comment by arokem** [comment]
Thanks for the quick reply! I agree there's nothing urgent about this issue, but was wondering whether some strong compelling reason led to this. Closing...
