### ISSUE TITLE
Parrec sorting broken with numpy 1.7

### ISSUE THREAD

**Issue by matthew-brett** [nipy/nibabel#435]
See : http://nipy.bic.berkeley.edu/builders/nibabel-py2.7-fedora/builds/175/steps/shell_5/logs/stdio

The sorting appears to work differently for numpy 1.7, compared to numpy 1.6 and numpy >= 1.8.  Example error:

```
======================================================================
FAIL: nibabel.tests.test_parrec.test_sorting_dual_echo_T1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mb312/.virtualenvs/nibabel/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/mb312/dev_trees/nibabel/nibabel/tests/test_parrec.py", line 294, in test_sorting_dual_echo_T1
    assert_equal(np.all(sorted_echos[:n_half] == 1), True)
AssertionError: False != True
```

**Comment by matthew-brett** [comment]
@grlee77  - any ideas about this one?  I suspect it's a numpy bug - but can you see a workaround?

**Comment by grlee77** [comment]
I will see if I can come up with anything

**Comment by grlee77** [comment]
I made a new conda environment with Python 2.7 and numpy 1.7.1 (and 1.7.0) and could not reproduce the bug.  Can you reproduce it on another machine?

I also checked numpy's issue tracker, but couldn't find any `lexsort` issues/fixes that looked related.

**Comment by matthew-brett** [comment]
Yes, I can reproduce it on my Mac (I use Python.org Python and pip).   It also appears on two separate Linux machines from the buildbots.   What platform are you using?

**Comment by grlee77** [comment]
I tried on Ubuntu linux 14.04.  Will try my mac laptop or system python in a bit

**Comment by matthew-brett** [comment]
This one's on Debian sid for example : http://nipy.bic.berkeley.edu/builders/nibabel-py3.3/builds/218/steps/shell_5/logs/stdio

Careful of system Python on the mac, unless you do something special, it will ignore any numpies you install : https://github.com/MacPython/wiki/wiki/Which-Python

**Comment by grlee77** [comment]
OK, I can reproduce the failures on OS X in a conda environment with python 2.7 and numpy 1.7.1.  I will try to investigate further later tonight.

**Comment by grlee77** [comment]
@matthew-brett 
As you suspected, numpy was the culprit.  It is a bug in `np.shuffle` (numpy/numpy#4286) which I used in some of the test cases to shuffle the `image_defs` in-place prior to testing the sort ordering.   The bug doesn't effect any of the PARREC routines themselves, but just the setup for some of my the test cases!

 I will make a PR to use something like the following utility function in `test_parrect.py` rather than np.shuffle.  Does that sound reasonable?
```python
def _shuffle(arr):
    """Return a copy of the array with entries shuffled.

    Needed to avoid a bug in np.shuffle for numpy 1.7.
    see:  numpy/numpy#4286
    """
    return arr[np.argsort(np.random.randn(len(arr)))]
```

**Comment by matthew-brett** [comment]
Thanks very much for checking that - yes that sounds like a good solution to me.  We should also test on numpy 1.7 on travis just to be sure we're catching these types of things.
