### ISSUE TITLE
CIFTI file format support

### ISSUE THREAD

**Issue by unidesigner** [nipy/nibabel#44]
The Human Connectome Project blesses the community with the Nifti2-based CIFTI format for connectivity information and the like: http://www.nitrc.org/plugins/mwiki/index.php/cifti:ConnectivityMatrixFileFormats

**Comment by bcipolli** [comment]
Looks like nifti2 has been implemented, and that there's a CIFTI2 format. I'm interested in getting the Human Connectome Project data available to `nilearn` and other packages, so I could be talked into doing this.

@matthew-brett any pointers on how to approach this? Looks like this NITRIC forum post is a good starting point--look at what they've done in C++ / other formats, then try to recapitulate the logic here?
http://www.nitrc.org/forum/forum.php?thread_id=4380&forum_id=1955

**Comment by matthew-brett** [comment]
Satra did a first pass at this here:

https://github.com/nipy/nibabel/pull/249

I'm afraid I haven't paid it as much attention as I should have.  My memory is that I was worried that the API was too ad-hoc.

Would you mind taking a look at that PR?  What do you think of the API?

**Comment by bcipolli** [comment]
That's great, thanks for the pointer! I will start there.
