### ISSUE TITLE
4D minc2 image

### ISSUE THREAD

**Issue by klarcher** [nipy/nibabel#448]
Hi,
Does nibabel read minc2 4D image ?
Below is the error I got when trying to upload it :

.../python2.7/site-packages/nibabel-2.0.0-py2.7.egg/nibabel/loadsave.pyc in load(filename, **kwargs)
     42        Image of guessed type
     43     '''
---> 44     return guessed_image_type(filename).from_filename(filename, **kwargs)
     45 
     46 

.../python2.7/site-packages/nibabel-2.0.0-py2.7.egg/nibabel/spatialimages.pyc in from_filename(klass, filename)
    697     def from_filename(klass, filename):
    698         file_map = klass.filespec_to_file_map(filename)
--> 699         return klass.from_file_map(file_map)
    700 
    701     @classmethod

.../python2.7/site-packages/nibabel-2.0.0-py2.7.egg/nibabel/minc2.pyc in from_file_map(klass, file_map)
    150         if holder.filename is None:
    151             raise MincError('MINC2 needs filename for load')
--> 152         minc_file = Minc2File(h5py.File(holder.filename, 'r'))
    153         affine = minc_file.get_affine()
    154         if affine.shape != (4, 4):

.../python2.7/site-packages/nibabel-2.0.0-py2.7.egg/nibabel/minc2.pyc in __init__(self, mincfile)
     62         for dim in self._dims:
     63             if dim.spacing != b'regular__':
---> 64                 raise ValueError('Irregular spacing not supported')
     65         self._spatial_dims = [name for name in self._dim_names
     66                               if name.endswith('space')]

ValueError: Irregular spacing not supported

**Comment by matthew-brett** [comment]
I'm afraid Nibabel (at the moment) has no way of encoding irregular spacing in time, which it seems your image has.   Can you rewrite it without the time step information?

**Comment by klarcher** [comment]
I need to read the image in order to run matrices calculation, also to scan the image header.
Do you mean by "rewrite without the time step info" ?

**Comment by matthew-brett** [comment]
I mean - do you have access - for example - to the MINC tools?    

I think the problem is that your image has recorded values for the time at which each volume is acquired - see : https://en.wikibooks.org/wiki/MINC/Reference/MINC2.0_File_Format_Reference#Dimension_variable_attributes

So I was hoping you could use another tool to rewrite this image without this info.

But you could also try just disabling the check that raised the error, by commenting out the line starting `raise ValueError('Irregular` - and add a `pass` to replace it.  Does that work?

**Comment by klarcher** [comment]
Yes I defintely have acess to the MINC tools. It works properly.
I can still use pyminc. However it does not return the duration of each time-frame of my functional image.

By commenting out the line starting "raise ValueError" and adding a pass, I got the same error :

.../python/local/Canopy_64bit/User/lib/python2.7/site-packages/nibabel/minc2.py in __init__(self, mincfile)
     64         for dim in self._dims:
     65             if dim.spacing != b'regular__':
---> 66                 pass
     67                 #raise ValueError('Irregular spacing not supported')
     68         self._spatial_dims = [name for name in self._dim_names

ValueError: Irregular spacing not supported

**Comment by effigies** [comment]
Your `minc2.py` file isn't getting recompiled. It's running the old code, but showing you the updated source. Did you restart your Python interpreter?

**Comment by klarcher** [comment]
In my first post, I did use nibabel-2.0.0 (sorry). I did download the nibabel-master.zip. The error in the very last post had been returned using the lastest version from github. Yes I did restart the python interpreter.

**Comment by effigies** [comment]
Sorry, I was unclear.

```Python
.../python/local/Canopy_64bit/User/lib/python2.7/site-packages/nibabel/minc2.py in __init__(self, mincfile)
     64         for dim in self._dims:
     65             if dim.spacing != b'regular__':
---> 66                 pass
     67                 #raise ValueError('Irregular spacing not supported')
     68         self._spatial_dims = [name for name in self._dim_names

ValueError: Irregular spacing not supported
```

The above suggests to me that what's happening is that you are running a version where line 66 still reads `raise ValueError('Irregular spacing not supported')`, but when it looks at the source file to show you the offending line, it's reading the updated version. Restarting the python interpreter, I'd think, should have resolved the mismatch. Only other thing I can think of is to kill your interpreter, remove the `.pyc` file, and start it back up, forcing it to recompile.

**Comment by klarcher** [comment]
Ok, sorry for my misunderstanding. Everything look fine now. Thanks a lot to the both of you.
