### ISSUE TITLE
Documentation link on nibabel homepage is dead

### ISSUE THREAD

**Issue by mwaskom** [nipy/nibabel#453]
Hi,

On the nibabel homepage (http://nipy.org/nibabel/), there is a dead link (it just hangs and never connects) to the documentation. I've copied the structure of the page and bolded the list element below with the dead link:

# Code
## You can find our sources and single-click downloads:

- Main repository on Github;
- **Documentation for all releases and current development tree;**
- Download the current release from pypi;
- Download current development version as a zip file;
- Downloads of all available releases.

I think the problem is that it is pointing to nipy.github.io.

**Comment by matthew-brett** [comment]
Thanks - good catch.  And the mailing list link is out of date.   I'll fix on the maintenance branch...

**Comment by matthew-brett** [comment]
Fixed I think - do you agree?

**Comment by mwaskom** [comment]
I'm having a little trouble sorting out how the nibabel sphinx is assembled, but it doesn't look like your last two commits on the maint/2.x branch touched [this text](http://nipy.org/nibabel/#code) which is where I originally found the issue.

**Comment by matthew-brett** [comment]
Oops - I fixed the same problem but further up.  Yes, the doc build is a bit complicated but this info comes from `nibabel/info.py` (I eventually discovered).

**Comment by matthew-brett** [comment]
@mwaskom - can I close this one?

**Comment by mwaskom** [comment]
Yep just tested and that link works!
