### ISSUE TITLE
Use load/save with file object instead of filesystem path

### ISSUE THREAD

**Issue by dimrozakis** [nipy/nibabel#454]
Suppose I have an **open file object** to some nii file. To make things easier with file type discovery, I also have the original **filename** of the nii file, for example `exam.nii.gz`. But there's **no file path** and therefore I can't access the file that way. Maybe the path is unknown, maybe it's not even stored on some local filesystem.

Is it possible to perform `nib.load` to load that file as a NiftiImage?
Is it possible to save a NiftiImage to such a file?

There are several use cases such a thing would be beneficial:
- Transient nii files being processed by a system that has them stored in some unknown temporary location or even entirely in memory, but that provides a file-like object to the actual data.
- Custom file-like object types that perform on the fly operations such as:
  - Compression/Decompression (I know this is natively supported)
  - Encryption/Decryption
- File-like objects to files actually stored on some remote object store and accessible via an API (like s3).

To load such a file object I could first write it to disk in order to read it using nibabel, and to perform the opposite I could have nibabel save it to disk and then read it into the file object, but this would seriously affect performance.

Is it currently supported to use file-like objects for such operations?

**Comment by matthew-brett** [comment]
It is - have a look at the `make_file_map` and `from_file_map` methods of the image classes - say `Nifit1Image`.  It certainly does need a better and more discoverable API - any suggestions?

**Comment by dimrozakis** [comment]
Thanks! I'll look into it

**Comment by matthew-brett** [comment]
For example, I could imagine that `nibabel.load` could accept a file object, and, for images that only have one file associated (such as `.nii` files, but not `.img, .hdr` Nifti pairs), could use this file object as the `image` fileobject part of the file map referred to in the methods I pointed to.

And / or have a `nibabel.load_from_fileobj` function that does the same thing, which might point to a new `from_fileobj` method of the image classes.

**Comment by effigies** [comment]
@dimrozakis It looks like your concern was addressed? Closing for now, but please reopen if this is still an issue.
