### ISSUE TITLE
MemoryError when sequentially loading data

### ISSUE THREAD

**Issue by naddoth** [nipy/nibabel#467]
Hi,
I m calling sequentially several sequences by using the function load() and get_data(). Before calling a sequence (of size 26Mo) I delete all the variables. However, at the third load I get a Memory error.
How could I manage this error?
Thanks in advance for any return.

`
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Work/QualityAssessmentSSIM/mainSSIM.py", line 40, in <module>
    seq_data = np.asarray(seq_nii.dataobj)

  File "C:\Python27\lib\site-packages\numpy\core\numeric.py", line 462, in asarray
    return array(a, dtype, copy=False, order=order)

  File "C:\Python27\lib\site-packages\nibabel\arrayproxy.py", line 145, in __array__
    return apply_read_scaling(raw_data, self._slope, self._inter)

  File "C:\Python27\lib\site-packages\nibabel\volumeutils.py", line 961, in apply_read_scaling
    arr = arr + inter

MemoryError
`

**Comment by matthew-brett** [comment]
Do you get the same effect when running from a Python shell such as IPython?

Are your images really 28MB in total?    How much memory does your machine have?

**Comment by naddoth** [comment]
Thank for your rapid response.
Yes I got the same error.
The nii.gz file is of size: 24.6Mo, the RAM of 4Go

**Comment by matthew-brett** [comment]
Can you post somewhere a script that generates the error, and the relevant file?

**Comment by matthew-brett** [comment]
By the way - private dropbox link or similar is fine, if you can't share the data publicly.

**Comment by naddoth** [comment]
Yes the data is private. What I can say about it is that its a nifit file obtained by converting a DICOM by dcm2nii Mricron tool.

here the code
`
for file in os.listdir(path_ims):
    if file.endswith(".nii.gz"): #NIfTI 1 image
        name_seq_nii = file #ecrasment
del file   

full_path = os.path.join(path_ims, name_seq_nii)
seq_nii = nib.load(full_path)
seq_data = seq_nii.get_data()

slice_10 = seq_data[:, :, 10]

del seq_data, seq_nii
`

**Comment by matthew-brett** [comment]
Can you share the file just with me somehow?  There's nothing obvious in your script to explain the problem.

**Comment by matthew-brett** [comment]
There's no way of debugging this one without a file to replicate with, so closing this one.  Please do re-open if you can share (privately) a file that we can use.
