### ISSUE TITLE
fully deprecate (i.e. remove) some RFed years ago methods

### ISSUE THREAD

**Issue by yarikoptic** [nipy/nibabel#477]
I see that `to_filespec` was deprecated in 2010 (36d8c21bd11166fd36f8642e3ff8189b1bc1c41f, i.e. upstream/1.0.0.dev~16) so may be it is time to prune those which were marked deprecated in 1.x series completely in 2.x or at least in some 3.x at least whenever that one comes?
Now it seems a good portion of `.to_` methods is deprecated, complicating "guess writing" of code via completions ;)

I think I saw somewhere (thought it was numpy but their decorator seems to be not as sophisticated), some decorator so you could mark your version when you are going to deprecate the method, so if originally you did

``` python
@deprecate('2.0.0')
def to_be_removed():
```

then whenever you release 2.0.0 (adjust `__version__` to be 2.0.0), it would simply cause an error demanding physical removal, and thus reminding about necessity... or I just dreamed it up?

**Comment by matthew-brett** [comment]
That decorator does sound like a good idea.  I can't remember seeing that written though.  I had a quick look in numpy, scipy, matplotlib.

It is probably a good idea to elevate the deprecationwarning to make sure they are visible, I believe they will be suppressed by default at the moment.

How would this decorator work when the version number goes to the version where the function will be removed?  The tests will fail, but there's a risk of changing the version number expecting the tests to still pass, and then releasing with a broken package.

**Comment by yarikoptic** [comment]
Fwiw Myself I always run tests during pkg build whenever version is already changed.

**Comment by matthew-brett** [comment]
How about https://github.com/nipy/nibabel/pull/479 ?

**Comment by effigies** [comment]
Closing, since this seems to have been handled by #479. @yarikoptic please reopen if something remains to be addressed.
