### ISSUE TITLE
Best way to cite nibabel in a paper

### ISSUE THREAD

**Issue by iglpdc** [nipy/nibabel#482]
Which is the best way to cite nibabel in a research paper? I couldn't find any pointers in the documentation.

**Comment by matthew-brett** [comment]
Sorry to be slow to get back to you.  The best way to cite nibabel, as of 30 minutes ago, is by going to the https://github.com/nipy/nibabel/releases page, choosing your nibabel release, and then using the Zenodo DOI on the relevant page.  Eric Larson helped us to set that up (thanks Eric).

Release 2.1 has a DOI already, the others, back to 1.3, are waiting for Zenodo to process them.  Should be done by the end of tomorrow.

**Comment by matthew-brett** [comment]
All done back to nibabel 1.0.0

**Comment by iglpdc** [comment]
Great! Thanks!
