### ISSUE TITLE
Understanding between get_data().dtype.kind to get_data_dtype().kind

### ISSUE THREAD

**Issue by KamalakerDadi** [nipy/nibabel#490]
Hello nibabel team,

I could not able to figure out why there is a difference in type between ```get_data().dtype``` and ```get_data_dtype()```. From ```get_data().dtype.kind=f``` to ```get_data_dtype().kind=i``` ? Any hints are appreciated.

Here, is the Nifti image for testing and below is the small code snippet.
[mni_icbm152_gm_tal_nlin_sym_09a.nii.tar.gz](https://github.com/nipy/nibabel/files/502932/mni_icbm152_gm_tal_nlin_sym_09a.nii.tar.gz)

```python
import nibabel as nib

icbm = nib.load('attached_image')
icbm.get_data().dtype.kind
icbm.get_data_dtype().kind
```
cc @GaelVaroquaux

**Comment by matthew-brett** [comment]
Maybe `get_data_dtype` isn't well named, it could better be `get_storage_dtype`.   Nibabel converts to this dtype before saving the image data to a file.

This often isn't the same as the image data dtype; if the image specifies scaling factors, as is often the case, then a storage dtype of type int will change to float type after applying the scale factors.

**Comment by GaelVaroquaux** [comment]
> Maybe get_data_dtype isn't well named, it could better be get_storage_dtype.
> Nibabel converts to this dtype before saving the image data to a file.

OK, so we were using it wrong. We have found our bug! Thanks

**Comment by KamalakerDadi** [comment]
@matthew-brett Thanks for your reply.

What would be alternative to ```get_data_dtype()``` to use ?

Just in case if the header of the Nifti image is bad and could not be able to retreive ```dtype``` with ```get_data().dtype``` ?

**Comment by matthew-brett** [comment]
If you have the header, you can predict the dtype.  The data will be loaded from disk as the datatype in `get_data_dtype()`.  If either of the slope or intercept are not default - (1, 0) respectively - then the data will be upcast to float by the multiplication / addition.  Get the scalefactors with `header.get_slope_inter()`.   Otherwise the data stays the same dtype as loaded.

**Comment by KamalakerDadi** [comment]
Thank you very much for your quick replies.
