### ISSUE TITLE
question about function: nibabel.freesurfer.io.read_annot()

### ISSUE THREAD

**Issue by anbai106** [nipy/nibabel#497]
Hello, 
I have a question about this function, i dont know if i put this question to the right place, if not, sorry...
so if i set `orig_ids=False`
Si the returned value `labels` will give me back the annotation id, like this:

> array([11, 11, 11, ..., 27, 27, 27])

And names will give me the name of the labels, like:

> ['unknown', 'bankssts', 'caudalanteriorcingulate', 'caudalmiddlefrontal', 'corpuscallosum', 'cuneus', 'entorhinal', 'fusiform', 'inferiorparietal', 'inferiortemporal', 'isthmuscingulate', 'lateraloccipital', 'lateralorbitofrontal', 'lingual', 'medialorbitofrontal', 'middletemporal', 'parahippocampal', 'paracentral', 'parsopercularis', 'parsorbitalis', 'parstriangularis', 'pericalcarine', 'postcentral', 'posteriorcingulate', 'precentral', 'precuneus', 'rostralanteriorcingulate', 'rostralmiddlefrontal', 'superiorfrontal', 'superiorparietal', 'superiortemporal', 'supramarginal', 'frontalpole', 'temporalpole', 'transversetemporal', 'insula']

> 

So my question is if the annotation id  corresponds to the sequence of names, let's say, the first value in labels is 11, so this will corresponds to the 11th value in names--'isthmuscingulate', Is this right???

I dont find explanation about this sequence problem in your documentation, neither in FreeSurfer wiki, So if I did some statistical analysis for the different regions of cortical surface, how I can corresponds to the annotation id to the different region???

But if you consider this and make the sequence acting like what I guess, that would be great, and aliviate our life:)

Correct me if I understood it in a wrong way:)

Thanks very much
Good night

Hao

**Comment by anbai106** [comment]
anybody there???

**Comment by effigies** [comment]
That would be my expectation, give or take an off-by-one for 0-indexing.

@agramfort, this looks like your contribution. Any help here?

**Comment by agramfort** [comment]
yes that should be it. You can visualize it eg with pysurfer

**Comment by effigies** [comment]
Closing this. @anbai106 please re-open if your question wasn't answered.
