### ISSUE TITLE
create a nifti image with a specific datatype

### ISSUE THREAD

**Issue by satra** [nipy/nibabel#498]
i need to create a nifti image stored on disk as an 8 bit datatype. does the following suffice:

```
import nibabel as nb
import numpy as np
img = nb.load(tmp_aseg)
data = img.get_data()
data = (data > 0).astype(np.uint8)
img.set_data_dtype(np.uint8)
nb.Nifti1Image(data, img.affine, img.header).to_filename('aseg.nii.gz')
```

**Comment by effigies** [comment]
@satra You probably already have your answer, but for searchability:

Yes, though I'd `set_data_dtype` on the result image, so that it's done after the header is copied from the original. If you're throwing away the original issue, that concern is obviously moot.
