### ISSUE TITLE
Data scaling

### ISSUE THREAD

**Issue by JavierCoronel** [nipy/nibabel#523]
Hi,

I have a dataset of .nii.gz images and I want all of them with the same voxelsize. I get this scaling done in matlab by rescaling the values in pixdim. Now, I want to make this rescaling with nibabel but do not know how.

I tried `set_qform` and it changed the pixdim info in the header, but the `img.shape` is still the same that before applying the affine transformation.

Somebody could help me?

**Comment by matthew-brett** [comment]
You can change the 'pixdim' directly with something like:

```
img.header['pixdim'][1:4] = [2, 3, 4]
```

I wouldn't expect this to change the `img.shape` value though - that is the number of voxels in each array dimension.

**Comment by JavierCoronel** [comment]
Thanks, that also changes the info of pixdim. 

But how can I change the pixdim values in such a way that changes also the size of the matrix? If I set the pixdim smaller than the original it is supposed that the matrix will be bigger.

**Comment by matthew-brett** [comment]
I think what you're asking is how to resample the image down to a smaller voxel size?   So, you want to change the image to have more voxels, subsampled from the original data?   You can try something like:

```
from nibabel.processing import resample_to_output
big_img = resample_to_output(img, [2, 2, 2])
```

where [2, 2, 2] is your desired voxel size.

**Comment by JavierCoronel** [comment]
That's exactly what I was looking for. 

Thank you.

**Comment by ROOKLO** [comment]
Hi @matthew-brett 
I am a little confused about this: why it does not change the image shape(or say the number of pixels) by applying the different affine matrix. And if I want to resample the image voxel as isotropy (let's say 1*1*1) when I use the convolutional network to processing it, which method should I use?  
1.Applying the identity affine matrix to all images to change the 'pixdim' as [1, 1, 1]
or 
2. resampling the voxel size (by interpolations? I am not sure about this ) and this will change the image shape

**Comment by matthew-brett** [comment]
@ROOKLO - I'm not quite sure what you're asking.   Are you saying you already have the resampled array, but you want a matching affine for it?

**Comment by ROOKLO** [comment]
> @ROOKLO - I'm not quite sure what you're asking. Are you saying you already have the resampled array, but you want a matching affine for it?

My bad and Nope. 
when I perform the convolutional neural network, I wish the input image have the same pixel/voxel size, and there seems to have two methods to achieve this goal, as u mentioned in this issue before: change the pixdim (I am thinking this can be done by applying the identity affine matrix 
`nib.Nifti1Image(dataobj=src_data, affine=np.eye(4, 4))` 
 in this, the number of the pixel/voxel doesn't change)
or using the 
`resample_to_output(test_img, voxel_size=[1, 1, 1])` 
(this will change the number of the pixel/voxel)
I'm don't know which is more reasonable for CNN. And why the first method (the pixdim one) doesn't change the number of voxels, but the pixdim is changed indeed. 
and thx for the reply!

**Comment by matthew-brett** [comment]
The affine is just the mapping of the voxel coordinates to world-space coordinates - see https://nipy.org/nibabel/coordinate_systems.html . So, changing the affine doesn't have any effect on the underlying voxel grid, it just changes the spatial interpretation of any given voxel coordinate from that grid.

I can't answer in general about whether you should prefer a resampled array for your CNN.  My instinct would be that you would be better off with the raw, not-resampled data - but I suppose that could depend on the details of your CNN.   Does your CNN have some requirements on the input data?  What are they?

I'm surprised that the CNN cares about the affine matrix.  How does it come into play?

**Comment by ROOKLO** [comment]
I don't think CNN cares about the affine matrix or saying the voxel coordinates to world-space coordinates. (At least in my task, it doesn't. May in some situations, need CNN to consider the position relation between objects in world-space coordinates......and why don't put them in one object, hahaha..... I don't know, just guessing).

It's the papers I read before, and some of them mentioned resampling (by interpolation) the voxel to the same size before performing the CNN. I didn't figure out why and don't understand how affine works. Maybe these masks you misunderstood my words. 

My data are CT images, and they don't have the same voxel size, but all of them have the same voxel number in width and height dimension (image shape). I'm using 2DCNN now (what about 3D? Do I need to resample it ?). I am not sure whether I need to resample the voxel, actually. 

About resampling the voxel, whether they just want every voxel to represent the information at the same level? If u know about this.
thx again!

**Comment by matthew-brett** [comment]
I think you will need to work out whether you too need to resample your images to have the same millimeter size in each dimension.  If not, you don't have to worry, and you can use the raw images.  If so, then you'll need `resample_to_output(test_img, voxel_size=[1, 1, 1])` or similar.   And yes, I suppose you're right, if you're working in 2D, and assuming that the voxels are the same size in x and y, you won't need to resample.

**Comment by ROOKLO** [comment]
It helps me a lot, thank you very much!
