### ISSUE TITLE
API documentation missing

### ISSUE THREAD

**Issue by effigies** [nipy/nibabel#527]
Might just be me, but it looks like none of these listings are links: http://nipy.org/nibabel/api.html

**Comment by ltirrell** [comment]
I have the same issue, and I remember being able to click through the listings a few months back. The index (access by keywords) page is also blank: http://nipy.org/nibabel/genindex.html

**Comment by matthew-brett** [comment]
Sorry - I messed up when building the docs on my machine - is all good now?

**Comment by effigies** [comment]
Looks good. Thanks!
