### ISSUE TITLE
nib.get_data() error for register fucntional image

### ISSUE THREAD

**Issue by grjd** [nipy/nibabel#537]
Hi,
I registered a functional volume with spm.
I can load it fine, but when I want to access the data returns an error. 

myf = nib.load(image_file)
myf.shape 
(79, 95, 79, 116)

**IOError: Expected 275103280 bytes, got 2371580 bytes from  wfiltered_func_data.nii
 - could the file be damaged?**

IOError                                   Traceback (most recent call last)
<ipython-input-100-ec2e9362aa77> in <module>()
----> 1 first_rsn = image.index_img(im2, 0)

/Users/jaime/Library/Python/2.7/lib/python/site-packages/nilearn/image/image.pyc in index_img(imgs, index)
    554     """
    555     imgs = check_niimg_4d(imgs)
--> 556     return _index_img(imgs, index)
    557
    558

/Users/jaime/Library/Python/2.7/lib/python/site-packages/nilearn/_utils/niimg_conversions.pyc in _index_img(img, index)
     72     """Helper function for check_niimg_4d."""
     73     return new_img_like(
---> 74         img, img.get_data()[:, :, :, index], get_affine(img),
     75         copy_header=True)
     76

/usr/local/lib/python2.7/site-packages/nibabel/spatialimages.pyc in get_data(self, caching)
    570         if self._data_cache is not None:
    571             return self._data_cache
--> 572         data = np.asanyarray(self._dataobj)
    573         if caching == 'fill':
    574             self._data_cache = data

/usr/local/lib/python2.7/site-packages/numpy/core/numeric.pyc in asanyarray(a, dtype, order)
    531
    532     """
--> 533     return array(a, dtype, copy=False, order=order, subok=True)
    534
    535 def ascontiguousarray(a, dtype=None):

/usr/local/lib/python2.7/site-packages/nibabel/arrayproxy.pyc in __array__(self)
    143     def __array__(self):
    144         # Read array and scale
--> 145         raw_data = self.get_unscaled()
    146         return apply_read_scaling(raw_data, self._slope, self._inter)
    147

/usr/local/lib/python2.7/site-packages/nibabel/arrayproxy.pyc in get_unscaled(self)
    138                                        offset=self._offset,
    139                                        order=self.order,
--> 140                                        mmap=self._mmap)
    141         return raw_data
    142

/usr/local/lib/python2.7/site-packages/nibabel/volumeutils.pyc in array_from_file(shape, in_dtype, infile, offset, order, mmap)
    533                           n_bytes,
    534                           n_read,
--> 535                           getattr(infile, 'name', 'object')))
    536     arr = np.ndarray(shape, in_dtype, buffer=data_bytes, order=order)
    537     if needs_copy:

IOError: Expected 275103280 bytes, got 243269632 bytes from /Users/jaime/vallecas/data/cadavers/nifti/bcpa_0537/session_0/noreg.feat/filtered_func_data.nii
 - could the file be damaged?
[print (myf.header).txt](https://github.com/nipy/nibabel/files/1029469/print.myf.header.txt)

**Comment by matthew-brett** [comment]
Does SPM load the file OK?   For example, can you display it in the SPM viewer?

**Comment by matthew-brett** [comment]
My guess is that the file is in fact damaged - that is, it has less data in it than the header says it does.  Specifically, from your error message, the header is saying it has 79 volumes, but in fact it only has bytes enough for one volume:

```
In [1]: shape = 79, 95, 79, 116
In [2]: size = 275103280
In [3]: import numpy as np
In [4]: n_elements = np.prod(shape)
In [5]: bytes_per_element = size / n_elements
In [6]: bytes_per_element
Out[6]: 4.0
In [7]: voxels_per_volume = np.prod(shape[:-1])
In [8]: bytes_per_volume = voxels_per_volume * bytes_per_element
In [9]: size / bytes_per_volume
Out[9]: 116.0
In [10]: actual_size = 2371580
In [11]: actual_size / bytes_per_volume
Out[11]: 1.0
```

**Comment by effigies** [comment]
Hi @grjd, did you resolve your issue?

**Comment by effigies** [comment]
Closing for now. Please reopen if you're still having issues.
