### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by massich** [nipy/nibabel#538]
In [DICOM voxel to patient coordinate system mapping](http://nipy.org/nibabel/dicom/dicom_orientation.html), the article linked to [http://fixunix.com/dicom/50449-image-position-patient-image-orientation-patient.html](http://fixunix.com/dicom/50449-image-position-patient-image-orientation-patient.html) is no longer there.

**Comment by effigies** [comment]
By the URL I'm going to guess that was a mailing list or newsgroup post, and looking for the sequence of words in the slug gets this thread in comp.protocols.dicom: [Image Position (Patient) and Image Orientation (Patient)](https://groups.google.com/forum/#!topic/comp.protocols.dicom/-Nms_GgmdRc)

@matthew-brett Does that look right?

**Comment by matthew-brett** [comment]
@effies - excellent deduction - see : https://web.archive.org/web/20120213061539/http://fixunix.com/dicom/50449-image-position-patient-image-orientation-patient.html

@massich - thanks very much for pointing this out. 

See: https://github.com/nipy/nibabel/pull/539

**Comment by massich** [comment]
@matthew-brett cool. Feel free to close the issue
