### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by mgxd** [nipy/nibabel#540]
Any plans for cutting a new release? I'd love to have the CIFTI support.

**Comment by effigies** [comment]
Hi @matthew-brett. I agree w/ @mgxd that it would be nice to get CIFTI (along with all the other improvements and fixes) out in an official release.

Is there anything I can do to speed the release along?

**Comment by jchoude** [comment]
I'm in the same boat, would really like to get the streamlines.tck format support.

**Comment by satra** [comment]
@matthew-brett - is there anything in particular holding up the release? anything we can help with?

**Comment by matthew-brett** [comment]
Mainly - my day job!  But also - I wanted to get this in:

https://github.com/nipy/nibabel/pull/551

It just needs a little more work - but one or more reviews at this stage would be very useful.
