### ISSUE TITLE
loading DICOM images

### ISSUE THREAD

**Issue by massich** [nipy/nibabel#542]
#### Description
Dicom is not part of the supported image formats

#### Steps/Code to Reproduce
```Python
from nilearn.datasets.utils import _fetch_file as download
from nilearn.datasets.utils import _uncompress_file as unzip
from nibabel import load as nib_load
from pydicom.filereader import read_file as pydcm_load

download('http://www.barre.nom.fr/medical/samples/files/CT-MONO2-16-brain.gz',
         data_dir='./',
         md5sum='fa2b7cf8bfa6bb15ecbd79edce394cfa',
         overwrite=True)
unzip('CT-MONO2-16-brain.gz')

data = pydcm_load('CT-MONO2-16-brain')
print(data.SOPInstanceUID)

data = nib_load('CT-MONO2-16-brain')
```
#### Expected Results
`data` contains the example image

#### Actual Results
it crasses 
```
<ipython-input-64-7b48de179599> in <module>()
     13 print(data.SOPInstanceUID)
     14 
---> 15 data = nib_load('CT-MONO2-16-brain')

/home/sik/miniconda3/lib/python3.6/site-packages/nibabel/loadsave.py in load(filename, **kwargs)
     46 
     47     raise ImageFileError('Cannot work out file type of "%s"' %
---> 48                          filename)
     49 
     50 

ImageFileError: Cannot work out file type of "CT-MONO2-16-brain"
```

#### Versions
Linux-4.8.0-49-generic-x86_64-with-debian-stretch-sid
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
NumPy 1.12.1
SciPy 0.19.0
Pydicom 1.0.0a1
NiBabel 2.1.0

**Comment by effigies** [comment]
I'm not sure what all the hang-ups are (I have never tried working with them) but `nibabel.load` doesn't work with dicoms. I would check [this section](http://nipy.org/nibabel/reference/nibabel.nicom.html#module-nibabel.nicom) of the API for the appropriate classes. Looking at the [tests](https://github.com/nipy/nibabel/blob/master/nibabel/nicom/tests/test_dicomwrappers.py#L163-L180) looks like the way to open a dicom file is:

```Python
import nibabel.nicom.dicomwrappers
img = nibabel.nicom.dicomwrappers.wrapper_from_file(fname)
```
