### ISSUE TITLE
API documentation only shows classes

### ISSUE THREAD

**Issue by ashgillman** [nipy/nibabel#546]
The API documentation doesn't show any functions. I can't quite recall, but I believe it used to, there may be an issue in the documentation generation configuration (that's a mouthful)?

E.g.: http://nipy.org/nibabel/reference/nibabel.affines.html#module-nibabel.affines
![image](https://user-images.githubusercontent.com/816777/28348511-bacfeafa-6c80-11e7-916d-c86f3eeaa067.png)

**Comment by matthew-brett** [comment]
Good catch - I think this is fixed now - take a look?

**Comment by ashgillman** [comment]
Perfect :)
