### ISSUE TITLE
FYI: AppVeyor

### ISSUE THREAD

**Issue by Eric89GXL** [nipy/nibabel#547]
Just a heads-up -- AppVeyor had been running on my personal account name because of how they set things up by default. I have now made a `nipy` AppVeyor account, and put PySurfer and nibabel under it instead. Let me know if any other nipy folks would like to be added as administrators on the nipy account.

I assume it should be the [core](https://github.com/orgs/nipy/teams/core/members) members to start?

**Comment by arokem** [comment]
Thanks. Please do add me.

**Comment by arokem** [comment]
Also -- relatedly: I don't see any of the nipypers in "core". We should probably add them to that team.

@satra (sorry to pick on you, but I know you probably know the answer): who should we add to nipy/core at this point to represent the nipype universe?

**Comment by satra** [comment]
@arokem - to allow for a better bus factor could you please add @chrisfilo and myself.

**Comment by effigies** [comment]
I would at least like privileges to cancel jobs. When commits are coming fast, AppVeyor can be a major bottleneck.

**Comment by arokem** [comment]
@satra, @chrisfilo : done!

**Comment by Eric89GXL** [comment]
Okay I added `nipy/Core` as "Administrator" in AppVeyor. Hopefully y'all can GitHub-sign-in as "nipy" on AppVeyor now.
