### ISSUE TITLE
Converting intensities to hounsfield units in nifti file

### ISSUE THREAD

**Issue by nmurali269** [nipy/nibabel#549]
Hello,

I have converted a series of CT images that were originally DICOM files into NifTI, which I am using to derive intensity values. I have a range of intensity values that I am looking to convert to Hounsfield units. I understand that the linear transformation to convert from intensity to Hounsfield is typically stored in a DICOM header under slope and intercept. However, in the NiFTI file, these header categories are set to NaN (not a number.)

scl_slope : nan
scl_inter : nan

Is there a way to find the slope and intercept from a NifTI file header (or elsewhere) to convert from intensity to Hounsfield units?

Thanks!

**Comment by matthew-brett** [comment]
Hi,

On Tue, Aug 15, 2017 at 11:36 AM, nmurali269 <notifications@github.com>
wrote:

> Hello,
>
> I have converted a series of CT images that were originally DICOM files
> into NifTI, which I am using to derive intensity values. I have a range of
> intensity values that I am looking to convert to Hounsfield units. I
> understand that the linear transformation to convert from intensity to
> Hounsfield is typically stored in a DICOM header under slope and intercept.
> However, in the NiFTI file, these header categories are set to NaN (not a
> number.)
>
> scl_slope : nan
> scl_inter : nan
>
> Is there a way to find the slope and intercept from a NifTI file header
> (or elsewhere) to convert from intensity to Hounsfield units?
>
Nibabel resets the slope and inter on load, so that you can set them
yourself, explicitly.

If you want the originals in the header on disk, have a look at:

img = nib.load('my_image.nii')
print(img.dataobj.slope, img.dataobj.inter)

Cheers,

Matthew

**Comment by nmurali269** [comment]
Hi Matthew,

Thanks so much for the help! That worked perfectly.

-N
