### ISSUE TITLE
step_size missing in .tck output header.

### ISSUE THREAD

**Issue by soichih** [nipy/nibabel#553]
Hi. 

I am using the latest version of nibabel to save our streamlines to .tck output with something like following code.

```
from nibabel.streamlines import Tractogram, save
...
streamlines = LocalTracking(prob_dg, tissue_classifier=classifier, seeds=seeds, step_size=.5, max_cross=1,affine=affine)
tractogram = Tractogram(streamlines, affine_to_rasmm=affine)
save(tractogram, 'track.tck')
```

This generates track.tck with following header info.

```
$ head track.tck
mrtrix tracks
count: 0000272259
datatype: Float32LE
file: . 67
```

I am having trouble opening this track.tck with Matlab - VISTASOFT dtiImportFibersMrtrix() function because VISTASOFT requires "step_size" field to be present in the header. 

It should look like

```
step_size: 0.2
```

Can/should nibabel be made to output this field?

**Comment by MarcCote** [comment]
Hi @soichih  
We follow the [TCK specification](http://mrtrix.readthedocs.io/en/latest/getting_started/image_data.html?highlight=format#tracks-file-format-tck). According to that documentation, the only two keys required in the header are `file` and `datatype`.

That said, you can always manually put additional information in the header like this:
```python
from nibabel.streamlines import Tractogram, save
from nibabel.streamlines import TCKFile
...
tck = TCKFile(tractogram)
tck.header['step_size'] = 0.2
save(tck, 'track.tck')
```  
or with this one-liner:
```python
save(tractogram, 'track.tck', header={'step_size': 0.2})
``` 
Let us know if that works for you.
Cheers

**Comment by MarcCote** [comment]
@soichih I see from https://github.com/brain-life/encode/issues/86 that you've figured it out. Can we close this issue? Thanks.

**Comment by soichih** [comment]
Yes, you can close this now. Thank you!
