### ISSUE TITLE
streamlines module can't be found

### ISSUE THREAD

**Issue by Dimitrievici** [nipy/nibabel#554]
Hi there, 

I'm trying to import the streamlines module in a Python script, but it tells me that there's no module named streamlines.

I'm using Python 2.7 on Anaconda on a Win32. After I import the nibabel library, I try:
from nibabel.streamlines import ArraySequence as Streamlines

What I get is:
ImportError: No module called streamlines.

Sorry, can't copy the code from my MinGW32.

Hope you can help

**Comment by matthew-brett** [comment]
Have you upgraded to the latest nibabel?

```
pip install -U nibabel
```

**Comment by effigies** [comment]
Hi @Dimitrievici has this been resolved?

**Comment by Dimitrievici** [comment]
everything is installed...

**Comment by effigies** [comment]
Hi @Dimitrievici, I'm not sure how to interpret your last post. Did you successfully install the latest nibabel?

If you're still having issues, could you share what version you're using?

```Python
import nibabel
print(nibabel.__version__)
```
