### ISSUE TITLE
transform a 3D into 4D

### ISSUE THREAD

**Issue by grjd** [nipy/nibabel#563]
Hi i habe a 4D nifti image that bt mistake has been created as 3D
image_data.shape is (128, 128, 3720)   
(the  z axis has 32(slices)*116 (time poits) = 3720)
I want to transform it into 
(128, 128, 32, 116)

**Comment by matthew-brett** [comment]
I think you want the mailing list for questions like that - this is for bugs / bad features in nibabel.

But, you could do:

```
image = nibabel.load('my_image.nii')
data = image.get_data()
new_image = nibabel.Nifti1Image(data.reshape((128, 128, 32, 116)), image.affine, image.header)
```

**Comment by effigies** [comment]
@grjd Please reopen if Matthew didn't answer your question.
