### ISSUE TITLE
FileNotFoundError: No such file: 'someones_epi.nii.gzip'

### ISSUE THREAD

**Issue by AnkitaS7** [nipy/nibabel#570]
I am trying to load an MRI, I keep getting the following error:
`Traceback (most recent call last):
  File "F:/Study/Projects/BTSaG/Programs/t3.py", line 2, in <module>
    epi_img = nib.load('someones_epi.nii.gzip')
  File "C:\Users\AnkitaShinde\AppData\Local\Programs\Python\Python35-32\lib\site-packages\nibabel\loadsave.py", line 38, in load
    raise FileNotFoundError("No such file: '%s'" % filename)
FileNotFoundError: No such file: 'someones_epi.nii.gzip'`

The code is used is as follows:
`import nibabel as nib
epi_img = nib.load('someones_epi.nii.gzip')
epi_img_data = epi_img.get_data()
epi_img_data.shape(53, 61, 33)

import matplotlib.pyplot as plt
def show_slices(slices):
    """ Function to display row of image slices """
    fig, axes = plt.subplots(1, len(slices))
    for i, slice in enumerate(slices):
        axes[i].imshow(slice.T, cmap="gray", origin="lower")

slice_0 = epi_img_data[26, :, :]
slice_1 = epi_img_data[:, 30, :]
slice_2 = epi_img_data[:, :, 16]
show_slices([slice_0, slice_1, slice_2])
plt.suptitle("Center slices for EPI image")
`
I even updated the loadsave.py file in nibabel but it didn't work. Please help.

**Comment by matthew-brett** [comment]
Is your file really called 'someones_epi.nii.gzip'?  Usually the extension
is '.gz' as in 'someones_epi.nii.gz'.
​

**Comment by AnkitaS7** [comment]
There is no error in the file name. I still tried both variations of file
name which resulted in the same error.

**Comment by effigies** [comment]
Is the python command being run from the directory that contains the file? With a relative path, this error could be resulting from the file not being in the working directory.

**Comment by AnkitaS7** [comment]
The file was copied in the working directory, it still raises the error.

Regards,
Ankita Shinde
*Computer Science major at WCE, Sangli*
shindeankita7@gmail.com
+91 9819396405

**Comment by matthew-brett** [comment]
Here's what I get in the same situation:

```
In [1]: import numpy as np
In [2]: import nibabel as nib
In [3]: nib.load('someones_epi.nii.gz')
Out[3]: <nibabel.nifti1.Nifti1Image at 0x10621c898>
In [4]: !cp someones_epi.nii.gz someones_epi.nii.gzip
In [5]: nib.load('someones_epi.nii.gzip')
---------------------------------------------------------------------------
ImageFileError                            Traceback (most recent call last)
<ipython-input-5-2022229c9b26> in <module>()
----> 1 nib.load('someones_epi.nii.gzip')

~/Library/Python/3.5/lib/python/site-packages/nibabel/loadsave.py in load(filename, **kwargs)
     46 
     47     raise ImageFileError('Cannot work out file type of "%s"' %
---> 48                          filename)
     49 
     50 

ImageFileError: Cannot work out file type of "someones_epi.nii.gzip"
```

That's what I'd expect (because of the incorrect file extension).

Have you tried upgrading nibabel to the latest version?  Maybe our error messages weren't as good in the old days.

**Comment by AnkitaS7** [comment]
The library is updated to the latest version

**Comment by pauldmccarthy** [comment]
The `nibabel` code where that error is raised is pretty simple, and I can't see it going wrong:

```python
    if not op.exists(filename):
        raise FileNotFoundError("No such file: '%s'" % filename)
```

Is there a chance that the working directory for the script is different to what you expect?  Are you calling it from a different directory?

Could you please verify that the file you are trying to load does actually exist in the expected directory? Modify your code as follows:

```python
import os
print(os.getcwd())
print(os.listdir('.'))
import nibabel as nib
epi_img = nib.load('someones_epi.nii.gzip')
```

**Comment by AnkitaS7** [comment]
The file path is C:\Users\AnkitaShinde\AppData\Local\Programs\Python\Python35‌​-32\Lib\site-package‌​s\nibabel\someones_e‌​pi.nii.gzip

**Comment by AnkitaS7** [comment]
The file path is C:\Users\AnkitaShinde\AppData\Local\Programs\Python\Python35‌​-32\Lib\site-package‌​s\nibabel\someones_e‌​pi.nii.gzip

**Comment by effigies** [comment]
Hi @ankitaS7, if you ask nibabel to open a file without a path, it's going to look in the current working directory (`os.getcwd()`), not the nibabel installation directory. I would not recommend putting data files in the nibabel installation directory.
