### ISSUE TITLE
Intent to deprecate: keep_file_open

### ISSUE THREAD

**Issue by effigies** [nipy/nibabel#573]
As of indexed_gzip [0.7.0](https://github.com/pauldmccarthy/indexed_gzip/releases/tag/v0.7.0), the default behavior of a `SafeIndexedGzipFile` is to close the underlying file between accesses. This pretty much obviates the machinery @pauldmccarthy built around the `keep_file_open` option in Opener, ArrayProxy, AnalyzeImage and MGHImage.

As we did have a release, we're going to need to deprecate the API, but I think the following scheme should be reasonably safe:

* Set minimum `indexed_gzip` version to 0.7.0
* Remove any effects of `keep_file_open` -  it only had any effect if `indexed_gzip` was installed AND `keep_file_open` was `'auto'` or `True` - and update docs to say "has no effect, will be removed vXXX"
* Any function that currently takes `keep_file_open` raises a `DeprecationWarning` if it is not `None`.
* Remove `arrayproxy.KEEP_FILE_OPEN_DEFAULT` - This one I'm not sure of. I think people would only be setting it, not reading it, but maybe it should stay just in case.
* Schedule full removal of option for v4.0

What do y'all think?

**Comment by pauldmccarthy** [comment]
Hey @effigies, I don't have any strong feelings either way about this, apart from wondering whether there might be some use case (or future file IO driver) which depends on having a persistent file handle. This is not a problem for me personally though. Happy to help out if this goes ahead too!

**Comment by pauldmccarthy** [comment]
I do like your `ReleasingFileHandle` idea - that would possibly make the existing code cleaner. Could this logic be built into the existing `Opener` class, and the `ArrayProxy` changed so that it persists a reference to a single `Opener`?

**Comment by effigies** [comment]
That might be the cleanest way of doing it. I had a brief look, but haven't had time to think carefully about how to do that. Feel free to push ahead, and I'll try to review. Otherwise I'll poke at it as I find time.

**Comment by pauldmccarthy** [comment]
Sure - I'm flying down under shortly so am quite busy, but I should have some time over the next couple of weeks.

**Comment by pauldmccarthy** [comment]
Hey @effigies, I've finally gotten around to working on this - #614 -  let me know what you think!
