### ISSUE TITLE
sform/qform codes clobbered when creating new image with adjusted affine

### ISSUE THREAD

**Issue by pauldmccarthy** [nipy/nibabel#574]
Howdy,

 I don't know if this should be considered a bug, but I have a use case where I am taking a `Nifti1Image`, resampling its data and adjusting the affine accordingly, and creating a new `Nifti1Image`. As part of this process, the `sform_code` and `qform_code` fields appear to get reset. For example (using nibabel 2.2.0):

```python
Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 08:49:46)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]:
   ...: import nibabel       as nib
   ...: import scipy.ndimage as ndi
   ...: import numpy         as np
   ...:
   ...:
   ...: image   = nib.load('MNI152_T1_2mm.nii.gz')
   ...: data    = image.get_data()
   ...: xform   = image.affine
   ...: header  = image.header
   ...:
   ...: # resample data to 1mm
   ...: oldShape    = np.array(image.shape[:3])
   ...: newShape    = oldShape * 2
   ...: scale       = np.eye(4)
   ...: r, c        = np.diag_indices(3)
   ...: scale[r, c] = oldShape / newShape
   ...: data2       = ndi.affine_transform(data, scale[:3, :3], output_shape=newShape)
   ...:
   ...: # adjust the affine so
   ...: # the resampled image is
   ...: # in the same space
   ...: xform2  = np.dot(xform, scale)
   ...: image2  = nib.nifti1.Nifti1Image(data2, xform2, header=header.copy())
   ...: header2 = image2.header
   ...:
   ...: print('image       shape: {}'.format(image.shape))
   ...: print('image      affine: {}'.format(image.affine))
   ...: print('image  sform_code: {}'.format(header[ 'sform_code']))
   ...: print('image  qform_code: {}'.format(header[ 'qform_code']))
   ...: print('image2      shape: {}'.format(image2.shape))
   ...: print('image2     affine: {}'.format(image2.affine))
   ...: print('image2 sform_code: {}'.format(header2['sform_code']))
   ...: print('image2 qform_code: {}'.format(header2['qform_code']))
   ...:
image       shape: (91, 109, 91)
image      affine: [[  -2.    0.    0.   90.]
 [   0.    2.    0. -126.]
 [   0.    0.    2.  -72.]
 [   0.    0.    0.    1.]]
image  sform_code: 4
image  qform_code: 4
image2      shape: (182, 218, 182)
image2     affine: [[  -1.    0.    0.   90.]
 [   0.    1.    0. -126.]
 [   0.    0.    1.  -72.]
 [   0.    0.    0.    1.]]
image2 sform_code: 2
image2 qform_code: 0

In [2]:
```

I traced this to a call to [`Nifti1Image.set_sform`](https://github.com/nipy/nibabel/blob/master/nibabel/nifti1.py#L1068) which occurs during creation:

```
 test.py:37:                                 image2  = nib.nifti1.Nifti1Image(data2, xform2, header=header.copy())
  nifti1.py:1765:                            file_map)
   analyze.py:923: dataobj,                  affine, header, extra, file_map)
    spatialimages.py:373:                    self.update_header()
     nifti1.py:2029:                         super(Nifti1Image, self).update_header()
      nifti1.py:1788:                        super(Nifti1Pair, self).update_header()
       spatialimages.py:407:                 self._affine2header()
        nifti1.py:1796:                      hdr.set_sform(self._affine, code='aligned')
         nifti1.py:1115:                     tr.trace('Aargh')
```

And I think the logic which controls this initialisation is in `SpatialImage.update_header`:

```python
        # If the affine is not None, and it is different from the main affine
        # in the header, update the header
        if self._affine is None:
            return
        if np.allclose(self._affine, hdr.get_best_affine()):
            return
        self._affine2header()
```

So essentially, if both a header and affine are provided, but the header affine does not match the provided affine, the `sform`/`qform` codes will get reset (as `_affine2header` calls `set_sform`).

Is this a bug, or is this user error? I don't know. The documentation for [`SpatialImage.__init__`](https://github.com/nipy/nibabel/blob/master/nibabel/spatialimages.py#L330) is ambiguous with respect to what should happen if both `header` and `affine` are specified.

* If it's user error, then maybe a note could be added to the docs making the expected behaviour unambiguous
* If you think this is a bug, then perhaps a clause could be added somewhere in the `__init__` hierarchy, which harmonises the header and affine before initialisation takes place. I haven't looked into this enough to figure out the best place for such a clause, but am happy to do so  if people think that this is the way to go.

What do you think?

**Comment by effigies** [comment]
I'm pretty sure this is the intended behavior. If I provide an affine and header, and the affine doesn't match the header, the intuitive interpretation IMO is that the explicitly provided affine is correct.

The choice of (invalid qform, aligned sform) for default xform codes seems sensible to me; a new affine probably reflects alignment to some other image, and the qform can't encode shears. This is also reasonable behavior from a downstream perspective: everybody but ANTs will give preference to sform, and setting qform to equal sform (if possible) ensures that ANTs will also load the correct affine.

If this default is not correct for the use case, it falls to the user to manually (re-)set the qform and sform to match their needs.

I think being very clear about this in the docs is a good idea. We should probably decide whether to include it in [Nifti1Pair](http://nipy.org/nibabel/reference/nibabel.nifti1.html#nifti1pair) or [The NIfTI affines](http://nipy.org/nibabel/nifti_images.html#the-nifti-affines) (and cross-link between the sections, if we're not already), so it's as easy as possible to find.

**Comment by pauldmccarthy** [comment]
Hey @effigies, thanks for the reply. Makes sense, although my intuition was the complete opposite of yours - I was expecting that the header info would be preserved, and only the affine would be updated. But as long as the behaviour is clear, it is easy to work around.

I'll try and find some time to update the docs on this.

**Comment by matthew-brett** [comment]
Paul - what do you mean by  "header info would be preserved, and only the affine would be updated"?  Do you mean that, if you pass an affine and a header with a different affine, then the affine information would be discarded?   You can pass None as the affine ...

It would be luverly if you time to add to the docs.

**Comment by pauldmccarthy** [comment]
Hey @matthew-brett, I mean that I originally expected that if I created an image like so:

```python
img = nib.nifti1.Nifti1Image(data, header=existing_header, affine=new_xform)
```

i.e. specifying both an existing header, and a new affine, that the header of the new image would retain all of the information from the specified header (including `sform`/`qform` codes), but would have the new affine. 

This was just an assumption that I made. I don't have a problem with the actual behaviour the way that it currently is :)

**Comment by matthew-brett** [comment]
But - just to clarify - the sform and qform are where the affine goes in the header.   So - were you expecting the header to stay unchanged in memory, but then get changed before writing to disk?  And then, were you expecting the sform to be changed by the qform to stay the same?  Or the other way round?

**Comment by matthew-brett** [comment]
Ah - no - I think I see - you were expecting the *codes* to stay unchanged - right?

**Comment by pauldmccarthy** [comment]
Yes - sorry, I meant to say that I assumed the values of the `sform_code`/`qform_code` would be preserved.

**Comment by pauldmccarthy** [comment]
What do you think about this addition to the [`nibabel.nifti1.Nifti1Pair`](https://github.com/nipy/nibabel/blob/master/nibabel/nifti1.py#L1756) documentation (and the approach I have taken to include it!?):

```python
    def __init__(self, dataobj, affine, header=None,
                 extra=None, file_map=None):
        super(Nifti1Pair, self).__init__(dataobj,
                                         affine,
                                         header,
                                         extra,
                                         file_map)
        # Force set of s/q form when header is None unless affine is also None
        if header is None and affine is not None:
            self._affine2header()
    # Copy docstring
    __init__.__doc__ = analyze.AnalyzeImage.__init__.__doc__ + '''
    .. note:: If both a ``header`` and an ``affine`` are specified, and the
              ``affine`` does not match the affine that is in the
              ``header``, the ``sform_code`` and ``qform_code`` fields in
              the header will be re-initialised - see the
              :meth:`set_sform` and :meth:`set_qform` methods.
    '''
```

If this looks ok I will open a PR with this, and also add a similar note to [The NIfTI affines](http://nipy.org/nibabel/nifti_images.html#the-nifti-affines) page.

**Comment by matthew-brett** [comment]
Yes, it certainly looks like an improvement.  Maybe also add that you can reset the codes with `set_sform` and `set_qform`?  And even something like "we reset the codes to their defaults on the basis that, if you are changing the affine, you are likely to be changing the space to which the affine is pointing" ?
