### ISSUE TITLE
Expat Error while parsing gifti file (.gii)

### ISSUE THREAD

**Issue by KamalakerDadi** [nipy/nibabel#581]
Hello Nibabel team,

I am trying to get some help in information about what is causing this failure ```xml.parsers.expat.ExpatError: no element found: line 1, column 0``` . The error occurred while we are trying to load surface mesh object fsaverage5 in .gii (attached).
[pial.left.gii.zip](https://github.com/nipy/nibabel/files/1474373/pial.left.gii.zip)

Full stack trace can be found [here](https://travis-ci.org/nilearn/nilearn/jobs/302221486#L3493). Error occurs in one of the travis environment in Nilearn project. I could not reproduce it on my laptop. Thanks a lot for your time & help.

**Comment by effigies** [comment]
I'm unable to reproduce this as well. Can you replicate the Travis environment more closely to try to track down the relevant configuration that's producing this? For instance, what is your expat version?

**Comment by KamalakerDadi** [comment]
>Can you replicate the Travis environment more closely to try to track down the relevant configuration that's producing this?

I am actually trying that without any success.

>For instance, what is your expat version?

If I doing correct, I checked my laptop's pyexpat==2.7.13

**Comment by KamalakerDadi** [comment]
I just did this.
```python
import xml.parsers.expat
In [11]: xml.parsers.expat.__version__
Out[11]: '$Revision: 17640 $'
```

**Comment by effigies** [comment]
I meant in the Travis container. Can you make a branch that will print out the expat version just before the call? Also, printing out the file size (or better, sha256sum) to make sure that you have a valid GIFTI inside the container might be a good idea.

**Comment by KamalakerDadi** [comment]
Sorry for the noise. Problem was on our side. Thanks a lot for your time.
