### ISSUE TITLE
Problem writing MGH image

### ISSUE THREAD

**Issue by billbrod** [nipy/nibabel#594]
I'm having an issue writing some MGH images to file. If my MGH file has one non-singleton dimension and three singleton dimensions (so its shape is something like `(120275, 1, 1, 1)`, I cannot write it to file, because I get a shape error when doing so (full traceback at the bottom of this post).

I don't have the issue if the MGH file has two singleton dimensions and two non-singleton dimensions (e.g., `(120275, 1, 1, 52)`). From poking around in `mghformat.py`, it seems like the problem is with `get_data_shape()` and `set_data_shape()`: `set_data_shape` specifies that an "MGH header always needs 4 dimensions", while `get_data_shape` drops the last dimension if it's 1, "because we want to maintain 3D". These two things contradict each other and it means that, when `get_data_shape` is checked during the process of saving the MGH image, it is different than the actual data shape and `set_data_shape` (which gets called during `update_header`) cannot be used to fix this.

This is all in nibabel version 2.2.1.

Functions:
```
    def get_data_shape(self):
        ''' Get shape of data
        '''
        dims = self._header_data['dims'][:]
        # If last dimension (nframes) is 1, remove it because
        # we want to maintain 3D and it's redundant
        if int(dims[-1]) == 1:
            dims = dims[:-1]
        return tuple(int(d) for d in dims)

    def set_data_shape(self, shape):
        ''' Set shape of data

        Parameters
        ----------
        shape : sequence
           sequence of integers specifying data array shape
        '''
        dims = self._header_data['dims']
        # If len(dims) is 3, add a dimension. MGH header always
        # needs 4 dimensions.
        if len(shape) == 3:
            shape = list(shape)
            shape.append(1)
            shape = tuple(shape)
        dims[:] = shape
        self._header_data['delta'][:] = 1.0
```

Traceback:
```
/home/wfb229/.conda/envs/sfp/lib/python2.7/site-packages/nibabel/filebasedimages.pyc in to_filename(self, filename)
    332         '''
    333         self.file_map = self.filespec_to_file_map(filename)
--> 334         self.to_file_map()
    335 
    336     @deprecate_with_version('to_filespec method is deprecated.\n'

/home/wfb229/.conda/envs/sfp/lib/python2.7/site-packages/nibabel/freesurfer/mghformat.pyc in to_file_map(self, file_map)
    579         with file_map['image'].get_prepare_fileobj('wb') as mghf:
    580             hdr.writehdr_to(mghf)
--> 581             self._write_data(mghf, data, hdr)
    582             self._write_footer(mghf, hdr)
    583         self._header = hdr

/home/wfb229/.conda/envs/sfp/lib/python2.7/site-packages/nibabel/freesurfer/mghformat.pyc in _write_data(self, mghfile, data, header)
    600         if data.shape != shape:
    601             raise HeaderDataError('Data should be shape (%s)' %
--> 602                                   ', '.join(str(s) for s in shape))
    603         offset = header.get_data_offset()
    604         out_dtype = header.get_data_dtype()

HeaderDataError: Data should be shape (120275, 1, 1)
```

**Comment by billbrod** [comment]
If I comment out the lines

```
        if int(dims[-1]) == 1:
            dims = dims[:-1]
```

in `get_data_shape()`, that fixes the issue for me and doesn't seem to break anything, but that seems really hacky. Should I open a pull request with it?

**Comment by effigies** [comment]
Feel free to open a PR, and include a test image that it fails on (it can be all zeroes). If you could write a quick test that loads and saves an image of this sort, that would be great, too.

That may not end up being the fix we go with, but at least with some test data, we can try to poke at the issue and make sure any alternatives work at least as well.

**Comment by billbrod** [comment]
Okay, so after spending some more time looking into this, it appears that this is actually a bug with my code. The problem wasn't with saving and loading 3D MGH images, it was saving a 3D MGH image that I had improperly created. Regardless of whether my data should have been 3D or 4D, I was making the input data object (to `nibabel.freesurfer.mghformat.MGHImage`) 4 dimensions, which was what was confusing `nibabel`. If I make sure the shape of my input data object is correct, the issue goes away.
