### ISSUE TITLE
DataobjImage doesn't proxy ndim

### ISSUE THREAD

**Issue by cancan101** [nipy/nibabel#595]
`DataobjImage` currently [proxies `shape`](https://github.com/nipy/nibabel/blob/6eacaf556c31c62f698ac07b4112245842d21f4e/nibabel/dataobj_images.py#L391-L393) but not [`ndim`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.ndim.html) even though various docs refer to `ndim(s)`: 
* http://nipy.org/nibabel/reference/nibabel.nifti1.html#nibabel.nifti1.Nifti1Header.set_data_shape
* http://nipy.org/nibabel/reference/nibabel.nifti2.html#nibabel.nifti2.Nifti2Header.set_data_shape

Might be useful to proxy `ndim` through.

**Comment by effigies** [comment]
Just to be clear, `ndims` is used in the context of those docstrings just as a stand-in for `len(shape)`, to explain the behavior of the methods.

That said, if people have a use-case for it, it doesn't seem unreasonable to add a property:

```Python
@property
def ndim(self):
    return len(self.shape)
```

Images that explicitly represent this value in the header could override the method to be a little less circuitous.

**Comment by matthew-brett** [comment]
I'd be OK with adding ndim to the proxy interface.   Would need that tested in the image API tests for all the various arrayproxies.  @cancan101 - would you consider doing a pull request?
