### ISSUE TITLE
List of all image/surface/data formats readable by Nibabel

### ISSUE THREAD

**Issue by raamana** [nipy/nibabel#596]
Did someone compile a list of all formats that can be read by Nibabel? Also writable list would be helpful too, as part of docs.

We can get a sense of this via API docs, but we could make it easier for a novice eye:
http://nipy.org/nibabel/api.html

From what I can tell, this seems to be the list:
 - Nifti
 - MGH/Freesurfer
 - MINC
 - Analyze
 - DICOM
 - PAR/REC
 - ECAT
 - TrackVis
 - Streamlines
 - gifti

So a small table with different columns noting whether nibabel can read or write it, and what versions etc might be helpful, it one doesn't exist already. Listing what is not supported, and what is coming up soon (like BRIK/HEAD) would be useful too.

**Comment by raamana** [comment]
Never mind, its right on the home page:
"This package provides read +/- write access to some common medical and neuroimaging file formats, including: ANALYZE (plain, SPM99, SPM2 and later), GIFTI, NIfTI1, NIfTI2, MINC1, MINC2, MGH and ECAT as well as Philips PAR/REC. We can read and write FreeSurfer geometry, annotation and morphometry files. There is some very limited support for DICOM. NiBabel is the successor of PyNIfTI."

I think it might be helpful to add it to manual/docs for sake of completeness.

**Comment by satra** [comment]
it should also say `CIFTI2` if it doesn't state it.

**Comment by raamana** [comment]
No, it doesn't seem to be mentioned, but I didn't look thoroughly enough.

**Comment by effigies** [comment]
I believe it's missing. It should probably also be promoted in the [file formats list](https://github.com/nipy/nibabel/blame/master/doc/source/api.rst#L32).
