### ISSUE TITLE
Pydicom 1.0.0 API breakage

### ISSUE THREAD

**Issue by effigies** [nipy/nibabel#598]
Looks like pydicom 1.0.0 is out, and there are some API breakages.

Searching for `tag_for_name` led to this PR, which outlines some changes: https://github.com/pydicom/pydicom/pull/517

Short term solution could be limit pydicom to <1.0. Alas, they don't seem to have had a pre-release cycle (or we just didn't run any tests during it).

**Comment by matthew-brett** [comment]
I'm confused - is pydicom 1.0 out? I can't see it on pypi...

**Comment by satra** [comment]
not yet - 1.0.0b1 was tagged 7 days ago.

**Comment by effigies** [comment]
They may have pulled it down from pypi, but it was up when I posted this.

**Comment by matthew-brett** [comment]
I've opened some issues on the failures, let's wait to see what happens before adapting to the new API:

https://github.com/pydicom/pydicom/issues/553
https://github.com/pydicom/pydicom/issues/554
https://github.com/pydicom/pydicom/issues/555

Chris - for the vanishing release, see: https://github.com/pydicom/pydicom/issues/553#issuecomment-366452904
