### ISSUE TITLE
Cannot work out file type of ".nii"

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [nipy/nibabel#620]
While this is a corner case, nibabel should properly load `.nii.` instead of raising an exception.
```
>>> import nibabel
>>> nibabel.load('.nii')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/nibabel/loadsave.py", line 49, in load
    filename)
nibabel.filebasedimages.ImageFileError: Cannot work out file type of ".nii"
```

**Comment by DimitriPapadopoulos** [comment]
This happens because _path_maybe_image()_ does not recognize `.nii` as a image file:
```
>>> import nibabel
>>> nibabel.filebasedimages.FileBasedImage.path_maybe_image('.nii')
(False, None)
```
and in turn that's because _splitext_addext()_ fails and outputs:
```
>>> nibabel.filename_parser.splitext_addext('.nii', ('.gz', '.bz2'))
('.nii', '', '')
```
instead of:
```
>>> nibabel.filename_parser.splitext_addext('.nii', ('.gz', '.bz2'))
('', '.nii', '')
```

**Comment by DimitriPapadopoulos** [comment]
And finally that's because _os.path.splitext()_ does not work as expected:
```
>>> os.path.splitext('.nii')
('.nii', '')
```
while you expect:
```
>>> os.path.splitext('.nii')
('', '.nii')
```

**Comment by effigies** [comment]
As a point of information, you can always load such a file with `nibabel.Nifti1Image.from_filename`. And just out of curiosity, under what circumstances are you finding a file without a name?

> And finally that's because os.path.splitext() does not work as expected:
> 
> ```
> >>> os.path.splitext('.nii')
> ('.nii', '')
> ```

This is what I would expect. Initial dots are [considered](https://docs.python.org/3/library/os.path.html#os.path.splitext) part of the filename, not an extension.

**Comment by DimitriPapadopoulos** [comment]
Happens with out put of `dcm2nii -d N -e N -p Y ` in some edge cases.

**Comment by DimitriPapadopoulos** [comment]
i know about the behavior of _os.path.splitext()_ but I claim this is not the behavior we need in this context.

**Comment by DimitriPapadopoulos** [comment]
On the other hand I can understand why you wouldn't want to deviate from the standard _os.path.splitext()_ behavior. However while I almost always agree with choices made in Python libraries, I find the choices made for _os.path.splitext()_ arbitrary - an optional argument would be welcome to switch behavior in edge cases depending on context.

**Comment by lanranranM** [comment]
> As a point of information, you can always load such a file with `nibabel.Nifti1Image.from_filename`. And just out of curiosity, under what circumstances are you finding a file without a name?
> 
> > And finally that's because os.path.splitext() does not work as expected:
> > ```
> > >>> os.path.splitext('.nii')
> > ('.nii', '')
> > ```
> 
> This is what I would expect. Initial dots are [considered](https://docs.python.org/3/library/os.path.html#os.path.splitext) part of the filename, not an extension.

Hello, I'm using nib.Nifti1Image.from_filename(file_path) to read the .nii.gz file. Referring another issue post, I renamed the file without .gz and the file_path without .gz. However, it's now rasing ```WrapStructError('Binary block is wrong size')
nibabel.wrapstruct.WrapStructError: Binary block is wrong size. ```How can I sove it?
