### ISSUE TITLE
Wrong when using function "nib.load"  to load "nii.gz" (can anyone help me check out )

### ISSUE THREAD

**Issue by chris1992212** [nipy/nibabel#626]
Code:
img_path = '1000_3.nii.gz'
img  = nib.load(img_path).get_data()

Error:
File "D:/DAGAN-master/data_loader.py", line 44, in <module>
    img = nib.load(img_path).get_data()
  File "D:\anaconda\lib\site-packages\nibabel\loadsave.py", line 45, in load
    return image_klass.from_filename(filename, **kwargs)
  File "D:\anaconda\lib\site-packages\nibabel\keywordonly.py", line 17, in wrapper
    return func(*args, **kwargs)
  File "D:\anaconda\lib\site-packages\nibabel\analyze.py", line 1001, in from_filename
    return klass.from_file_map(file_map, mmap=mmap)
  File "D:\anaconda\lib\site-packages\nibabel\keywordonly.py", line 17, in wrapper
    return func(*args, **kwargs)
  File "D:\anaconda\lib\site-packages\nibabel\analyze.py", line 971, in from_file_map
    img._affine = header.get_best_affine()
  File "D:\anaconda\lib\site-packages\nibabel\nifti1.py", line 731, in get_best_affine
    return self.get_qform()
  File "D:\anaconda\lib\site-packages\nibabel\nifti1.py", line 915, in get_qform
    quat = self.get_qform_quaternion()
  File "D:\anaconda\lib\site-packages\nibabel\nifti1.py", line 890, in get_qform_quaternion
    return fillpositive(bcd, self.quaternion_threshold)
  File "D:\anaconda\lib\site-packages\nibabel\quaternions.py", line 99, in fillpositive
    raise ValueError('w2 should be positive, but is %e' % w2)
ValueError: w2 should be positive, but is -6.401211e-07

**Comment by effigies** [comment]
Related: #625

**Comment by effigies** [comment]
As noted in #625, you can successfully load this file by using the following, before attempting to load the file:

```
nib.Nifti1Header.quaternion_threshold = -1e-06
```

As long as you save any derivative images with a valid `sform_code`, you should be able to keep the those images in the same space.

**Comment by ljdream0710** [comment]
Thank you so much

**Comment by daiyangolam** [comment]
import nibabel as nib
import numpy as np
import SimpleITK as sitk
import os
testf = open('test.txt', 'r')
test_dir = testf.readlines()
for i in range(int(len(test_dir)/5)):
    print i
    direct,_ = test_dir[5*i].split("\n")    
    # read the images and ground truth
    images0 = nib.load('./'+direct+'.gz').get_data()
    images0 = np.expand_dims(images0, axis=0)
        
    direct1,_ = test_dir[5*i + 1].split("\n")    
    # read the images and ground truth
    images1 = nib.load('./'+direct1+'.gz').get_data()
    images1 = np.expand_dims(images1, axis=0)
        
    direct2,_ = test_dir[5*i + 2].split("\n")    
    # read the images and ground truth
    images2 = nib.load('./'+direct2+'.gz').get_data()
    images2 = np.expand_dims(images2, axis=0)
        
    direct3,_ = test_dir[5*i + 3].split("\n")    
    # read the images and ground truth
    images3 = nib.load('./'+direct3+'.gz').get_data()
    images3 = np.expand_dims(images3, axis=0)
        
    images = np.concatenate((images0, images1, images2, images3), axis=0)
    
    image = np.max(images, axis=0)
    image = np.swapaxes(image, 0, 2)
    image[image>0] =1
    image = image.astype(dtype=np.uint8)
    if not os.path.exists(direct):
        os.makedirs(direct)
    image = sitk.GetImageFromArray(image)
sitk.WriteImage(image, direct + "/mask.nii.gz")
I am not getting mask

**Comment by matthew-brett** [comment]
You are saving with SimpleITK.   Can you give a simple reproducible example that just uses Nibabel?
