### ISSUE TITLE
How to get the axial, sagital and coronal view separately

### ISSUE THREAD

**Issue by mko010** [nipy/nibabel#628]
Hi guys,

I want to get the distinct views from .nii file, with Nibabel is it posible?

Thank you

**Comment by effigies** [comment]
Not directly, it would need matplotlib or some other viewer. Nilearn has very flexible [plotting](https://nilearn.github.io/plotting/index.html), and works smoothly with nibabel images.

**Comment by mko010** [comment]
Thank you, I will prove it

**Comment by Shuo-Han** [comment]
I have a function to use the nii affine to transform the image into axial (RAI minus), coronal (RSA minus), and sagittal (ASR minus) views. Is this something interesting to be included in nibabel? @effigies

**Comment by raamana** [comment]
hi @mko010, take a look at `mrivis` also: which provides a small utility function `get_axis` to access any view/slice number without worrying about syntax

There is another useful class called `SlicePicker` which can let you programmatically traverse through an MRI image in different views, and lets you sample slices in a variety of ways:
https://nbviewer.jupyter.org/github/raamana/mrivis/blob/master/docs/example_notebooks/mrivis_demo_Collage_SlicePicker_classes.ipynb
