### ISSUE TITLE
Update on click when OrthoSlicer is embed on PyQt5

### ISSUE THREAD

**Issue by mko010** [nipy/nibabel#629]
Hello,
Why the axes don't update when I the OrthoSilcer is on PyQt5?

Thank you.

**Comment by effigies** [comment]
Hi @mko010, again, sorry about the delayed response. Closing for the same reason as #613. If there's a bug we can fix, let us know, but we don't have the experience to support PyQt5 interactions. (At least I don't, and nobody seems to be jumping at this.)
