### ISSUE TITLE
ETA for next nibabel release?

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/nibabel#631]
Hi @matthew-brett, @effigies and all,

We were wondering when will be the next nibabel release.

We have some issue will loading "large" trk files with last release. The good news is that the fix is already in your master. The issue affects mostly nibabel and dipy windows users. Basically it takes literally for ever to load those files.

Merged PR here
https://github.com/nipy/nibabel/pull/597

**Comment by effigies** [comment]
Hi @Garyfallidis. I think we were thinking about a release a couple months back, but dropped the ball.

Just in terms of the current status, there are a couple open PRs that look ready or nearly ready to me:

* #550 (Submitter: @effigies; Reviewer: @matthew-brett)
* #561 (Submitter: @rmarkello; Reviewer: @matthew-brett)
* #614 (Submitter: @pauldmccarthy; Reviewer: @effigies @matthew-brett) 

I'm not sure how busy everybody is, what with PRNI and OHBM coming up, but it might be good to try to get these in if we have some spare cycles among us.

That said, there's already a pretty respectable changelog, and I can respect a desire not to delay any further. Are there any blocking issues?

In any event, I'll try to find some time to do some pre-release prep this week, and the question of any further updates can be resolved in parallel.

Related: #622

**Comment by Garyfallidis** [comment]
Thank you for your response @effigies It would be beneficial to have a release before OHBM. If that is possible for you guys. There will be some workshops using nibabel in OHBM. This bug affects all users but mostly windows users. We (meaning DIPY developers) are also working to release DIPY 0.15 before OHBM to accommodate the workshops.
