### ISSUE TITLE
AppVeyor deauthorized

### ISSUE THREAD

**Issue by effigies** [nipy/nibabel#633]
Can somebody with permissions to the AppVeyor group re-authorize its use for nibabel?

https://help.appveyor.com/discussions/problems/11287-the-build-phase-is-set-to-msbuild-mode-default-but-no-visual-studio-project-or-solution-files-were-found

**Comment by effigies** [comment]
https://github.com/nipy/nibabel/settings/hooks

**Comment by matthew-brett** [comment]
I just tried revoking and reauthorizing.  You don't have permission to do that?

**Comment by effigies** [comment]
Nope. I vaguely recall an email about this, but didn't know I'd ever need to muck about in there.

**Comment by effigies** [comment]
Doesn't seem to have resolved the issue.

https://ci.appveyor.com/project/nipy/nibabel/build/1.0.352

I guess if you're able to give me permissions, I can fiddle further.

**Comment by matthew-brett** [comment]
I've tried adding you specifically, as an Admin, invitation should be with you now.  I don't know if that's it ...

**Comment by effigies** [comment]
Oh, sorry. I do have GitHub permissions. Just not AppVeyor.

**Comment by effigies** [comment]
I can see in https://ci.appveyor.com/profile that I have "Restarter" permissions in one group I'm a collaborator in. Perhaps there's something that the `nipy` account can extend me?

**Comment by matthew-brett** [comment]
Chris - what email do you use with Appveyor?

**Comment by effigies** [comment]
This user @gmail

**Comment by matthew-brett** [comment]
OK - I gave you admin access to the Appveyor account that Eric Larson set up an age ago.

**Comment by effigies** [comment]
Got it. Thanks. Looks like @yarikoptic might have fixed the issue already, but I'll verify that it's fixed for me, too.

**Comment by effigies** [comment]
Looks like it's working. Thanks @matthew-brett and @yarikoptic.
