### ISSUE TITLE
nii file looks different after converting from REC 

### ISSUE THREAD

**Issue by Joshuaalbert** [nipy/nibabel#640]
Upon loading a REC file and then resaving it as a nii file, the image looks noisy. For other converted files, the converted nii looks fine. What do different nii image format versions do to the data before saving?

**Comment by matthew-brett** [comment]
Can you put your image somewhere for us to try doing what you did?

**Comment by effigies** [comment]
Hi @Joshuaalbert, if you can provide a file and code that reproduces the issue, please reopen.
