### ISSUE TITLE
GIFTI compression and Connectome Workbench

### ISSUE THREAD

**Issue by chrisgorgo** [nipy/nibabel#642]
I'm attempting to open gifti files created using nibabel in Connectome Workbench and I found that only the `ASCII` encoding mode works:
1. When using `B64GZ` I get 'Decompression of Binary data failed' error when reading the file (see https://github.com/Washington-University/workbench/blob/376691ce35697a0118a660bb5f116791eebba095/src/Gifti/GiftiDataArray.cxx#L709)
2. When using `B64BIN` I get funky looking images
![image](https://user-images.githubusercontent.com/238759/42120422-a0306382-7bcf-11e8-8c7a-846041672b94.png)

This could be an issue on the Connectome Workbench side.

**Comment by effigies** [comment]
Can you try viewing with FreeView or tksurfer? That should help distinguish between a nibabel writing issue and a Connectome Workbench reading issue.

**Comment by effigies** [comment]
@chrisfilo Any updates on this?

**Comment by effigies** [comment]
@chrisgorgo Please reopen if you can provide a reproducing file.
