### ISSUE TITLE
TIF (stack) input

### ISSUE THREAD

**Issue by TheChymera** [nipy/nibabel#645]
A number of molecular imaging devices (most prominently optoacoustics, e.g. MSOT, but also a number of optical imaging methods), have the capacity to output 3D stack recordings of the brain, but do so in TIF format.

What our lab currently does it convert those to NIfTI via [AFNI's `to3d`](https://afni.nimh.nih.gov/pub/dist/doc/program_help/to3d.html), and then take it from there. This is however rather an involved process, and of course comes with the additional dependency on AFNI, all of its deps, and its rather problemaic build system.

I was wondering if anybody else was thinking of maybe adding support for this in nibabel --- or if not, now I might elsewise best do this via the NiPy useland.

**Comment by effigies** [comment]
You may want to have a look at [scikit-image](http://scikit-image.org) for this.

**Comment by effigies** [comment]
Hey @TheChymera, were you able to come up with a solution?

**Comment by TheChymera** [comment]
@felixsc1 would you like to implement this? I could help you out a bit!

**Comment by effigies** [comment]
@TheChymera @felixsc1 If this is involved enough to warrant inclusion in nibabel, please reopen this issue and/or start a PR.

**Comment by felixsc1** [comment]
I thought about it, but the TIFF header doesn't include any information about the image orientation, not even the pixel size and thus the field-of-view.  Those would all have to be calculated manually anyways, thus I don't think it warrants a nibabel function.

**Comment by TheChymera** [comment]
Still, some functionality might be useful for this use case. At present the only option is really to code it yourself. The header could be parameterized, e.g. either via a manually specified affine matrix, or an affine matrix from an associated NIfTI file. Alternatively, if the affine matrix is deemed to complex (it's just 3x4, but some people don't understand it), you could just have `xy_dim` (optical sensors are isotropic) and `z_dim`, and construct the matrix internally like:

```
xy_dim 0 0 0
0 xy_dim 0 0
0 0 z_dim 0
```

I know this contains some hard-coding regarding the *position* in space, but this could just be the “light” version for when you don't plan to do any fancy registration and just want to embed the image resolution, if you want it to be 100% correct, there's no way around just specifying the affine.
