### ISSUE TITLE
How to check file to be read is a valid 4D image

### ISSUE THREAD

**Issue by raamana** [nipy/nibabel#648]
I'd like to ensure the image that is loaded (via nibabel) is a valid 4D image, which can easily be done with checking the length of shape (to be 4), the 4th dim is > 1 and image is not empty (all zeros). I am wondering if there is a little utility function within nibabel to do this?

**Comment by raamana** [comment]
I can easily write one myself.. but I am guessing there is some form of internal validation already, before returning the object.. And, that might be more efficient.

**Comment by effigies** [comment]
Hi Pradeep. I don't recall seeing a function like that in here. I'm not really sure that nibabel has situations where it requires an image to be 4D with final dimension >1. It mostly leaves those concerns to users.

**Comment by raamana** [comment]
Cool. I am not saying nibabel should impose constraints on the image shape/size, but having little helper functions to check validity of functional or diffusion MR images (they are 4D) would be helpful, as its a common/routine task. Something like `nibabel.is_epi_nonzero()` or `nibabel.is_dwi_nonzero()`

We can choose to leave this to the users, of course, but this may be helpful to catch subtle bugs.

**Comment by matthew-brett** [comment]
I guess you're asking for:

```
len(img.shape) > 3 and img.shape[3] > 1 and np.any(img.get_fdata())
```

?  Isn't it reasonable to ask the user to write that check if they need it?  The line isn't that much longer than `nibabel.is_epi_nonzero(img)`, and it's immediately clear from the line (but not the function name) what the check is doing.

**Comment by raamana** [comment]
I am suggesting this check might be a good candidate to add when its clear user intends to use 4D data, and expects them to be non-empty. This is almost always the case for me personally, I think there is merit in doing this check somewhere in the I/O process - I just don't know where would be ideal.

Perhaps this is not how nibabel intends to work, as I noticed only the header is read, and the image data is not even loaded by default. Perhaps *this could be a warning from* `nib.get_data()` when it notices empty image (not on disk, but zeros all over in image).

**Comment by matthew-brett** [comment]
I don't think the check should be in the load process - sometimes all zero images are intended, and we often intend to load 4D images where the img.shape[3] == 1.    So I think the best solution is the check above, after the image has been loaded.  If you use it all the time, you could put it in a function.

**Comment by raamana** [comment]
Sure, I already have it set up for my various libraries, so just trying to see if this might be relevant for others too.

I'm curious to learn when all zero images are intended?

**Comment by raamana** [comment]
They seem to be rather rare, if not exceptionally rare cases. Its not really a mask if there isn't atleast one non-zero voxel, right?

Empty test images for testing are constructed on the fly, not read from disk, right? I see their need to ensure algo implementations aren't doing stupid things. Even if they are read from disk e.g. to test CLI program, a warning from `nib.load()` would be appropriate in testing (and harmless), as well as being very helpful in real use (as they are not expected).
