### ISSUE TITLE
Gauging interest on spatial transforms

### ISSUE THREAD

**Issue by oesteban** [nipy/nibabel#654]
I'm about to start working on python (mostly numpy) based geometric transformation of 3D images. I feel nibabel could be the best host to a new module `nibabel.transforms`.

I would start by implementing affine transforms (which is almost there already with `resample_from_to`) and free-deformation fields (e.g. generated by ANTs registration).

Next steps would include taking in collapsed transforms (hdf5), and also parametric transforms (e.g. BSpline).

WDYT?

**Comment by effigies** [comment]
This looks useful. I've done some work already with FreeSurfer's LTA format in #565.

So a `Transform` is defined to be RAS-RAS?

**Comment by oesteban** [comment]
#565 is definitely related to this.

In principle, Transforms are Voxel-to-voxel. However, they must have an internal parameterization of the transform. That internal model should be defined to be RAS-RAS and accessible through the `map_point` method.
