### ISSUE TITLE
BUG: read_annot changed values

### ISSUE THREAD

**Issue by larsoner** [nipy/nibabel#663]
Three things have changed when using `read_annot` from 2.2.2 to `master`, presumably from #592:

1. An entry of `cmap` with large ID 16777215 has changed to -1 
2. The third column entries have changed from 255 to 0
3. The `cmap.dtype` has changed from `int64` to `int32` (probably not a big deal)

To see these, look at [this annot](https://ndownloader.figshare.com/files/5528816) and do:
```
import nibabel as nib
labels, ctab, names = nib.freesurfer.read_annot('lh.HCPMMP1.annot')
print(ctab[:3])
```
On 2.2.2 you get:
```
[[     255      255      255      255 16777215]
 [      63        5      255      255 16713023]
 [      54      103      129      255  8480566]]
```
On `master` you get:
```

  File "/Users/larsoner/python/nibabel/nibabel/freesurfer/io.py", line 393, in read_annot
    labels[mask] = ord[np.searchsorted(ctab[ord, -1], labels[mask])]

IndexError: index 181 is out of bounds for axis 1 with size 181
```
But inspecting what's going on you can see:
```
ipdb> p ctab[:3]
array([[     255,      255,      255,      255,       -1],
       [      63,        5,      255,        0, 16713023],
       [      54,      103,      129,        0,  8480566]], dtype=int32)
```
i.e., the first label's ID has become negative, and the other third column values have been changed from 255 to 0.

If I do the same thing with `fsaverage/label/lh.aparc.annot`, the file reads without error, but the third column has changed from being all 255 in 2.2.x to all 0 in `master`.

@pauldmccarthy were these changes intended? I assume that the `alpha` / third-column value changes were. And as for the `-1` label, maybe the figshare `annot` is wacky somehow?

**Comment by christianbrodbeck** [comment]
cf. https://github.com/nipy/nibabel/issues/649

**Comment by larsoner** [comment]
Yes probably a dup of #649
