### ISSUE TITLE
Disable crosshairs OrthoSlicer3D

### ISSUE THREAD

**Issue by mko010** [nipy/nibabel#689]
Hello, how I can disable the crosshairs of Orthoslicer3D?

thank you.

**Comment by effigies** [comment]
In the short term, you can comment out these lines:

https://github.com/nipy/nibabel/blob/118d305bd86a83c238ebb8af968bc475e2626ec8/nibabel/viewers.py#L501-L502

If you'd like to submit a pull request, you could add a `_show_crosshairs` instance variable that's togglable with a keypress in

https://github.com/nipy/nibabel/blob/118d305bd86a83c238ebb8af968bc475e2626ec8/nibabel/viewers.py#L479-L492

that you could use to selectively deactivate the above lines.

**Comment by mko010** [comment]
Thank you a lot Chris, and it's possible hold the three views for select some points?

Thak you.

El mar., 6 nov. 2018 19:53, Chris Markiewicz <notifications@github.com<mailto:notifications@github.com>> escribió:

In the short term, you can comment out these lines:

https://github.com/nipy/nibabel/blob/118d305bd86a83c238ebb8af968bc475e2626ec8/nibabel/viewers.py#L501-L502

If you'd like to submit a pull request, you could add a _show_crosshairs instance variable that's togglable with a keypress in

https://github.com/nipy/nibabel/blob/118d305bd86a83c238ebb8af968bc475e2626ec8/nibabel/viewers.py#L479-L492

that you could use to selectively deactivate the above lines.

**Comment by effigies** [comment]
I'm sorry, I don't understand the question.

**Comment by mko010** [comment]
Sorry for the explanation, I want hold the three views, when I click some view, don't update other views. I want that for plotter some points in axes.

Thank you.
________________________________
De: Chris Markiewicz <notifications@github.com>
Enviado: martes, 6 de noviembre de 2018 22:00
Para: nipy/nibabel
Cc: mko010; Author
Asunto: Re: [nipy/nibabel] Disable crosshairs OrthoSlicer3D (#689)


I'm sorry, I don't understand the question.

**Comment by mko010** [comment]
I know, I'm trying do that, and I've realized that it's not possible show a RGB channel, I'm trying do that too.

El mié., 7 nov. 2018 15:27, Chris Markiewicz <notifications@github.com<mailto:notifications@github.com>> escribió:

I think freezing some views will require a more significant change. I'm not immediately sure of how I'd go about that.
