### ISSUE TITLE
No module named bz2file

### ISSUE THREAD

**Issue by skoudoro** [nipy/nibabel#710]
Hi,

Since the last release (2.3.2). I received the error message below. You can see the complete Travis log [here](https://travis-ci.org/fury-gl/fury/jobs/475087904#L3192).  I can not reproduce this error with pip, it is only with Miniconda. it seems related to bz2file version.

```
fury/tests/test_actors.py:16: in <module>
    from dipy.tracking.streamline import (center_streamlines,
../../../envs/miniconda/envs/testenv/lib/python2.7/site-packages/dipy/tracking/__init__.py:4: in <module>
    from nibabel.streamlines import ArraySequence as Streamlines
../../../envs/miniconda/envs/testenv/lib/python2.7/site-packages/nibabel/__init__.py:38: in <module>
    from . import analyze as ana
../../../envs/miniconda/envs/testenv/lib/python2.7/site-packages/nibabel/analyze.py:87: in <module>
    from .volumeutils import (native_code, swapped_code, make_dt_codes,
../../../envs/miniconda/envs/testenv/lib/python2.7/site-packages/nibabel/volumeutils.py:23: in <module>
    from .openers import Opener, BZ2File
../../../envs/miniconda/envs/testenv/lib/python2.7/site-packages/nibabel/openers.py:14: in <module>
    from bz2file import BZ2File
E   ImportError: No module named bz2file
```

environment: Python 2.7 - Miniconda - nibabel 2.3.2

**Comment by skoudoro** [comment]
The change was introduced on commit c79a29112dc42815946b142e34d4beabf8804d98

**Comment by matthew-brett** [comment]
Chris - I see there is a conda-forge project for nibabel - I guess it isn't picking up the new requirement?

Do we need a conda-forge project?  Isn't pip enough, for installs within conda?

**Comment by effigies** [comment]
Oh, yes, I'll update the conda-forge. One reason to have a conda-forge project is to allow for downstream conda packages that depend on nibabel. I don't think it's possible for a conda package to have a pip dependency.

**Comment by matthew-brett** [comment]
That sounds like a good reason.

**Comment by effigies** [comment]
Latest conda builds should be fixed. Please reopen if the problem persists.

**Comment by skoudoro** [comment]
Works like a charm! Thank you Chris!
