### ISSUE TITLE
Nibabel does not "pip install" with six

### ISSUE THREAD

**Issue by GaelVaroquaux** [nipy/nibabel#713]
pip installing nibabel under python2 installs a non working nibabel because of missing six in the requirements. As a result, the CI is broken on nilearn:
https://github.com/nilearn/nilearn/issues/1900

# Steps to reproduce:

1. Create a clean python2.7 virtualenv
2. "pip install nibabel"
3. Try importing nibabel

Results in
```
  File "/home/varoquau/tmp/clean_venv/local/lib/python2.7/site-packages/nibabel/testing/__init__.py", line 29, in <module>
    from six.moves import zip_longest
ImportError: No module named six.moves
```

**Comment by effigies** [comment]
Ah, thanks for tracking this down. I suspect this happened because of the switch to `setuptools` from `distutils`.

**Comment by GaelVaroquaux** [comment]
Thank you so much for being that fast in addressing this issue. I am impressed.
