### ISSUE TITLE
nifti dim_info transformation after orientation

### ISSUE THREAD

**Issue by constracti** [nipy/nibabel#716]
Running the test
```python
import numpy as np
import nibabel as nib

data = np.arange(24).reshape((2,3,4))
img = nib.Nifti1Image(data, np.eye(4))
img.header.set_dim_info(1, 0, 2)

ornt = np.array([[2, 1], [0, 1], [1, 1]])
img_ornt = img.as_reoriented(ornt)
print(ornt[:,0])
print(img.shape)
print(img_ornt.shape)
print(img.header.get_dim_info())
print(img_ornt.header.get_dim_info())
```
we get
```python
[2 0 1]
(2, 3, 4)
(3, 4, 2)
(1, 0, 2)
(1, 2, 0)
```
although (if I'm not wrong) the correct output should look like
```python
[2 0 1]
(2, 3, 4)
(3, 4, 2)
(1, 0, 2)
(0, 2, 1)
```
(note the difference in the last line).

Shouldn't the following
https://github.com/nipy/nibabel/blob/5ab94146d569dc905bfbbb5b7a4ae4b190bbd133/nibabel/nifti1.py#L2023
be `new_dim[idx] = ornt[value, 0]`?

[In which case, it would be better to ensure that value has an integer data type; however, `io_orienatation` returns a float array.]

**Comment by effigies** [comment]
That looks correct... Would you be willing to submit a test that makes sure dim_info is correctly permuted, and then your proposed fix?

**Comment by constracti** [comment]
I hope I'll be able to handle it in the following days.

**Comment by constracti** [comment]
I haven't understood, do you agree with my point?
In my example, should `img_ornt.header.get_dim_info()` return `(0, 2, 1)`?
I'm asking to make sure that I have completely comprehended the definition (i.e. the operation) of `ornt`.

**Comment by effigies** [comment]
Sorry, yes. I think you're right. I'm having some trouble thinking through the orientations, myself. I'll fix up the tests, and then test out your fix to make sure that it resolves them.
