### ISSUE TITLE
nibabel equivalent of spm_check_orientations?

### ISSUE THREAD

**Issue by jooh** [nipy/nibabel#721]
In Matlab, I use [spm_check_orientations](https://github.com/spm/spm12/blob/master/spm_check_orientations.m) to confirm that two niftis have similar affines and identical image dimensions before running array-based operations (e.g. masking one image by the other). Does nibabel have anything comparable?

**Comment by effigies** [comment]
Not that I know of, but it would be easy to write:

```Python
import numpy as np

def check_orientations(img1, img2, rtol=1e-05, atol=1e-08):
    return img1.shape == img2.shape and np.allclose(img1.affine, img2.affine,
                                                    rtol=rtol, atol=atol)
```

The `rtol` and `atol` would allow you to modulate how similar you need your affines to be. See the [numpy.allclose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.allclose.html) documentation for the exact semantics.

**Comment by jooh** [comment]
Thanks!
