### ISSUE TITLE
Minor bug checking versions

### ISSUE THREAD

**Issue by oesteban** [nipy/nibabel#723]
```Python
>>> from nibabel.info import cmp_pkg_version
>>> cmp_pkg_version('1.2.0+7', '1.2.0')
-1
```
(should be 1)

Happens with versions generated by versioneer that count the number of commits you diverged from latest tag.

**Comment by effigies** [comment]
@oesteban There's a deeper problem than PEP440 support, here. I think we should look into pulling this machinery out into a small, separate package. See bids-standard/pybids#406.
