### ISSUE TITLE
Address DeprecationWarning from numpy.testing.decorators

### ISSUE THREAD

**Issue by topspinj** [nipy/nibabel#725]
numpy.testing.decorators is deprecated. Getting this warning:
```
DeprecationWarning: Importing from numpy.testing.decorators is deprecated, import from numpy.testing instead.
```
This issue can be resolved by replace numpy.testing.decorators with numpy.testing.

**Comment by effigies** [comment]
Thanks for the report. This was addressed in #705 and will be part of the next release.
