### ISSUE TITLE
scl_slope/scl_inter

### ISSUE THREAD

**Issue by tashrifbillah** [nipy/nibabel#737]
If an image is of relative intensity does Nibabel ignore scl_slope/scl_inter when reporting the data? In other words, where can I see the code for it?

PS. did a `grep`, but don't see any such condition. Rather it looks like, Nibabel always scales data 
> if scl_slope!=1 and scl_inter!=0

**Comment by effigies** [comment]
I'm not sure what you mean by "relative intensity" in this context. If `scl_slope` and `scl_inter` are defined, they will be applied. You can use `img.dataobj.get_unscaled()` to retrieve the unscaled data.
