### ISSUE TITLE
Confusion about negative number shows  when dealing with nii format

### ISSUE THREAD

**Issue by yaoyao14** [nipy/nibabel#748]
I'm a freshman in this area
I use get_fdata() function for my iamge in nii format, then transform it into numpy.array()
then I found values in this array are all  about -25~-20, then I calculate mean and std of it, but the mean is about  20. It's strange,and I don't know the reason.
I have two questions. The first one, is it reasonable that values are negative ? 
The second one is why when values are negative but mean of them is positive ? 
Is something wrong here? If so,please tell me, thank you so much !

**Comment by effigies** [comment]
Just so you know, that sequence of steps is not necessary. The output of `get_fdata()` is a numpy array that you can use directly.

```Python
img = nibabel.load(file_name)
data = img.get_fdata()
```

Additionally, your approach will add an extra axis to the front of the array.

```Python
>>> data.shape
(64, 64, 40)
>>> np.array([data]).shape
(1, 64, 64, 40)
```

Also, I just realized I didn't answer you: There's no reason in principle that an image shouldn't have negative values, but there may be situations where it seems inappropriate. What type of image are you looking at?

**Comment by yaoyao14** [comment]
> Just so you know, that sequence of steps is not necessary. The output of `get_fdata()` is a numpy array that you can use directly.
> 
> ```python
> img = nibabel.load(file_name)
> data = img.get_fdata()
> ```
> 
> Additionally, your approach will add an extra axis to the front of the array.
> 
> ```python
> >>> data.shape
> (64, 64, 40)
> >>> np.array([data]).shape
> (1, 64, 64, 40)
> ```
> 
> Also, I just realized I didn't answer you: There's no reason in principle that an image shouldn't have negative values, but there may be situations where it seems inappropriate. What type of image are you looking at?

I’m using nibabel to deal with iamges in nii format,about brain ischemic stroke.

**Comment by matthew-brett** [comment]
I think @effigies was asking for the modality of the images (blood flow, PET, MRI etc).

Some images do have negative values, especially those that have had some processing applied.

As @effigies implied, you'll get the overall mean of the image data from:

```
data = img.get_fdata()
np.mean(data)
```

**Comment by effigies** [comment]
Thanks Matthew, and sorry for the imprecision.

**Comment by effigies** [comment]
Closing. Please reopen if there's still an issue to address.
