### ISSUE TITLE
Broken link in docstring

### ISSUE THREAD

**Issue by arokem** [nipy/nibabel#757]
This link is now broken:

https://github.com/nipy/nibabel/blob/master/nibabel/freesurfer/mghformat.py#L255

They must've moved that page elsewhere.

**Comment by effigies** [comment]
Works for me... https://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/MghFormat#line-82

**Comment by effigies** [comment]
Still up, so I don't think it was a caching issue. @arokem are you still seeing a problem?
