### ISSUE TITLE
to_filename() does not store header changes in .dlabel.nii

### ISSUE THREAD

**Issue by javzapata** [nipy/nibabel#758]
Hi,

I'm trying to open a .dlabel.nii file, modify its header and save it to a new .dlabel.nii file. However the **to_filename()** from the **FileBasedImage** class in the **nibabel** does not work. When I open the new file I don't see any changes in the header.

Here is an example code. Any help would be really appreciated. The label file used in the example below can be downloaded from: https://balsa.wustl.edu/study/show/RVVG

```Python
import numpy as np
import nibabel.cifti2 as ci

myLabelTable = ci.Cifti2LabelTable()
myLabelTable.append(ci.Cifti2Label(key=0, label='0', red=1.0, green=1.0, blue=1.0, alpha=0.0))
for i in np.arange(0,360):
    myLabelTable.append(ci.Cifti2Label(key=i+1, label=str(i+1), red=0.5, green=0.5, blue=0.5, alpha=1.0))


labelFile = "Q1-Q6_RelatedParcellation210.CorticalAreas_dil_Final_Final_Areas_Group_Colors.32k_fs_LR.dlabel.nii"

img = ci.Cifti2Image.from_filename(labelFile)
img.header.matrix._mims[0]._maps[0]._label_table=myLabelTable
img.update_headers()
img.to_filename('newLabels.dlabel.nii')
```

**Comment by effigies** [comment]
Modifying hidden variables seems like it's working around the intended API, so it's possible that there are some update steps that aren't getting created properly. @MichielCottaar does your recent Axes work make the intended operation here easier?

**Comment by MichielCottaar** [comment]
Sure, you can find the documentation on the Axes interface with CIFTI files [here](https://nipy.org/nibabel/reference/nibabel.cifti2.html#module-nibabel.cifti2.cifti2_axes) . The code for this would be:
```
import numpy as np
import nibabel.cifti2 as ci

# defining new labels
new_labels = {0: ('0', (1., 1., 1., 0.))}
for i in np.arange(0, 360):
    new_labels[i+1] = (str(i + 1), (0.5, 0.5, 0.5, 1.))

labelFile = "Q1-Q6_RelatedParcellation210.CorticalAreas_dil_Final_Final_Ar
img = ci.Cifti2Image.from_filename(labelFile)

# extracting the Axis describing the labels (i.e., along the first dimension)
label_axis = img.header.get_axis(0)
# updating the labels for the first (in this case only) column
label_axis.label[0] = new_labels

# We create a completely new header with our new labels across the first axis and the original brain model with the vertices across the other axis.
new_header = ci.Cifti2Header.from_axes((label_axis, img.header.get_axis(1)))

# I think we could also update the header on the old image, but I prefer to create new ones
new_img = ci.Cifti2Image(img.get_fdata(), header=new_header)
new_img.to_filename('newLabels.dlabel.nii')
```

Note that in the Axes interface labels are represented as a dictionary from keys to a tuple with label name and RGBA colour.

**Comment by javzapata** [comment]
That works wonderfully! Thank you @effigies and @MichielCottaar !
