### ISSUE TITLE
Taking hours to parse a nifti file

### ISSUE THREAD

**Issue by srinivasaravind5** [nipy/nibabel#765]
Hi, I am trying to parse and get data from a nifti file.

```
import numpy as np
import nibabel as nib

file_path = '/home/aravind/Desktop/dicom-test/filtered_func_data.nii'
img = nib.load(file_path).get_data()

print(img)
```

I waited for more than 10 minutes the terminal was still running.

**Comment by matthew-brett** [comment]
Yes, this can happen when your file is large and you don't have much memory.

If you don't need the whole image in memory at once, you can try getting the slices you need out of the underlying data object - see https://nipy.org/nibabel/images_and_memory.html - particularly the last section.

**Comment by srinivasaravind5** [comment]
File size is 78 kb

**Comment by matthew-brett** [comment]
Then there's something wrong - can you post your file somewhere we can take a look?

**Comment by srinivasaravind5** [comment]
https://s3.ap-south-1.amazonaws.com/dicom-viewer-backend-dev/dicom_viewer/media/zstat1.nii.gz

> Then there's something wrong - can you post your file somewhere we can take a look?

**Comment by srinivasaravind5** [comment]
https://s3.ap-south-1.amazonaws.com/dicom-viewer-backend-dev/dicom_viewer/media/zstat1.nii.gz

> Then there's something wrong - can you post your file somewhere we can take a look?

**Comment by srinivasaravind5** [comment]
> Yes, this can happen when your file is large and you don't have much memory.
> 
> If you don't need the whole image in memory at once, you can try getting the slices you need out of the underlying data object - see https://nipy.org/nibabel/images_and_memory.html - particularly the last section.

Can you share any sample working file

**Comment by matthew-brett** [comment]
On my laptop:

```
$ time python -c "import nibabel as nib; data = nib.load('zstat1.nii.gz').get_data()"

real	0m0.695s
user	0m0.537s
sys	0m0.162s
```

Is there anything strange about your setup?   Do other files load faster?   Is your disk corrupt?

**Comment by srinivasaravind5** [comment]
No files are loading

**Comment by matthew-brett** [comment]
What do you get for:

```
$ time python -c "with open('zstat1.nii.gz', 'rb') as fobj: content = fobj.read()"
```

?

**Comment by srinivasaravind5** [comment]
time python -c "with open('zstat1.nii.gz', 'rb') as fobj: content = fobj.read()"

real    0m0.036s
user    0m0.024s
sys     0m0.012s

**Comment by srinivasaravind5** [comment]
> On my laptop:
> 
> ```
> $ time python -c "import nibabel as nib; data = nib.load('zstat1.nii.gz').get_data()"
> 
> real	0m0.695s
> user	0m0.537s
> sys	0m0.162s
> ```
> 
> Is there anything strange about your setup? Do other files load faster? Is your disk corrupt?

Tried this its infinitely running

**Comment by matthew-brett** [comment]
How about:

```
$ time python -c "import gzip; fobj = open('zstat1.nii.gz', 'rb'); content = fobj.read()"
```

?

Try unzipping the file:

```
$ gunzip zstat1.nii.gz
$ time python -c "import nibabel as nib; data = nib.load('zstat1.nii').get_data()"
```

**Comment by srinivasaravind5** [comment]
> How about:
> 
> ```
> $ time python -c "import gzip; fobj = open('zstat1.nii.gz', 'rb'); content = fobj.read()"
> ```
> 
> ?
> 
> Try unzipping the file:
> 
> ```
> $ gunzip zstat1.nii.gz
> $ time python -c "import nibabel as nib; data = nib.load('zstat1.nii').get_data()"
> ```

Tried that as well same result

**Comment by matthew-brett** [comment]
Run the `... get_data()` command in IPython, press Ctrl-C after a few seconds, while it's hanging.  What stack trace do you get?

**Comment by srinivasaravind5** [comment]
I commented the get data

**Comment by srinivasaravind5** [comment]
I have another file with pydicom in the same directory I deleted the file and the issue was resolved

**Comment by effigies** [comment]
Hi, can you give more details about your image and available system memory? You use `print(nib.load(file_path).header)` to give details about your image.

**Comment by effigies** [comment]
Oh, sorry, somehow missed the entire convo on my app.
