### ISSUE TITLE
Some Nifty images are not parsed properly

### ISSUE THREAD

**Issue by srinivasaravind5** [nipy/nibabel#766]
Hi
I am using nibabel to get the data from a nifti file and plot them using matplotlib.

When I do so, for some file it fails and the result is wrong. I verified the results with the ITKSnap which can view nifti files.

```
import numpy as np
import nibabel as nib
import matplotlib.pyplot as plt


def save_images_to_local(pix, img_name):
    plt.imshow(pix, cmap=plt.cm.bone)
    plt.axis('off')
    plt.savefig(img_name)
    plt.cla()
    return


file_path = '/home/aravind/Desktop/dicom-test/zstat1.nii.gz'
ds = nib.load(file_path).get_data()

random_number = "100"
i = 0
list_of_image_frames = []

for pix in ds:
    img_name = "media/" + random_number + str(i) + ".png"
    list_of_image_frames.append({'pix':pix, 'img_name':img_name})
    i += 1

for image_frame in list_of_image_frames:
    save_images_to_local(image_frame['pix'], image_frame['img_name'])

```

For this file zstat1.nii.gz it works, for 21.nii.gz the results are wrong.
Public URLs for the files
https://s3.ap-south-1.amazonaws.com/dicom-viewer-backend-dev/dicom_viewer/media/zstat1.nii.gz
https://s3.ap-south-1.amazonaws.com/dicom-viewer-backend-dev/dicom_viewer/media/21.nii.gz

**Comment by matthew-brett** [comment]
We need more detail on why you think the results are wrong.  Can you replicate without using multiprocessing?

**Comment by srinivasaravind5** [comment]
> We need more detail on why you think the results are wrong. Can you replicate without using multiprocessing?

Removed multiprocessing

The plotted images are not the same as the one which is generated from the ITKSnap

**Comment by matthew-brett** [comment]
Why do you think that ITKSnap is correct?

**Comment by srinivasaravind5** [comment]
> Why do you think that ITKSnap is correct?

Is able to parse almost all the images and widely used.

Try parsing the https://s3.ap-south-1.amazonaws.com/dicom-viewer-backend-dev/dicom_viewer/media/21.nii.gz from the result, if you look at the image it's simply blank and some irrelevant data, nothing corresponding to what is expected. If you look at it you will understand

**Comment by srinivasaravind5** [comment]
> We need more detail on why you think the results are wrong. Can you replicate without using multiprocessing?

Do you want me to share the results?

**Comment by matthew-brett** [comment]
I don't know ITKSnap, I'm afraid.   I get a sensible looking image of what looks like a phantom out of:

```
import matplotlib.pyplot as plt
img = nib.load('21.nii.gz') 
plt.imshow(img.get_fdata()[:, :, 15]) 
```

**Comment by effigies** [comment]
@srinivasaravind5 Could you try posting pictures of what you see from ITKSnap and the corresponding view that you're getting from nibabel+matplotlib? I took a look at this image and it looks the same in nibabel and FreeView.

<img width="1792" alt="Screen Shot 2019-05-28 at 09 05 17" src="https://user-images.githubusercontent.com/83442/58480164-bdd3e900-8127-11e9-82cd-943403774545.png">

If by "it's simply blank and some irrelevant data, nothing corresponding to what is expected" you mean it doesn't look like a brain, I agree. It looks like synthetic data, and I don't think the tool is going to make much difference.

**Comment by effigies** [comment]
@srinivasaravind5 Has this been resolved, or are there still open questions?

**Comment by srinivasaravind5** [comment]
Hey

its not plotting anything where I iterate like this

`for pix in ds:
    img_name = "media/" + random_number + str(i) + ".png"
    list_of_image_frames.append({'pix':pix, 'img_name':img_name})
    i += 1`

`img = nib.load('21.nii.gz') 

for i in range (0, 15):
plt.imshow(img.get_fdata()[:, :, i]) `

This works
