### ISSUE TITLE
How to supress warnings when reading dscalar CIFTI2 images from HCP?

### ISSUE THREAD

**Issue by ellisdg** [nipy/nibabel#771]
Whenever I open a CIFTI2 dscalar file from the Human Connectome Project, the following message is printed to the terminal:
```
pixdim[1,2,3] should be non-zero; setting 0 dims to 1
```
Is there a way to suppress this message so that I don't have to see it every time?
I am using nibabel 2.4.0.

**Comment by effigies** [comment]
You'll want to set the logging level to > 30.

```Python
import nibabel as nib
nib.imageglobals.logger.level = 40
```

See https://nipy.org/nibabel/reference/nibabel.imageglobals.html#module-nibabel.imageglobals for details.

**Comment by effigies** [comment]
Hi @ellisdg, did this resolve your issue?

**Comment by effigies** [comment]
Hi @ellisdg I'm closing this, but please reopen if this didn't resolve your problem.

**Comment by sina-mansour** [comment]
The solution above didn't work for me, but this alternative did:

```python3
import nibabel as nib
nib.imageglobals.logger.setLevel(40)
```
