### ISSUE TITLE
Checking shape of CIFTI2 images

### ISSUE THREAD

**Issue by MichielCottaar** [nipy/nibabel#773]
At present there is no checking of whether the shape of the data array is consistent with the CIFTI2 header. In the example below, I expect two numbers (A and B) for each of my three vertices on the left cortex, so a (2, 3)-shaped array. However, nibabel will happily accept the (7,4)-shaped array provided here. Similarly, when reading the CIFTI file no errors or warnings are raised.

```
from nibabel import cifti2
import numpy as np
data = np.random.rand(7, 4)
bm = cifti2.BrainModelAxis.from_mask([True, True, True], name='left_cortex')
sc = cifti2.ScalarAxis(['A', 'B'])
img = cifti2.Cifti2Image(data, header=(sc, bm))
img.to_filename('test.dscalar.nii')
```

I'm happy to implement some code to compare the shape of the array with that implied by the header, but I'm not sure what would be the best time to make this check and whether it should be a warning or an error. The options are:
1. warning or error when creating the Cifti2Image itself
2. warning or error when writing the Cifti2Image
3. warning or error when reading the Cifti2Image

Any suggestions on where to plug this test and whether to make it a warning or an error? We can't simply adjust the header shape to match the data as this would involve creating new labels for the rows or columns and hence would lead to very confusing behaviour.

**Comment by effigies** [comment]
My personal inclination is to be strict on write, forgiving on read, which allows users to use nibabel to fix bad files while hopefully avoiding polluting the ecosystem with bad CIFTI-2 files that others have to deal with.

Do you know what the HCP folks do with inconsistencies?

We do also have a notion of consistency/validity checks that seem reasonable to extend for cases like this:

https://github.com/nipy/nibabel/blob/0282bb957f990100aaf39d19bd3e9c7606b4fe6d/nibabel/nifti1.py#L1656-L1744

If that doesn't fit, I've also been thinking about adding a `ConsistencyWarning` for other situations (#624) where we have a strictly legal but questionably valid file.

**Comment by MichielCottaar** [comment]
Thanks, that makes sense. I'll put something together soon. The HCP workbench viewer simply raises an error when the header file does not match (which is how I realized that I was writing CIFTI files with the wrong shape). I have not tested their command line tools, but I would expect the same behavior.
