### ISSUE TITLE
ECAT file support

### ISSUE THREAD

**Issue by idoimaging** [nipy/nibabel#776]
Currently, `EcatImage` is not included in `all_image_classes` in `imageclasses.py`.  Adding it and calling `load()` on an ECAT file gives an error in `ecat.py` line 562:

            i = iter(affs)
            first = i.next()

Changing the second line to the Python 3 syntax `first = next(i)` seems to address this issue, but there may be other Python 2 code in the `EcatImage` class.

**Comment by effigies** [comment]
There are some open issues for adding `EcatImage` to `nibabel.load`: #95 / [BIAP7](https://github.com/nipy/nibabel/wiki/BIAP7)

I believe the current way to load is:

```Python
import nibabel
nibabel.ecat.load(fname)
```

So it looks like the issue here is that we're [never testing](https://codecov.io/gh/nipy/nibabel/src/b356a64e74d12f2c1dddfd9630fe835c48937f76/nibabel/ecat.py#L559...566) this code. I wonder if you have a multi-frame ecat of a phantom that we could add to our test battery.

I'll open a pull request with your suggested fix.

**Comment by effigies** [comment]
Actually, since you found this issue, would you care to submit a pull request?

**Comment by idoimaging** [comment]
OK, I'll get on to both of those.

**Comment by idoimaging** [comment]
I have plenty of multi-frame Ecat phantom images but they are all 27 MB per frame.  Here's one: https://www.dropbox.com/s/nh3d2vyijkf69td/ecat_03fr.v?dl=0

**Comment by effigies** [comment]
Thanks. We may be able to reduce the size a bit one way or another. If not, we have some repositories of large test files we can add it to.

**Comment by effigies** [comment]
@idoimaging Do you have any opposition to releasing that image to the public domain (e.g., by the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/))? Or perhaps some other license? I'm considering adding it to [nipy-ecattest](https://github.com/freec84/nipy-ecattest), which currently has one file [licensed](https://github.com/freec84/nipy-ecattest/blob/master/LICENSE) under CC0.

I can also post an image that is identical, except with a data block of all zeros.

**Comment by idoimaging** [comment]
That's fine, though it's not a phantom obviously, and is huge.  If you don't need the voxels, they could certainly go.

**Comment by effigies** [comment]
Okay, I'll do the zeroed out version. If there's any metadata I should destroy let me know.

**Comment by effigies** [comment]
It turns out editing ECAT files is actually quite difficult. I suppose I'll go with the original file.
