### ISSUE TITLE
Image orientation issues

### ISSUE THREAD

**Issue by pocolya** [nipy/nibabel#801]
I have a dicom image that is converted to nifti with Dcm2Niix and an analyze segmentation image of the same patient coming from ITKSnap. Unfortunately, ITKSnap truncates the data when converting from DICOM (the double precision isn't accepted) and changes the rotation matrix. When I try to use the segmented image as a mask for Nifti image with Nibabel, I can't make them in the same orientation.

I tried saving either with the header and/or rotation of the other, but nothing works.
raw=nib.load('patient.nii.gz')
rawArray=raw.get_fdata()

seg=nib.load('seg.img')
segArray=seg.get_fdata()

segImage = nib.Nifti1Image(segArray,raw.affine,raw.header)
nib.save(segImage, os.path.join(OUTPUT_FOLDER,'seg_temp.img'))

seg=nib.load('seg_temp.img')
segArray=seg.get_fdata()

SUVArray=numpy.where(segArray==1,rawArray*Factor,0)
SUVImage = nib.Nifti1Image(SUVArray,raw.affine,raw.header)
nib.save(SUVImage, os.path.join(OUTPUT_FOLDER,'selection_suv.img'))

Any ideas on how to solve this?

**Comment by effigies** [comment]
Hi @pocolya, sorry for the delay. Did you resolve your issue?

I don't think there's enough information here to understand what Dcm2niix and ITKSnap are each doing. It might be worth getting some diagnostic information for each:

* Shape: `img.shape`
* Affine: `img.affine`
* Zooms: `img.header.get_zooms()`
* Orientation: `nib.affines.aff2axcodes(img.affine)`

And just in greater detail:

```Python
print(raw.header)
print(seg.header)
```

Out of curiosity, what happens if you just convert to NIfTI and then run ITKSnap on that output, rather than using to conversions from DICOM?

**Comment by pocolya** [comment]
Hi @effigies,

Thank you for your reply, I still don't have a "solution", even though I have a confirmation and an explication from the [currect discussion](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/itksnap-users/6hhoJrpPYM8/27ZP8zf0BgAJ) that ITKsnap alters the image. So, intuitevily, I've doing the same : just copying the original transform on the segmentation.

> Out of curiosity, what happens if you just convert to NIfTI and then run ITKSnap on that output, rather than using to conversions from DICOM?
Because a clinician segments the image in ITKSnap and saves it in Nifti, so whatever I do beforehand if the segmentation is done this way, the original image transform will be altered.

**Comment by effigies** [comment]
Ah, yes. Thanks for linking that discussion. ITK notoriously refuses to respect the sform matrix, relying entirely on the qform. If you're extremely confident that the data are in register, and only the affines differ, it is reasonable to copy the header from one to the other:

```
img_from = nib.load(...)
img_to = nib.load(...)

authoritative_affine = img_from.affine
xform_code = 1 

img_to.set_qform(authoritative_affine, xform_code)
img_to.set_sform(authoritative_affine, xform_code)
# You may also want to do this for img_from, so that the affines match.

img_to.to_filename(...)
```

For more information on the xform codes, refer to [nifti1.h](https://github.com/NIFTI-Imaging/nifti_clib/blob/9659cbecc827e15c07ccc1a03023e8c348aa14fe/niftilib/nifti1.h#L1237-L1272).

**Comment by effigies** [comment]
Please reopen if this needs further discussion.
