### ISSUE TITLE
Q: any plans/possibility to avoid patching versioneer.py?

### ISSUE THREAD

**Issue by yarikoptic** [nipy/nibabel#816]
```shell
$> git grep 'CJM:' versioneer.py 
versioneer.py:    # CJM: Nibabel hack to ensure we can git-archive off-release versions and
versioneer.py:    # CJM: Nibabel fix to avoid hitting unguarded dictionary lookup, better explanation
versioneer.py:    # CJM: Nibabel hack to ensure we can git-archive off-release versions and
```
I wondered if you (@effigies) anyhow considered/discussed with versioneer.py to make it possible to have versioneer.py needed functionality without nibabel patching it?

**Comment by effigies** [comment]
They haven't responded to issues or PRs in years at this point.

**Comment by effigies** [comment]
That said, I'm open to forking, opening a PR, and using that fork unless the fixes we need are eventually included.

**Comment by yarikoptic** [comment]
Ah, I didn't know that it is not active

**Comment by effigies** [comment]
Maybe if we find that we need to hack on it again for this or another project, we could make a nipy fork to consolidate effort and get more eyes on it.

**Comment by effigies** [comment]
Dropped versioneer.
