### ISSUE TITLE
How to use RobustFOV function in nipype.interfaces.fsl

### ISSUE THREAD

**Issue by leonardo-oz** [nipy/nibabel#819]
HI, All. I am trying to remove neck from an MRI sample image using nipype.interfaces.fsl. 

The function I used is as following:

````
    neckRM = fsl.RobustFOV()
    print(help(neckRM))
    neckRM.inputs.in_file = inPath
````
I could not find a way to save the neck removed image or make a reference to it. Can someone shed a light on this?

Thanks.

**Comment by matthew-brett** [comment]
I think you might want the Nipype project issues - but I bet they will recommend you try over at https://neurostars.org/

**Comment by leonardo-oz** [comment]
@matthew-brett , thanks.
