### ISSUE TITLE
How to save each nifti slice into png or jpg in nipype

### ISSUE THREAD

**Issue by leonardo-oz** [nipy/nibabel#820]
Hi, All:

Does nipype provide any function for saving nifti slice into png as pixel in each slice are well above 255, directly dump 2D numpy array can cause most value as either 0, or 255 not gray scale image.  Code snippet is below:

````
   import nibabel as nib
    import cv2 as cv
    
    image = nib.load(inFilePath)
    imageData = image.get_data()
   img_slice = imageData[:, :, 0]
   cv.imwrite("0.jpg", img_slice)

````
![0](https://user-images.githubusercontent.com/55828143/65810328-8e73dc80-e1ec-11e9-86a7-2167dd4ed106.png)

**Comment by effigies** [comment]
This isn't really a nipype question, so I moved it to nibabel.

Your strategy is reasonable, but in cases where the image minimum is non-zero, you might get unexpected behavior. If the goal is to rescale into unsigned bytes, you could use a full rescaling:

```Python
def rescale(data, newmin, newmax):
    return (data - data.min()) / (data.max() - data.min()) * (newmax - newmin)  + newmin

rescaled = np.uint8(rescale(image.get_fdata(), 0, 255))
```

We probably have a function lying around that we use when rescaling data blocks, but you don't really need it here.

**Comment by leonardo-oz** [comment]
@effigies , thanks.
