### ISSUE TITLE
How to save processed slices into a new nifti file

### ISSUE THREAD

**Issue by leonardo-oz** [nipy/nibabel#824]
Hi, All

Given an input nifti image, in.nii.gz, if I intend to crop it from 1/5 slices along z dimension and save the cropped image into a new nifti file with same header except dimensions, how can I do it.
I only figure out how to crop but am not sure about updating the header and save it. Can someone shed a light on this? Thanks.

````
    img = nib.load('in.nii.gz')
    data = img.get_data()
    nbrSlces = data.shape[2]
    nbrCrops = int(nbrSlces * 0.20)
    crop = data[:, :, nbrCrops:]
````

**Comment by effigies** [comment]
To be clear, you just want to crop the first 20% of slices and save the remainder as a new file?

The easiest way to ensure that the metadata is correct is to use the [`slicer`](https://nipy.org/nibabel/reference/nibabel.spatialimages.html#nibabel.spatialimages.SpatialImage.slicer) property:

```Python
img = nib.load('in.nii.gz')
cropped_img = img.slicer[:, :, img.shape[2] // 5:]
cropped_img.to_filename('out.nii.gz')
```

In general, any slices you might want to perform on the data array, you can perform with `img.slicer`. [Fancy indexing](https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html) is not supported, and no filtering or interpolation is done, so you should be careful with interpreting down-sampled data.

**Comment by leonardo-oz** [comment]
Thanks. @effigies

**Comment by leonardo-oz** [comment]
@effigies , Thanks. That's exactly what I am concerned after cropping off 20% of the slices and how the meta data should be updated. 

The other question about slicing is that how can I retrieve the image physical size, like from fsleyes , I can retrieve Size X=179 mm Y=256 mm Z=157 mm?

The last question is  how can I crop the image from specified Z such as 30mm upwards using the information above, and save the rest to the file?

Many Thanks. @effigies

**Comment by effigies** [comment]
Getting the size (or field of view) is relatively easy:

```Python
import numpy as np
import nibabel as nib

img = nib.load('in.nii.gz')
zooms = img.header.get_zooms()  # zooms are the size of the voxels
shape = img.shape
fov = np.array(zooms) * np.array(shape)
```

If you want to slice off the first 30mm off the z direction:

```Python
cropped = img.slicer[:, :, 30 // zooms[2]:]
```

Note that this will slice off less than 30mm if your zooms don't divide neatly into 30.

Also you should probably also be checking `img.header.get_xyzt_units()` to make sure that your voxel sizes are in `mm`, not `um` or `m`.

**Comment by leonardo-oz** [comment]
@effigies , all clear now. Thanks.
