### ISSUE TITLE
Difference in saving nifti files in nibabel

### ISSUE THREAD

**Issue by leonardo-oz** [nipy/nibabel#825]
Dear Nibabel Experts:

I am following nipype tutorial to save files. One approach is to use nib.save(). The other is to use image.to_filename().  But files saved from two methods seems quite different with fsleyes. The latter one is consistent with input file, while the formal is not. Please check the picture below. I was expecting both a and b should perfectly match. I intend to use the formal one, as image_data = image_get_fdata() can give me a numpy array which is easy to get processed for other purpose. Can someone point out what causes the difference in saving and how to fix it? Thanks. The zipped mask file is attached.
[mask.nii.gz](https://github.com/nipy/nibabel/files/3722882/mask.nii.gz)

 

The code snippet is below:
````
    image = nib.load("mask.nii.gz")
    # save method 1
    image.to_filename("a.nii.gz")
    
    # save method 2
    outImg = nib.Nifti1Image(image.get_fdata(), affine=image.header.get_base_affine(), 
    header=image.header)
    nib.save(outImg, "b.nii.gz")
```` 
![image](https://user-images.githubusercontent.com/55828143/66729110-912d2d80-ee8c-11e9-8b00-61f951cb457c.png)

**Comment by leonardo-oz** [comment]
After trial and error, set affine as None as below then it works. But I am still not sure why it works after set affine to None here?

````
outImg = nib.Nifti1Image(image.get_fdata(), None, header=image.header.copy())
````

**Comment by pauldmccarthy** [comment]
The `get_base_affine` method is not what you want - you should use either `image.affine`, or `header.get_best_affine`.

`get_base_affine` returns a 'fall-back' affine, which is only used if the `sform` and `qform` affines are unknown: 

https://nipy.org/nibabel/nifti_images.html#the-fall-back-header-affine

**Comment by leonardo-oz** [comment]
@pauldmccarthy , Thanks for your explanation.
