### ISSUE TITLE
ArrayProxy always casts image data to float64

### ISSUE THREAD

**Issue by effigies** [nipy/nibabel#832]
Consider a BOLD series (obtainable with git-annex [here](https://github.com/neuroscout-datasets/LearningTemporalStructure/blob/master/fmriprep/sub-01/func/sub-01_task-movie_run-01_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz)) saved in a NIfTI-1 with dtype `int16`, `scl_slope == 0.061591435` and `scl_inter == 1839.8748`. Both `scl_slope` and `scl_inter` are `np.float32`:

https://github.com/nipy/nibabel/blob/ddf26830eebdb11470009c3a04047377f29a4732/nibabel/nifti1.py#L49-L50

The ArrayProxy casts these data to `float64`:

```Python
>>> img.dataobj[0, 0, 0, 0].dtype
dtype('float64')
```

Note the following:

```Python
>>> type(img.dataobj.slope)
float
>>> type(img.dataobj.inter)
float
```

This is due to the cast in nifti1.py:

https://github.com/nipy/nibabel/blob/ddf26830eebdb11470009c3a04047377f29a4732/nibabel/nifti1.py#L1164-L1167

If I use:

```Python
>>> unscaled = img.dataobj.get_unscaled()
>>> slope = np.float32(img.dataobj.slope)
>>> inter = np.float32(img.dataobj.inter)
>>> nb.volumeutils.apply_read_scaling(unscaled, slope, inter).dtype
dtype('float32')
```

So the precision of the data available permits us to safely return this data block as float32 (`apply_read_scaling` would bump to float64 if it were needed), but instead we always return float64 data arrays.

This means that `img.get_fdata(dtype=np.float32)` will first load a 64-bit array and then cast it down to 32-bit.

My expectation would generally be to use the smallest data type as the default and scale up at need or request. While I do see a potential argument for using float64 across all image types (e.g., NIfTI-2 and thus CIFTI-2 have 64-bit scales and intercepts) as safe and consistent, that feels to me appropriate for a high-level interface like `get_fdata()`, rather than the low-level load of `np.array(img.dataobj)`.

**Comment by matthew-brett** [comment]
Yes, I noticed this a while ago.  I didn't mean for that to happen, but when I noticed, I didn't do anything about it because I was worried that this might cause subtle changes in the analysis results.  What do you think?

**Comment by effigies** [comment]
Just to get a sense of the potential error, and taking the current slope/inter as representative:

```Python
>>> a = np.arange(-32768, 32768).astype(np.int16)
>>> slope32 = np.float32(img.dataobj.slope)
>>> inter32 = np.float32(img.dataobj.inter)

>>> a32 = slope32 * a + inter32
>>> a64 = slope32.astype(np.float64) * a + inter32.astype(np.float64)

>>> np.max(a64 - a32)                                                                          
0.00018310174345970154

>>> np.max(a64.astype(np.float32) - a32)                                                       
0.00024414062
```

I'm not entirely sure how to think about these differences. They're very small relative to the intercept (~1e-7), and are themselves flips of the 12th or 13th bit. But if you believe in those bits (or need bit-for-bit reproducibility but don't want to pin your libraries), you might not want to lose them.

I do think that with high-resolution and short-TR time series, pushing everything through 64 bits even when the caller specifically requests 32 bit is pretty annoying.

We could think about keeping the current behavior with `get_fdata(dtype=float64)`, while avoiding building the 64-bit array for `get_fdata(dtype=float32)`. Suppose:

```Python
class ArrayProxy:
    def get_scaled(self, dtype=None):
        """Return scaled data with at least as much precision as dtype
        """
        slope = np.asanyarray(self.slope)  # Permit Python float
        if dtype is None:
            dtype = slope.dtype
        slope = slope.astype(dtype)
        inter = np.asanyarray(self.inter).astype(dtype)
        arr = self.get_unscaled()
        return apply_read_scaling(arr, slope, inter)
```

Then `get_fdata()` could become:

```Python
class DataobjImage:
    def get_fdata(self, caching, dtype):
        # check cache
        if isproxy(self.dataobj):
            arr = self.dataobj.get_scaled(dtype)
        else:
            arr = np.asanyarray(self.dataobj).astype(dtype)
        # save cache
```

This puts the control of the precision at all steps in the hands of the caller, and also will help retain the similarity between the processing of NIfTI-1 and NIfTI-2 images with the same data block and scaling parameters.

`ArrayProxy.__array__` can just call `get_scaled()` without parameters to get the format-default precision, which would be what we get from `img.get_data()` and `np.asanyarray(img.dataobj)`.

Not sure yet if I've sold myself on all of the above, but might as well hit send and get some feedback.

@GaelVaroquaux @bthirion I would be interested in hearing your thoughts here. (And anybody else, of course, but this will affect nilearn and nistats pretty directly.)

**Comment by matthew-brett** [comment]
The differences will definitely be small numerically, but of course these can have larger effects when run through an analysis pipeline.

I like your idea, generally.  I'm sure you meant this, but the default for `get_fdata` should still be float64.

**Comment by effigies** [comment]
Okay, I'll work up a first draft today or Sunday. Since it's an API change, it'd be good to make time to get it in before 3.0.
