### ISSUE TITLE
Replace @kw_only_meth/func decorator with "*" argument

### ISSUE THREAD

**Issue by rmarkello** [nipy/nibabel#841]
Python 3 supports the use of `*` in function signatures to denote that subsequent arguments must be supplied as keywords. Historically, `nibabel` has used `nibabel.keyword_only.kw_only_{meth,func}` to do this, instead. Since `nibabel` is no longer supporting Python 2 it might be nice to remove these and just use the '*' syntax! I'd be happy to make a PR for this, if you think it would be desirable.

**Comment by effigies** [comment]
Yup, this would be great.
