### ISSUE TITLE
3.0 todos

### ISSUE THREAD

**Issue by effigies** [nipy/nibabel#849]
A place to note things while looking through the code that need to be done before the 3.0 release.

* [x] Error on `keep_file_open == 'auto'`
https://github.com/nipy/nibabel/blob/fcc54489d04ba218f10ba98140f1596c0ad47553/nibabel/arrayproxy.py#L58-L62

* [x] Remove `minc.py`:
https://github.com/nipy/nibabel/blob/fcc54489d04ba218f10ba98140f1596c0ad47553/nibabel/minc.py#L5-L8

**Comment by rmarkello** [comment]
Here's a few more:

- [ ] Remove `checkwarns.py`:

https://github.com/nipy/nibabel/blob/fcc54489d04ba218f10ba98140f1596c0ad47553/nibabel/checkwarns.py#L18-L19

- [ ] Remove `testing.catch_warn_reset()`:

https://github.com/nipy/nibabel/blob/fcc54489d04ba218f10ba98140f1596c0ad47553/nibabel/testing/__init__.py#L207-L211

- [ ] Remove `MincFile` and `MincImage`:

https://github.com/nipy/nibabel/blob/fcc54489d04ba218f10ba98140f1596c0ad47553/nibabel/minc1.py#L362-L372

**Comment by effigies** [comment]
`@deprecate_with_version` will handle raising an error and give a better error message. I figure the objects themselves can be removed in 3.1.
