### ISSUE TITLE
test_pkg_info fail

### ISSUE THREAD

**Issue by hubutui** [nipy/nibabel#855]
I'm trying to compile the latest release, and here is the fail test log:
```text
FAIL: Test fallback version is up-to-date
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-nibabel/src/nibabel/nibabel/tests/test_pkg_info.py", line 33, in test_fallback_version
    assert (
AssertionError: nibabel.info.VERSION does not match current tag information
```
The complete log: [nibabel-build-log.txt](https://github.com/nipy/nibabel/files/3981431/nibabel-build-log.txt)

**Comment by yarikoptic** [comment]
Hypothesising based on the content here alone, so pardon me if I am wrong: Well I could disable/patch that test away, but  if I get it right, probably test should detect if it is running in the already git exported source - there some .gitattributes (or whatever)  exported variable : https://github.com/nipy/nibabel/blob/master/.gitattributes . Then test should just skip and not test possible packaging repo tags

**Comment by effigies** [comment]
Right, we should definitely fix it to work correctly by the next release, and would definitely appreciate your eyes on any proposed fix... I'm just wondering if any packagers can't work around for this release, forcing a quick fix.

**Comment by hubutui** [comment]
@effigies I can completely skip the check/test. Could we disable particular tests by specify `pytest`'s args or options?

**Comment by effigies** [comment]
We use `nosetests`, not `pytest` yet.

To skip this test, just add `-e test_fallback_version`.

**Comment by hubutui** [comment]
@effigies Oh, it's a typo. I mean `notests`. And I could build nibabel for [Arch Linux CN Repository](https://github.com/archlinuxcn/repo) now, and skip the `test_fallback_version`.

**Comment by effigies** [comment]
Great! Thanks for accommodating this hiccup. I'll keep this issue open until the actual test is fixed...
