### ISSUE TITLE
BUG: API docs fail when nibabel.info.VERSION doesn't match nibabel.__version__

### ISSUE THREAD

**Issue by larsoner** [nipy/nibabel#869]
Currently this page has no links:

https://nipy.org/nibabel/api.html#api

Found by seeing that our `intersphinx` links have [broken in CIs](https://circleci.com/gh/mne-tools/mne-python/17705).

**Comment by effigies** [comment]
Ugh. Thanks.

**Comment by effigies** [comment]
Okay, it's fixed. Apparently our doc build scripts don't love versioneer. I'll try to have that fixed before the next release.

**Comment by effigies** [comment]
Fixed in the `maint/3.0.x` branch. Will release Monday and merge into `master`.
