### ISSUE TITLE
question: how to cast to lower precision without overflow

### ISSUE THREAD

**Issue by kaczmarj** [nipy/nibabel#888]
does nibabel provide a method to cast, say, a float32 image to uint8, without clipping values? i've found [ArrayWriter](https://nipy.org/nibabel/reference/nibabel.arraywriters.html) and the [casting module](https://nipy.org/nibabel/reference/nibabel.casting.html), but it isn't clear to me how i can cast without clipping (while also preserving the data to a reasonable degree).

**Comment by effigies** [comment]
Nibabel automatically finds the scale factors (for NIfTI-1, float32 slope and intercept) to rescale the data into the output dtype.

```
img = Nifti1Image(...)
img.set_data_dtype(np.uint8)
new_img = Nifti1Image.from_bytes(img.to_bytes())
uint8_data = new_img.dataobj.get_unscaled()  # See the unscaled values
scaled_data = new_img.get_fdata(dtype=np.float32)  # See the reconstruction of original values
```

**Comment by satra** [comment]
@effigies - this question comes from the opposite side, imagine you have an image in `dtype=np.float32` that has values greater than 255 and you want to cast it to `np.uint8`. 

if i remember, nibabel doesn't have such a functionality. because this requires nibabel to know that scaling to fit is ok.

**Comment by effigies** [comment]
Can you propose an example that fails? I feel like I answered that...

**Comment by satra** [comment]
@effigies - it works the way you have proposed.

**Comment by kaczmarj** [comment]
thank you @effigies !
