### ISSUE TITLE
CT windowing 

### ISSUE THREAD

**Issue by shanpriya3** [nipy/nibabel#890]
Hi, I would like to apply HU /CT windowing on CT volume to segment Pancreas from abdominal CT. To do so, how to obtain the window width and window center values from a nifti image?

**Comment by effigies** [comment]
I'm not really familiar with this terminology, but you can get the sizes of the voxels:

```Python
img.header.get_zooms()
```

The units:

```Python
img.header.get_xyzt_units()
```

And the number of voxels in each dimension:

```Python
img.shape
```

This should be enough to determine the field-of-view. If the remainder of the question means determining the world coordinates of each voxel, or the value of the voxel nearest a given world coordinate, I would recommend having a read-through of [Coordinate systems and affines](https://nipy.org/nibabel/coordinate_systems.html).

**Comment by shanpriya3** [comment]
Sorry for not being specific.
I have CT volumes in Nifti format. I would like to apply the Hounsfield Unit(HU) windowing to these volumes to get soft tissue information. For doing so, I need RescaleSlope, RescaleIntercept, Window Center and Window Width values. In Dicom, it is possible to get these values using print(image). (
https://vincentblog.xyz/posts/medical-images-in-python-computed-tomography )
I would like to do the same using Nibabel. How to access this information.

**Comment by effigies** [comment]
NIfTI has no concept of window center or width, so you're going to have to find some external source for that information. That might be simply encoding the values on that website.

NIfTI does have the header fields `scl_slope` and `scl_inter`. These are applied automatically through the [image data array](https://nipy.org/nibabel/nibabel_images.html#the-image-data-array). So if the result of `img.get_fdata()` appears in the correct range, then there's nothing else you need to do. If the data array is not in the correct range, then again you will need to find an external source for that information.

**Comment by effigies** [comment]
@shanpriya3 Please reopen if this needs further discussion.
