### ISSUE TITLE
Passing a SpooledTemporaryFile to load

### ISSUE THREAD

**Issue by joshy** [nipy/nibabel#892]
Dear lovely people at nibabel,

thanks a lot for creating and supporting nibabel. Is it possible to have the an additional method for loading from a [SpooledTemporaryFile](https://docs.python.org/3/library/tempfile.html#tempfile.SpooledTemporaryFile) or directly BytesIO? Or to have it possible with the existing load method (check if type is SpooledTemporaryFile and then skip os.stat check)? 

Currently it fails on line 42 in file [loadsave.py](https://github.com/nipy/nibabel/blob/f043012dc7edd34830cc89cc2ce1d736e2ea74d7/nibabel/loadsave.py#L42)
```
try:
    stat_result = os.stat(filename)
except OSError:
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
```
because SpooledTemporaryFile exists only in memory.

Thanks a lot for your time considering this issue and with best regards,
Joshy

PS: My usecase is to run a small [starlette](https://starlette.io) server where uploaded nifti files are received as SpooledTemporaryFiles.

**Comment by effigies** [comment]
Several single file images have a from_bytes method as of 2.5.

**Comment by joshy** [comment]
Hi Chris,

thanks for the fast response. That is exactly what I was missing!
```
import nibabel as nib
t = nib.Nifti1Image.from_bytes(contents)
```
Thanks!
