### ISSUE TITLE
Nibabel future plans for DICOM files support

### ISSUE THREAD

**Issue by BramshQamar** [nipy/nibabel#897]
Hello,

I wanted to ask about Nibabel's future plans for enhancing support for DICOM files. For example, adding a direct function for converting DICOM to Nifti or adding support for different scanners/vendors. 

Thank You,
Bramsh

**Comment by liamtimms** [comment]
@BramshQamar [disclaimer: I am not part of the nibabel team] I always use `dcm2niix` from https://github.com/rordenlab/dcm2niix to convert to NIFTI first. Maintaining a good conversion tool across all scanners/vendors is a complex project on its own and adding it to nibabel would require  significant replication of effort for not much payoff, no?

**Comment by effigies** [comment]
There are some open PRs for improving DICOM support that have quite recently seen some activity. Additionally, @satra had expressed interest in merging components of dcmstack into nibabel.

There are no definite timelines, and I would echo @liamtimms in recommending dcm2niix for conversions.

**Comment by BramshQamar** [comment]
Thanks @effigies and @liamtimms for getting back to me. I always use dcm2niix too and I have tried other tools for converting DICOM to nifti as well. I think dcm2niix works the best among all.

I was just checking with nibabel if they had any plans to have DICOM to nifti converter. It makes sense not to reinvent the wheel.

Thanks,
Bramsh
