### ISSUE TITLE
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "../../499/499_CT.nii.gz"

### ISSUE THREAD

**Issue by ranabanik** [nipy/nibabel#898]
I have worked with 498 images in the similar code below. The 499th image generates the error in the title. I can open and visualize the image in .nii.gz file viewer like ITK and others. The file size is bigger compared to other images of same category.  

`import nibabel as nib
import os

CT = nib.load('/media/banikr2/DATA/emModels/CT-MR_batch2/499/499_CT.nii.gz').get_data()`

what could be the issue? 

Thanks

**Comment by effigies** [comment]
It seems likely there's an issue in the header. Could you run:

```
zcat /media/banikr2/DATA/emModels/CT-MR_batch2/499/499_CT.nii.gz | head -c 1024 > trunc.nii
```

And share the resulting `trunc.nii`?

**Comment by ranabanik** [comment]
`banikr2@banikr:~$ zcat /media/banikr2/DATA/emModels/499/499_CT.nii.gz | head -c 1024 > trunc.nii

gzip: /media/banikr2/DATA/emModels/499/499_CT.nii.gz: not in gzip format
`

I ran it from the terminal.

**Comment by ranabanik** [comment]
> It seems likely there's an issue in the header. Could you run:
> 
> ```
> zcat /media/banikr2/DATA/emModels/CT-MR_batch2/499/499_CT.nii.gz | head -c 1024 > trunc.nii
> ```
> 
> And share the resulting `trunc.nii`?
`banikr2@banikr:~$ zcat /media/banikr2/DATA/emModels/499/499_CT.nii.gz | head -c 1024 > trunc.nii

gzip: /media/banikr2/DATA/emModels/499/499_CT.nii.gz: not in gzip format
`

I ran it from the terminal.

**Comment by effigies** [comment]
That's probably the issue, then. Rename the file without the `.gz`, and it will probably work.

**Comment by ranabanik** [comment]
> That's probably the issue, then. Rename the file without the `.gz`, and it will probably work.

I renamed the file from .nii.gz extension to .nii and it can be read.
I have many other folders behaving similarly. Do you know the reason why such extension mishap may occur?

**Comment by effigies** [comment]
It sees that, at some point, your files either got renamed without being compressed or some tool is saving uncompressed NIfTIs regardless of extension.
