### ISSUE TITLE
test failed on ArchLinux with version 3.1.0

### ISSUE THREAD

**Issue by hubutui** [nipy/nibabel#904]
Hi, I create package for ArchLinux, and it failed to run many tests. After building nibabel, I run the test with:
```
export NIPY_EXTRA_TESTS=slow
pytest -v nibabel
```
And here is the complete log: [python-nibabel-log.txt](https://github.com/nipy/nibabel/files/4508231/python-nibabel-log.txt)

**Comment by effigies** [comment]
```
==> Making package: python-nibabel 3.0.2-1 (Tue Apr 21 14:58:29 2020)
```

Is it possible that you're not building the right version?

**Comment by hubutui** [comment]
Oh, I'm so sorry. I forget to update the pkg version. pkg is updated by lilac robot, and here is the [build log](https://build.archlinuxcn.org/~imlonghao/log/python-nibabel/2020-04-21T01%3A17%3A02.html).  According to the [doc](https://github.com/nipy/nibabel/blob/master/doc/source/devel/advanced_testing.rst#long-running-tests), nibabel switch from nose to pytest. After switch nose to pytest, everything works right. Thanks for your reply.

**Comment by effigies** [comment]
Thanks for checking in!
