### ISSUE TITLE
Is there a corresponding C ++ library function for NiBabel？

### ISSUE THREAD

**Issue by Peterisfar** [nipy/nibabel#912]
Is there a corresponding C ++ library function for NiBabel？

**Comment by aktasfatih** [comment]
You can look into RNifti. It is used to access medical file formats. It has a c++ API. github.com/jonclayden/RNifti/tree/master/standalone

**Comment by matthew-brett** [comment]
But the answer for Nibabel is no - because it's a pure Python library.  I'm sure you know, but you can call Python from within C++;  I have never done that myself.
