### ISSUE TITLE
Saveing Nifti1 changes the data

### ISSUE THREAD

**Issue by soroush361** [nipy/nibabel#921]
Hi,

I have a very short script for image read and write as below:
```
import numpy as np
import nibabel as ni

niftiFile = ni.load('my_image.nii.gz')
header = niftiFile.header
affine = niftiFile.affine
img = niftiFile.get_fdata()

niftiFile2 = ni.Nifti1Image(img, affine=affine, header=header)
niftiFile2.to_filename('my_second_image.nii.gz')

img2 = ni.load('my_second_image.nii.gz').get_fdata()

print(img[10,10,10])
print(img2[10,10,10])
```

Based on the code the print result must be identical, but I got:
```
-844.0
-843.9787130355835
```

I believe it is something related to `dtype`. But I couldn't figure it out.
My python version is `3.7.4` and my Nibabel version is `3.1.0`.
Can anyone help me with this?

**Comment by matthew-brett** [comment]
This is what I expect.  By default, when nibabel Nifti saves an image, it rescales the data to best fit within the output dtype range.  I'm sure you've got an int output dtype, I'm guessing int16. 

If you want to preserve the exact same scaling, you have to jump through some hoops.

**Comment by soroush361** [comment]
> This is what I expect. By default, when nibabel Nifti saves an image, it rescales the data to best fit within the output dtype range. I'm sure you've got an int output dtype, I'm guessing int16.
> 
> If you want to preserve the exact same scaling, you have to jump through some hoops.

Perfect, thank you so much!
I've just cast the array to `np.int16` when I'm saving it and it resolved the issue.

For others who have the same problem:
Nibabel loads the array as `float64` regardless of the header's datatype. Therefore, it is your responsibility to check the header datatype and cast the array to the proper datatype as in the header. This way the data will be preserved.

**Comment by fepegar** [comment]
I've just been bitten by this as well. Would it make sense to print a warning when the dtype of the output array and the header are different?
