### ISSUE TITLE
Affine matrix not the same between Nibabel and SPM

### ISSUE THREAD

**Issue by seralouk** [nipy/nibabel#924]
I just came across this unexpected behavior and incosistency between SPM (matlab) and Nibabel (Python) when looking at the affine transformation matrix of the same nifti file.

The matrices are not the same. 

Matlab using SPM:
```
V=spm_vol('/Users/loukas/Desktop/test.nii');
V.mat

ans =
    -2     0     0    92
     0     2     0  -128
     0     0     2   -74
     0     0     0     1
```

Python
```
import numpy as np, nibabel as nib

img = nib.load("/Users/loukas/Desktop/test.nii")
img.affine
array([[  -2.,    0.,    0.,   90.],
       [   0.,    2.,    0., -126.],
       [   0.,    0.,    2.,  -72.],
       [   0.,    0.,    0.,    1.]])
```

**Comment by effigies** [comment]
Might be a qform/sform difference?

```
>>> img.affine
>>> img.get_qform(coded=True)
>>> img.get_sform(coded=True)
>>> img.get_qform()
>>> img.get_sform()
```

**Comment by matthew-brett** [comment]
I think it's due to the difference in Python and Matlab array indexing.  Python is 0-based, and Matlab is 1-based.  So - for example. the first voxel will be 0, 0, 0 in Python.  It will have mm coordinate 90,. -126, -72.   The first voxel will be 1, 1, 1 in Matlab, and will have coordinate 92 - 2 = 90, -128 + 2 = -126, -74 + 2 = 72.   So the affines give the same mm for the corresponding array index.

**Comment by seralouk** [comment]
> Might be a qform/sform difference?
> 
> ```
> >>> img.affine
> >>> img.get_qform(coded=True)
> >>> img.get_sform(coded=True)
> >>> img.get_qform()
> >>> img.get_sform()
> ```

Actually no.. Weird situation.
I am sharing the nifti here:  https://www.dropbox.com/s/zb4syi1e6p66gk5/test.nii?dl=0

**Comment by seralouk** [comment]
> I think it's due to the difference in Python and Matlab array indexing. Python is 0-based, and Matlab is 1-based. So - for example. the first voxel will be 0, 0, 0 in Python. It will have mm coordinate 90,. -126, -72. The first voxel will be 1, 1, 1 in Matlab, and will have coordinate 92 - 2 = 90, -128 + 2 = -126, -74 + 2 = 72. So the affines give the same mm for the corresponding array index.

Amazing. This is the case indeed. Just another quick think. 
Even if affines give the same mm for the corresponding array index, I notice that the estimated scanner-coordinates in mm are not the same between Nibabel & Matlab.

Nifti file: https://www.dropbox.com/s/zb4syi1e6p66gk5/test.nii?dl=0

**Matlab**
```
V=spm_vol('test.nii');
[intensityValues,xyzCoordinates ]=spm_read_vols(V);

xyzCoordinates(:,1)

    90
  -126
   -72
```

**Python**
```
img = nib.load("test.nii")
array_indices = np.indices(img.shape).transpose(1, 2, 3, 0)
xyzCoordinates_python = nib.affines.apply_affine(img.affine, array_indices)

xyzCoordinates_python = xyzCoordinates_python.reshape(3,-1, order='F') # to match matlab ordering

xyzCoordinates_python[:,0]
array([92., 90., 88.])
```
What am I missing here?

**Comment by matthew-brett** [comment]
You need to flip the coordinate axis to be the first before doing your reshape, to get the equivalent to the SPM XYZ array:

```python
xyzCoordinates_python = nib.affines.apply_affine(img.affine, array_indices)
# Put Coordinate axis first.
xyzCoordinates_python = xyzCoordinates_python.transpose(3, 0, 1, 2)
# Flatten the other axes, with Matlab ordering.
xyzCoordinates_python = xyzCoordinates_python.reshape(3,-1, order='F')
```

**Comment by seralouk** [comment]
Once again thanks. Another way would be using `ravel` (equivalent to your code) as follows:

```
array_indices = np.indices(img.shape).transpose(1, 2, 3, 0)
xyzCoordinates_python = nib.affines.apply_affine(img.affine, array_indices)

xyzCoordinates_python = xyzCoordinates_python.ravel().reshape(3,-1, order='F') # to match matlab ordering

xyzCoordinates_python[:,0]
```
Cheers!
