### ISSUE TITLE
RGB of nii files

### ISSUE THREAD

**Issue by arushgupta2007** [nipy/nibabel#928]
Hi,
I am getting image data in 16bit while I would like to get the image data in RGB.
The current information is got by ImageJ:
![20200701_214430](https://user-images.githubusercontent.com/39236387/86267488-67679280-bbe4-11ea-9f9c-7fb854deb21e.jpg)
Is there a API for this?
I could not find it in the docs!
Thanks

**Comment by effigies** [comment]
To be clear, you have a NIfTI file with RGB contents that isn't being correctly read by nibabel? Or you have an RGB image you would like to encode as a NIfTI file?

**Comment by arushgupta2007** [comment]
Hi,
Thanks for the quick response
I have a .nii file from which I want image data as RGB
Thanks

**Comment by effigies** [comment]
Is it an RGB image?

```Python
import nibabel as nb
img = img.load(fname)
print(img.get_data_dtype())
```

**Comment by arushgupta2007** [comment]
Hi,
I get this as the output:
```
int16
```

**Comment by arushgupta2007** [comment]
Hi,
I found a workaround to my problem.
I normalized my image data using opencv to scale all values from 0 to 255 but keeping datatype as int16
```python
cv2.normalize(img_in, img_out, 0, 255, cv2.NORM_MINMAX)
```
Thanks
