### ISSUE TITLE
Test suite failures

### ISSUE THREAD

**Issue by tillea** [nipy/nibabel#937]
Hi,
the current Debian package is not really up to date and thus the [bug log](https://bugs.debian.org/964610) not relevant for your latest version.  However, I have updated nibabel in Debian packaging Git and realised that there are also several test suite errors with Python3.8.  Here is the log:

    ======================================================================
    ERROR: nibabel.cmdline.tests.test_conform.test_default
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_default() missing 1 required positional argument: 'tmpdir'

    ======================================================================
    ERROR: nibabel.cmdline.tests.test_conform.test_nondefault
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_nondefault() missing 1 required positional argument: 'tmpdir'

    ======================================================================
    ERROR: nibabel.externals.tests.test_netcdf.test_read_write_files
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_read_write_files() missing 1 required positional argument: 'tmp_path'

    ======================================================================
    ERROR: nibabel.gifti.tests.test_giftiio.test_read_deprecated
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_read_deprecated() missing 1 required positional argument: 'tmp_path'

    ======================================================================
    ERROR: nibabel.tests.test_data.test_data_path
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_data_path() missing 1 required positional argument: 'with_nimd_env'

    ======================================================================
    ERROR: nibabel.tests.test_data.test_make_datasource
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_make_datasource() missing 1 required positional argument: 'with_nimd_env'

    ======================================================================
    ERROR: nibabel.tests.test_data.test_bomber
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/build/nibabel-3.1.1/nibabel/tests/test_data.py", line 206, in test_bomber
        b.any_attribute  # no error
      File "/build/nibabel-3.1.1/nibabel/data.py", line 316, in __getattr__
        raise BomberError(
    nibabel.data.BomberError: Trying to access attribute "any_attribute" of non-existent data "bomber example"

    a message

    ======================================================================
    ERROR: nibabel.tests.test_data.test_datasource_or_bomber
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_datasource_or_bomber() missing 1 required positional argument: 'with_nimd_env'

    ======================================================================
    ERROR: nibabel.tests.test_environment.test_user_dir
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_user_dir() missing 1 required positional argument: 'with_environment'

    ======================================================================
    ERROR: nibabel.tests.test_euler.test_euler_mat_2
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_euler_mat_2() missing 3 required positional arguments: 'x', 'y', and 'z'

    ======================================================================
    ERROR: nibabel.tests.test_euler.test_quats
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_quats() missing 3 required positional arguments: 'x', 'y', and 'z'

    ======================================================================
    ERROR: nibabel.tests.test_init.test_nibabel_test
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_nibabel_test() missing 4 required positional arguments: 'verbose', 'v_args', 'doctests', and 'coverage'

    ======================================================================
    ERROR: nibabelok

    ======================================================================
    ERROR: nibabel.cmdline.tests.test_conform.test_default
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_default() missing 1 required positional argument: 'tmpdir'

    ======================================================================
    ERROR: nibabel.cmdline.tests.test_conform.test_nondefault
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_nondefault() missing 1 required positional argument: 'tmpdir'

    ======================================================================
    ERROR: nibabel.externals.tests.test_netcdf.test_read_write_files
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_read_write_files() missing 1 required positional argument: 'tmp_path'

    ======================================================================
    ERROR: nibabel.gifti.tests.test_giftiio.test_read_deprecated
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_read_deprecated() missing 1 required positional argument: 'tmp_path'

    ======================================================================
    ERROR: nibabel.tests.test_data.test_data_path
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_data_path() missing 1 required positional argument: 'with_nimd_env'

    ======================================================================
    ERROR: nibabel.tests.test_data.test_make_datasource
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_make_datasource() missing 1 required positional argument: 'with_nimd_env'

    ======================================================================
    ERROR: nibabel.tests.test_data.test_bomber
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/build/nibabel-3.1.1/nibabel/tests/test_data
    ======================================================================
    ERROR: nibabel.tests.test_scaling.test_finite_range
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_finite_range() missing 2 required positional arguments: 'in_arr' and 'res'

    ======================================================================
    ERROR: nibabel.tests.test_scaling.test_a2f_mn_mx
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_a2f_mn_mx() missing 1 required positional argument: 'out_type'

    ======================================================================
    ERROR: nibabel.tests.test_scaling.test_array_file_scales
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_array_file_scales() missing 2 required positional arguments: 'in_type' and 'out_type'

    ======================================================================
    ERROR: nibabel.tests.test_scaling.test_scaling_in_abstract
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_scaling_in_abstract() missing 3 required positional arguments: 'category0', 'category1', and 'overflow'

    ======================================================================
    ERROR: nibabel.tests.test_scripts.test_nib_ls
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_nib_ls() missing 1 required positional argument: 'args'

    ======================================================================
    ERROR: nibabel.tests.test_spaces.test_slice2volume_exception
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_slice2volume_exception() missing 2 required positional arguments: 'index' and 'axis'

    ======================================================================
    ERROR: nibabel.tests.test_testing.test_assert_re_in
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_assert_re_in() missing 2 required positional arguments: 'regex' and 'entries'

    ======================================================================
    ERROR: nibabel.tests.test_quaternions.test_qrotate
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_qrotate() missing 3 required positional arguments: 'vec', 'M', and 'q'

    ======================================================================
    ERROR: nibabel.tests.test_quaternions.test_quaternion_reconstruction
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_quaternion_reconstruction() missing 1 required positional argument: 'q'

    ======================================================================
    ERROR: nibabel.tests.test_scaling.test_finite_range
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_finite_range() missing 2 required positional arguments: 'in_arr' and 'res'

    ======================================================================
    ERROR: nibabel.tests.test_scaling.test_a2f_mn_mx
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_a2f_mn_mx() missing 1 required positional argument: 'out_type'

    ======================================================================
    ERROR: nibabel.tests.test_scaling.test_array_file_scales
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_array_file_scales() missing 2 required positional arguments: 'in_type' and 'out_type'

    ======================================================================
    ERROR: nibabel.tests.test_scaling.test_scaling_in_abstract
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_scaling_in_abstract() missing 3 required positional arguments: 'category0', 'category1', and 'overflow'

    ======================================================================
    ERROR: nibabel.tests.test_scripts.test_nib_ls
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_nib_ls() missing 1 required positional argument: 'args'

    ======================================================================
    ERROR: nibabel.tests.test_spaces.test_slice2volume_exception
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_slice2volume_exception() missing 2 required positional arguments: 'index' and 'axis'

    ======================================================================
    ERROR: nibabel.tests.test_testing.test_assert_re_in
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    TypeError: test_assert_re_in() missing 2 required positional arguments: 'regex' and 'entries'

    ----------------------------------------------------------------------
    Ran 2018 tests in 164.382s

    FAILED (SKIP=64, errors=26)

I admit I have not checked recent commits past version 3.1.1 whether some of these tests are fixed meanwhile.

Kind regards, Andreas.

**Comment by effigies** [comment]
I assume you're using nose? We've switched to purest.

**Comment by effigies** [comment]
pytest

**Comment by matthew-brett** [comment]
`pytest` in its purest form?  :)

**Comment by tillea** [comment]
On Tue, Jul 21, 2020 at 04:45:56AM -0700, Matthew Brett wrote:
> `pytest` in its purest form?  :)
:-)
OK, purest `pytest` works - feel free to close the bug.  Thank you
for the quick and helpful response, Andreas.

**Comment by effigies** [comment]
Thanks for checking back.
