### ISSUE TITLE
extract information from surf/rh.thickness and so on, then create a feature matrix

### ISSUE THREAD

**Issue by tanjia123456** [nipy/nibabel#953]
Hello, my subject is brain parcellation. Now, I need to create a feature matrix(N*D) by six features from bert/surf/rh.thickness sulc curv area volume jacabian_white. But, I don't konw how to do.  In my oppion, first step,extract the six feature according the vertices. Second step, make a feature matrix by the extracted information.
By the way, the N is number of the node(vertices) and D is the number of the feature.
could you plaease help me ?

**Comment by effigies** [comment]
To load morphometry data, you can use [nibabel.freesurfer.io.read_morph_data](https://nipy.org/nibabel/reference/nibabel.freesurfer.html#nibabel.freesurfer.io.read_morph_data). This will return numpy ndarrays that can be stacked as needed.

**Comment by tanjia123456** [comment]
I have tried it by myself. 
`import numpy as np

def read_morph_data(filepath):
   
    with open("rh.thickness", "rb") as fobj:
        magic = _fread3(fobj)
        if magic == 16777215:
            vnum = np.fromfile(fobj, ">i4", 3)[0]
            thickness = np.fromfile(fobj, ">f4", vnum)
        else:
            vnum = magic
            _fread3(fobj)
            thickness = np.fromfile(fobj, ">i2", vnum) / 100
    return thickness


def _fread3(fobj):
    b1, b2, b3 = np.fromfile(fobj, ">u1", 3)
    return (b1 << 16) + (b2 << 8) + b3


read_thickness=read_morph_data("rh.thickness")
'''with open("rhthickness.txt","w") as f:
    f.write(read_thickness)'''
print(read_thickness)`

but  I want get:
vertex_index     thickness
1                      1.185884
2                      1.1276183
3                      1.0460092

**Comment by tanjia123456** [comment]
I have solved my problem, Thank you very much!
