### ISSUE TITLE
some command  to template to fsaverage5

### ISSUE THREAD

**Issue by tanjia123456** [nipy/nibabel#956]
hello, I'm sorry to bother you. do you know how to template the /bert/surf to fsaverage5? 
My subject is to use vertex , feature ,label and so on to create a matrix.
but,the number of vertex is too large to create a adj_matrix, so there's a memoryerror.

The template operation is to generate surf files for freesurfer processing, mainly rh.white rh.annot rh.thickness in the surf folder.
I have knowed the mri_surf2surf command may useful.
Can this operation operate on folders? Still can only register a single file (rh.white)？

**Comment by effigies** [comment]
The FreeSurfer mailing list (https://mail.nmr.mgh.harvard.edu/mailman/listinfo/freesurfer) is a better place for help with FreeSurfer tools and data structures.
