### ISSUE TITLE
Trackvis header saved with Dipy (nibabel) is not read by Matlab or other tools

### ISSUE THREAD

**Issue by alecrimi** [nipy/nibabel#959]
## Description
I am having issues loading some information from tracts saved by Dipy from Matlab or other things that need certain informations on the header
Dipy  0.16.
Nibabel  2.5.2

I use the library nibabel:
```
import nibabel as nib 
from nibabel import trackvis as tv
```

and I save the tracks like this
```
hdr = nib.trackvis.empty_header()
hdr['voxel_size'] = img.get_header().get_zooms()[:3]
hdr['voxel_order'] = 'LAS'
hdr['dim'] = fa.shape
hdr['n_count'] = len(csd_streamlines)
tensor_streamlines_trk = ((sl, None, None) for sl in csd_streamlines)
ten_sl_fname = 'tensor_streamlines_2182_1_b3000.trk'
nib.trackvis.write(ten_sl_fname, tensor_streamlines_trk, hdr, points_space='voxel')
```

one of the missing field which is very important to me is "n_count"
the command `len(csd_streamlines)` produces a real integer number, and it seems stored into hdr['n_count'].
However, when read by [TRK-read in Matlab](https://github.com/johncolby/along-tract-stats/blob/master/trk_read.m) 
it appears empty (set to zero). 

> Subscript indices must either be real positive integers or logicals.

>Error in trk_read_raw (line 56)
>tracks(header.n_count).nPoints = 0;

If I take the same file, first I open it in trackvis and then do the same, the problem is gone. It is like trackvis sort out the issue.

**Comment by skoudoro** [comment]
Hi @alecrimi,

As we can see [here](https://github.com/nipy/nibabel/blob/30c0bc561e0f34763c415a3fdc2b39cf0789a4ea/nibabel/streamlines/header.py#L10), it seems that the field `n_count` became `nb_streamlines` with the new streamlines API. it could be one reason.  Concerning the why, I think @MarcCote or @frheault will have more answers. 

In any case, we need to update this point

**Comment by alecrimi** [comment]
'''
File "tract.py", line 74, in <module>
    hdr['nb_streamlines'] = 300 #len(csd_streamlines)
ValueError: no field of name nb_streamlines
'''
I don't think this is the way

**Comment by MarcCote** [comment]
Hi @alecrimi, it seems you are using the old trackvis interface. Let me know if that's not the case, but you should have seen a deprecation warning like
> "The trackvis interface has been deprecated and will be removed "
              "in v4.0; please use the 'nibabel.streamlines' interface." 

Can I suggest you to try @frheault's `StatefulTractogram` to save your streamlines to a TRK file? According to the [documentation](https://www.dipy.org/documentation/1.2.0./examples_built/streamline_formats/#example-streamline-formats), you should be able to do something like this:
```python
from dipy.io.stateful_tractogram import Space, StatefulTractogram
tractogram = StatefulTractogram(csd_streamlines, reference=img, Space.VOX)
save_tractogram(tractogram, 'tensor_streamlines_2182_1_b3000.trk')
```

**Comment by MarcCote** [comment]
@effigies once 4.0 is out, I think this issue can be closed as it relates to the old trackvis interface.

**Comment by effigies** [comment]
Nothing to fix (AFAICT) so we can go ahead and close now.
