### ISSUE TITLE
Pylance reports NoReturn for Nifti1Image.from_bytes 

### ISSUE THREAD

**Issue by Spenhouet** [nipy/nibabel#993]
We use the method `Nifti1Image.from_bytes` and it works as expected but Pylance (what we use for static type checking) reports that this method has no return value.
This leads to all subsequent code being marked as unreachable.

Following the implementation leads to `FileBasedImage.from_file_map`:

```python
@classmethod
def from_file_map(klass, file_map):
    raise NotImplementedError
```

Pylance is not wrong in reporting that `from_bytes` has no return value.
I guess that Nibabel is doing something sketchy for `from_bytes` to still work.

Can this be improved?

**Comment by effigies** [comment]
It looks like Pylance isn't following the method resolution order? from_file_map is implemented in AnalyzeImage.

**Comment by matthew-brett** [comment]
Is the type checking also testing the base classes?   The `NotImplemented` error is a fairly standard way of indicating a virtual method on a base class.  Is there some recommendation that y'all know if to placate type checking for these kinds of virtual methods?

**Comment by Spenhouet** [comment]
@matthew-brett Not completely sure what a virtual method is but I would probably make it an [abstract method](https://docs.python.org/3/library/abc.html#abc.abstractmethod).

**Comment by effigies** [comment]
That looks like it's going to require a refactorization of our class hierarchy with abstract base classes. Happy to review if someone wanted to take that on, but it might end up being pretty involved.

I think reporting it as an issue with pylance might be the quicker path to a fix.

**Comment by effigies** [comment]
@Spenhouet Would you mind having another look at nibabel 5.0.1? We have added type annotations to a significant portion of the image API.
