### ISSUE TITLE
[Doc] Document how to convert a list of 3D nii images to 4D nibabel image.

### ISSUE THREAD

**Issue by DasDominus** [nipy/nibabel#994]
For context, I have several datasets where:
each run has X scans and each scan is one .nii image

The documentation mentioned the image to be of 4d form:
https://nipy.org/nibabel/gettingstarted.html

eg. (x, y, z, time)

My understanding is that a new nibabel image can be simply created if I concat all scans together to form one .nii.gz image.

However, I have yet to find a function/util for this (or perhaps I missed something)...

Thanks!

**Comment by DasDominus** [comment]
After some digging around, this is actually achievable via SPM -> Util -> 3D to 4D file conversion
It would be nice to document this in the user guide somewhere.

**Comment by effigies** [comment]
I think the function you're looking for is [concat_images](https://nipy.org/nibabel/reference/nibabel.funcs.html#nibabel.funcs.concat_images).

**Comment by DasDominus** [comment]
ah thanks @effigies ! I indeed missed this part in the doc XD
