### ISSUE TITLE
Cannot read '.img.gz' nifti file. 

### ISSUE THREAD

**Issue by sunshichen** [nipy/nibabel#997]
Nibabel cannot read ```.img.gz``` file directly. It could only recognize ```.img``` format files. 
```python
import nibabel as nib
sample_file = 'xxx.mri.img.gz'
data = nib.load(sample_file)
```
output
```python
ImageFileError: Cannot work out file type of "../data/xxx.mri.img.gz"
```

Btw, the simpleITK can read it as [link](https://simpleitk.readthedocs.io/en/master/IO.html#images)

So is there a way to solve this problem? Thx.

**Comment by pauldmccarthy** [comment]
Are you sure that the file is actually a gzip file? What happens if you rename it so it ends with `.img`?

**Comment by effigies** [comment]
Without seeing the file, it's hard to diagnose. Are you able to share it? And is there a corresponding hdr.gz?
