### ISSUE TITLE
Resize nii image getting the modified affine information

### ISSUE THREAD

**Issue by SouthAmericaB** [nipy/nibabel#998]
Hello every body!

I'm trying to resize nii images but I don't know how to modify its affine information to have the reference space information.
I've seen some ways to do that but you have to put your "target_affine" and for me it's a unknown data.

Could you help me, please?
Thank you very much in advance :)

**Comment by effigies** [comment]
Can you elaborate on what you mean by resize? For example, are you trying to crop empty space from the edges of the image, or change the size of voxels?

**Comment by SouthAmericaB** [comment]
Hi @effigies !
Sorry, I mean resize all the image (without cropping) from (512,512,n_slices) to (256,256,n_slices)
What I want is resize the nii image and algo obtain the new affine and header information.

**Comment by effigies** [comment]
Got it. We have a function to determine the affine for these types of transformations: [rescale_affine](https://nipy.org/nibabel/reference/nibabel.affines.html#nibabel.affines.rescale_affine)

You can also [slice](https://nipy.org/nibabel/reference/nibabel.spatialimages.html#nibabel.spatialimages.SpatialImage.slicer) an image with `img.slicer[::2, ::2, :]`, which will use that function to update the affine automatically. Note, though, that this does not anti-alias, so if you haven't already considered [aliasing](https://en.wikipedia.org/wiki/Aliasing) in your resize algorithm, please see [this notebook](https://nbviewer.jupyter.org/urls/dl.dropbox.com/s/s0nw827nc4kcnaa/Aliasing.ipynb?flush_cache=true).

You might want something like:

```Python
from scipy import ndimage as ndi

def blur(img, sigma):
    return img.__class__(ndi.gaussian_filter(img.dataobj, sigma), img.affine, img.header)

# Use (scale factors - 1) / 2, not guaranteed to be a good choice...
downsampled_img = blur(img, sigma=[0.5, 0.5, 0]).slicer[::2, ::2, :]
```

**Comment by SouthAmericaB** [comment]
Thank you very much @effigies !

I'm trying to use that function but it doesn't appear:
![image](https://user-images.githubusercontent.com/49905756/108223513-2f449e00-713a-11eb-9819-f46e1a6b8a16.png)

I've checked  and upgrade my nibabel version but the function doesn't appear.

Do you know why could be that?

**Comment by effigies** [comment]
What version of nibabel are you using? Note that if you are in Python 2 still, you will not be able to upgrade to nibabel 3 or higher.

**Comment by SouthAmericaB** [comment]
Ok. Now it appears. I'm going to try.
Thanks!

**Comment by SouthAmericaB** [comment]
Sorry, but I have another question: 

Regarding the input parameters:
rescale_affine(affine_old, **old_shape (512,512,nslices)?)**, new_zooms, **new_shape (256,256,nslices)?**)

I'm not sure what I have to set in the "shape" input parameters. 
The volume image shape? The volume affines matrix shape?

Thank you ver much :)

**Comment by effigies** [comment]
I would use it like so:

```Python
new_zooms = np.array(img.header.get_zooms()) * [2, 2, 1]
new_shape = np.array(img.shape) // [2, 2, 1]
new_affine = rescale_affine(img.affine, img.shape, new_zooms, new_shape)
```

**Comment by SouthAmericaB** [comment]
Thank you very much for your attention @effigies 

Now, it works! I appreciate it a lot :)

All the best!

**Comment by effigies** [comment]
Glad to hear it. Good luck with your project!
